-- Execute each role section in a separate session with USE SECONDARY ROLES NONE.
-- Expected DENY statements intentionally raise authorization errors.

-- Dedicated consumer: Semantic View SELECT/REFERENCES = ALLOW; direct Gold SELECT = DENY.
USE ROLE TRUSTED_AI_SEMANTIC_CONSUMER; USE SECONDARY ROLES NONE; USE WAREHOUSE COMPUTE_WH;
SELECT * FROM SEMANTIC_VIEW(
  TRUSTED_AI_GOVERNANCE.SEMANTIC.TRUSTED_BANKING_OPERATIONS
  DIMENSIONS period_comparison.period
  METRICS period_comparison.high_value_exception_rate
);
DESCRIBE SEMANTIC VIEW TRUSTED_AI_GOVERNANCE.SEMANTIC.TRUSTED_BANKING_OPERATIONS;
SELECT COUNT(*) FROM TRUSTED_AI_GOVERNANCE.GOLD.PAYMENT_EXCEPTION_INVESTIGATION;

-- Bronze reader and tag administrator: Semantic View business access = DENY.
USE ROLE TRUSTED_AI_BRONZE_READER; USE SECONDARY ROLES NONE; USE WAREHOUSE COMPUTE_WH;
SELECT * FROM SEMANTIC_VIEW(TRUSTED_AI_GOVERNANCE.SEMANTIC.TRUSTED_BANKING_OPERATIONS DIMENSIONS investigation.exception_id);
USE ROLE TRUSTED_AI_TAG_ADMIN; USE SECONDARY ROLES NONE; USE WAREHOUSE COMPUTE_WH;
SELECT * FROM SEMANTIC_VIEW(TRUSTED_AI_GOVERNANCE.SEMANTIC.TRUSTED_BANKING_OPERATIONS DIMENSIONS investigation.exception_id);

-- Auditor: approved registry/deployment evidence and Semantic View structure = ALLOW; business result = DENY.
USE ROLE TRUSTED_AI_AUDITOR; USE SECONDARY ROLES NONE; USE WAREHOUSE COMPUTE_WH;
SELECT COUNT(*) FROM TRUSTED_AI_GOVERNANCE.GOVERNANCE.SEMANTIC_OBJECT_REGISTRY;
SELECT COUNT(*) FROM TRUSTED_AI_GOVERNANCE.AUDIT.SEMANTIC_DEPLOYMENT_EVIDENCE;
DESCRIBE SEMANTIC VIEW TRUSTED_AI_GOVERNANCE.SEMANTIC.TRUSTED_BANKING_OPERATIONS;
SELECT * FROM SEMANTIC_VIEW(TRUSTED_AI_GOVERNANCE.SEMANTIC.TRUSTED_BANKING_OPERATIONS DIMENSIONS investigation.exception_id);

-- Data steward: approved semantic governance and structure = ALLOW; business result = DENY.
USE ROLE TRUSTED_AI_DATA_STEWARD; USE SECONDARY ROLES NONE; USE WAREHOUSE COMPUTE_WH;
SELECT COUNT(*) FROM TRUSTED_AI_GOVERNANCE.GOVERNANCE.SEMANTIC_OBJECT_REGISTRY;
DESCRIBE SEMANTIC VIEW TRUSTED_AI_GOVERNANCE.SEMANTIC.TRUSTED_BANKING_OPERATIONS;
SELECT * FROM SEMANTIC_VIEW(TRUSTED_AI_GOVERNANCE.SEMANTIC.TRUSTED_BANKING_OPERATIONS DIMENSIONS investigation.exception_id);
