-- Execute in isolated authorized sessions and capture actual ALLOW/DENY evidence.
-- DATA_ENGINEER transform/write = ALLOW; DATA_STEWARD read = ALLOW, destructive DML = DENY.
-- BRONZE_READER Silver read = DENY; TAG_ADMIN business-data read = DENY; AUDITOR evidence read = ALLOW, DML = DENY.
SHOW GRANTS TO ROLE TRUSTED_AI_DATA_ENGINEER;
SHOW GRANTS TO ROLE TRUSTED_AI_DATA_STEWARD;
SHOW GRANTS TO ROLE TRUSTED_AI_BRONZE_READER;
SHOW GRANTS TO ROLE TRUSTED_AI_TAG_ADMIN;
SHOW GRANTS TO ROLE TRUSTED_AI_AUDITOR;
