-- G2.3 role-boundary tests
-- Each section must be run by a principal authorized to assume the named role.
-- Role switching is commented out deliberately. Capture actual ALLOW/DENY evidence.

SELECT CURRENT_ROLE() AS EXECUTING_ROLE;

-- DATA_ENGINEER — expected ALLOW for governed load/read/evidence DML.
-- USE ROLE TRUSTED_AI_DATA_ENGINEER;
-- SELECT COUNT(*) FROM TRUSTED_AI_GOVERNANCE.BRONZE.PAYMENT_RAW; -- expected ALLOW
-- SELECT COUNT(*) FROM TRUSTED_AI_GOVERNANCE.AUDIT.INGESTION_RUN; -- expected ALLOW
-- LIST @TRUSTED_AI_GOVERNANCE.PLATFORM.SOURCE_STAGE;              -- expected ALLOW

-- DATA_STEWARD — expected ALLOW for metadata/evidence; DENY for destructive writes.
-- USE ROLE TRUSTED_AI_DATA_STEWARD;
-- SELECT COUNT(*) FROM TRUSTED_AI_GOVERNANCE.GOVERNANCE.INGESTION_SOURCE_REGISTRY; -- expected ALLOW
-- SELECT COUNT(*) FROM TRUSTED_AI_GOVERNANCE.AUDIT.INGESTION_FILE_EVIDENCE;        -- expected ALLOW
-- DELETE FROM TRUSTED_AI_GOVERNANCE.BRONZE.PAYMENT_RAW; -- expected DENY; do not execute without an isolated authorized test session.

-- BRONZE_READER — expected ALLOW only for approved Bronze reads.
-- USE ROLE TRUSTED_AI_BRONZE_READER;
-- SELECT COUNT(*) FROM TRUSTED_AI_GOVERNANCE.BRONZE.PAYMENT_RAW; -- expected ALLOW
-- SELECT * FROM TRUSTED_AI_GOVERNANCE.AUDIT.INGESTION_RUN; -- expected DENY.
-- INSERT INTO TRUSTED_AI_GOVERNANCE.BRONZE.PAYMENT_RAW(PAYMENT_ID) VALUES ('PROHIBITED'); -- expected DENY.

-- TAG_ADMIN — tag administration does not imply Bronze data access.
-- USE ROLE TRUSTED_AI_TAG_ADMIN;
-- SHOW TAGS IN SCHEMA TRUSTED_AI_GOVERNANCE.GOVERNANCE; -- expected ALLOW
-- SELECT * FROM TRUSTED_AI_GOVERNANCE.BRONZE.CUSTOMER_RAW; -- expected DENY.

-- AUDITOR — read-oriented evidence only.
-- USE ROLE TRUSTED_AI_AUDITOR;
-- SELECT COUNT(*) FROM TRUSTED_AI_GOVERNANCE.AUDIT.INGESTION_RUN; -- expected ALLOW
-- SELECT COUNT(*) FROM TRUSTED_AI_GOVERNANCE.GOVERNANCE.INGESTION_SOURCE_REGISTRY; -- expected ALLOW
-- UPDATE TRUSTED_AI_GOVERNANCE.AUDIT.INGESTION_RUN SET STATUS='ALTERED'; -- expected DENY.
-- INSERT INTO TRUSTED_AI_GOVERNANCE.BRONZE.PAYMENT_RAW(PAYMENT_ID) VALUES ('PROHIBITED'); -- expected DENY.

-- Grant inspection supports review without pretending unexecuted DENY statements passed.
-- SHOW GRANTS TO ROLE TRUSTED_AI_DATA_ENGINEER;
-- SHOW GRANTS TO ROLE TRUSTED_AI_DATA_STEWARD;
-- SHOW GRANTS TO ROLE TRUSTED_AI_BRONZE_READER;
-- SHOW GRANTS TO ROLE TRUSTED_AI_TAG_ADMIN;
-- SHOW GRANTS TO ROLE TRUSTED_AI_AUDITOR;
