-- Execute each role section in a separate session with secondary roles disabled.
-- Capture expected/actual/result; expected DENY statements intentionally raise authorization errors.

-- DATA_ENGINEER: Gold SELECT and zero-row transformation DML = ALLOW.
USE ROLE TRUSTED_AI_DATA_ENGINEER; USE SECONDARY ROLES NONE;
SELECT COUNT(*) FROM TRUSTED_AI_GOVERNANCE.GOLD.PAYMENT_EXCEPTION_INVESTIGATION;
DELETE FROM TRUSTED_AI_GOVERNANCE.GOLD.PAYMENT_EXCEPTION_INVESTIGATION WHERE 1=0;

-- DATA_STEWARD: Gold/catalog SELECT = ALLOW; destructive Gold DML = DENY.
USE ROLE TRUSTED_AI_DATA_STEWARD; USE SECONDARY ROLES NONE;
SELECT COUNT(*) FROM TRUSTED_AI_GOVERNANCE.GOLD.PAYMENT_EXCEPTION_DAILY_METRICS;
SELECT COUNT(*) FROM TRUSTED_AI_GOVERNANCE.GOVERNANCE.GOLD_METRIC_CATALOG;
DELETE FROM TRUSTED_AI_GOVERNANCE.GOLD.PAYMENT_EXCEPTION_INVESTIGATION WHERE 1=0;

-- BRONZE_READER: Gold business-data SELECT = DENY.
USE ROLE TRUSTED_AI_BRONZE_READER; USE SECONDARY ROLES NONE;
SELECT COUNT(*) FROM TRUSTED_AI_GOVERNANCE.GOLD.PAYMENT_EXCEPTION_INVESTIGATION;

-- TAG_ADMIN: tag administration remains ALLOW; Gold business-data SELECT = DENY.
USE ROLE TRUSTED_AI_TAG_ADMIN; USE SECONDARY ROLES NONE;
SHOW TAGS IN SCHEMA TRUSTED_AI_GOVERNANCE.GOVERNANCE;
SELECT COUNT(*) FROM TRUSTED_AI_GOVERNANCE.GOLD.PAYMENT_EXCEPTION_INVESTIGATION;

-- AUDITOR: minimized run/product evidence and definitions = ALLOW; Gold payload and audit mutation = DENY.
USE ROLE TRUSTED_AI_AUDITOR; USE SECONDARY ROLES NONE;
SELECT COUNT(*) FROM TRUSTED_AI_GOVERNANCE.AUDIT.GOLD_TRANSFORMATION_RUN;
SELECT COUNT(*) FROM TRUSTED_AI_GOVERNANCE.AUDIT.GOLD_PRODUCT_EVIDENCE;
SELECT COUNT(*) FROM TRUSTED_AI_GOVERNANCE.GOVERNANCE.GOLD_PRODUCT_CATALOG;
SELECT COUNT(*) FROM TRUSTED_AI_GOVERNANCE.GOLD.PAYMENT_EXCEPTION_INVESTIGATION;
UPDATE TRUSTED_AI_GOVERNANCE.AUDIT.GOLD_TRANSFORMATION_RUN SET STATUS=STATUS WHERE 1=0;
