-- G2.3 — concise project-managed governance tag taxonomy
-- Prerequisite: roles, database, and GOVERNANCE schema exist.

USE ROLE SYSADMIN;
USE DATABASE TRUSTED_AI_GOVERNANCE;
USE SCHEMA GOVERNANCE;

CREATE TAG IF NOT EXISTS GOVERNANCE.DATA_CLASSIFICATION
  ALLOWED_VALUES 'DIRECT_PERSONAL_IDENTIFIER', 'FINANCIALLY_SENSITIVE',
                 'OPERATIONAL_SENSITIVE', 'INTERNAL_REFERENCE',
                 'GOVERNED_BUSINESS_INFORMATION'
  COMMENT = 'Approved synthetic banking data classification intent';

CREATE TAG IF NOT EXISTS GOVERNANCE.SENSITIVITY_LEVEL
  ALLOWED_VALUES 'HIGH', 'MODERATE', 'LOW'
  COMMENT = 'Approved sensitivity level';

CREATE TAG IF NOT EXISTS GOVERNANCE.DATA_DOMAIN
  ALLOWED_VALUES 'CUSTOMER', 'ACCOUNT', 'PAYMENT', 'PAYMENT_EXCEPTION',
                 'OPERATIONS', 'REFERENCE', 'GOVERNANCE'
  COMMENT = 'Approved business data domain';

CREATE TAG IF NOT EXISTS GOVERNANCE.SYNTHETIC_DATA
  ALLOWED_VALUES 'TRUE'
  COMMENT = 'Confirms the tagged object contains synthetic demonstration data';

CREATE TAG IF NOT EXISTS GOVERNANCE.DATA_LAYER
  ALLOWED_VALUES 'BRONZE'
  COMMENT = 'Governed medallion layer for this implementation action';

CREATE TAG IF NOT EXISTS GOVERNANCE.OWNER_DOMAIN
  ALLOWED_VALUES 'BANKING_OPERATIONS', 'DATA_GOVERNANCE'
  COMMENT = 'Accountable owning domain';

CREATE TAG IF NOT EXISTS GOVERNANCE.PERMITTED_PURPOSE
  ALLOWED_VALUES 'TRUSTED_BANKING_OPERATIONS_AI'
  COMMENT = 'Approved lighthouse business purpose';

-- Transfer tag ownership without granting data access. SYSADMIN inherits this
-- child role for deployment-time assignment, while TAG_ADMIN remains separable.
GRANT OWNERSHIP ON TAG GOVERNANCE.DATA_CLASSIFICATION TO ROLE TRUSTED_AI_TAG_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON TAG GOVERNANCE.SENSITIVITY_LEVEL TO ROLE TRUSTED_AI_TAG_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON TAG GOVERNANCE.DATA_DOMAIN TO ROLE TRUSTED_AI_TAG_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON TAG GOVERNANCE.SYNTHETIC_DATA TO ROLE TRUSTED_AI_TAG_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON TAG GOVERNANCE.DATA_LAYER TO ROLE TRUSTED_AI_TAG_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON TAG GOVERNANCE.OWNER_DOMAIN TO ROLE TRUSTED_AI_TAG_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON TAG GOVERNANCE.PERMITTED_PURPOSE TO ROLE TRUSTED_AI_TAG_ADMIN COPY CURRENT GRANTS;
