-- G2.3 — table and representative sensitive-column tag assignments
-- Execute as the deployment role that owns Bronze tables and inherits TAG_ADMIN.

USE ROLE SYSADMIN;
USE DATABASE TRUSTED_AI_GOVERNANCE;

ALTER TABLE BRONZE.CUSTOMER_RAW SET TAG
  GOVERNANCE.DATA_LAYER='BRONZE', GOVERNANCE.SYNTHETIC_DATA='TRUE',
  GOVERNANCE.DATA_DOMAIN='CUSTOMER', GOVERNANCE.OWNER_DOMAIN='BANKING_OPERATIONS',
  GOVERNANCE.PERMITTED_PURPOSE='TRUSTED_BANKING_OPERATIONS_AI';
ALTER TABLE BRONZE.ACCOUNT_RAW SET TAG
  GOVERNANCE.DATA_LAYER='BRONZE', GOVERNANCE.SYNTHETIC_DATA='TRUE',
  GOVERNANCE.DATA_DOMAIN='ACCOUNT', GOVERNANCE.OWNER_DOMAIN='BANKING_OPERATIONS',
  GOVERNANCE.PERMITTED_PURPOSE='TRUSTED_BANKING_OPERATIONS_AI';
ALTER TABLE BRONZE.PAYMENT_RAW SET TAG
  GOVERNANCE.DATA_LAYER='BRONZE', GOVERNANCE.SYNTHETIC_DATA='TRUE',
  GOVERNANCE.DATA_DOMAIN='PAYMENT', GOVERNANCE.OWNER_DOMAIN='BANKING_OPERATIONS',
  GOVERNANCE.PERMITTED_PURPOSE='TRUSTED_BANKING_OPERATIONS_AI';
ALTER TABLE BRONZE.PAYMENT_EXCEPTION_RAW SET TAG
  GOVERNANCE.DATA_LAYER='BRONZE', GOVERNANCE.SYNTHETIC_DATA='TRUE',
  GOVERNANCE.DATA_DOMAIN='PAYMENT_EXCEPTION', GOVERNANCE.OWNER_DOMAIN='BANKING_OPERATIONS',
  GOVERNANCE.PERMITTED_PURPOSE='TRUSTED_BANKING_OPERATIONS_AI';
ALTER TABLE BRONZE.SLA_EVENT_RAW SET TAG
  GOVERNANCE.DATA_LAYER='BRONZE', GOVERNANCE.SYNTHETIC_DATA='TRUE',
  GOVERNANCE.DATA_DOMAIN='OPERATIONS', GOVERNANCE.OWNER_DOMAIN='BANKING_OPERATIONS',
  GOVERNANCE.PERMITTED_PURPOSE='TRUSTED_BANKING_OPERATIONS_AI';
ALTER TABLE BRONZE.OPERATIONS_TEAM_RAW SET TAG
  GOVERNANCE.DATA_LAYER='BRONZE', GOVERNANCE.SYNTHETIC_DATA='TRUE',
  GOVERNANCE.DATA_DOMAIN='OPERATIONS', GOVERNANCE.OWNER_DOMAIN='BANKING_OPERATIONS',
  GOVERNANCE.PERMITTED_PURPOSE='TRUSTED_BANKING_OPERATIONS_AI';
ALTER TABLE BRONZE.OPERATIONS_USER_RAW SET TAG
  GOVERNANCE.DATA_LAYER='BRONZE', GOVERNANCE.SYNTHETIC_DATA='TRUE',
  GOVERNANCE.DATA_DOMAIN='OPERATIONS', GOVERNANCE.OWNER_DOMAIN='BANKING_OPERATIONS',
  GOVERNANCE.PERMITTED_PURPOSE='TRUSTED_BANKING_OPERATIONS_AI';
ALTER TABLE BRONZE.REFERENCE_EXCEPTION_REASON_RAW SET TAG
  GOVERNANCE.DATA_LAYER='BRONZE', GOVERNANCE.SYNTHETIC_DATA='TRUE',
  GOVERNANCE.DATA_DOMAIN='REFERENCE', GOVERNANCE.OWNER_DOMAIN='DATA_GOVERNANCE',
  GOVERNANCE.PERMITTED_PURPOSE='TRUSTED_BANKING_OPERATIONS_AI';
ALTER TABLE BRONZE.REFERENCE_PAYMENT_THRESHOLD_RAW SET TAG
  GOVERNANCE.DATA_LAYER='BRONZE', GOVERNANCE.SYNTHETIC_DATA='TRUE',
  GOVERNANCE.DATA_DOMAIN='REFERENCE', GOVERNANCE.OWNER_DOMAIN='DATA_GOVERNANCE',
  GOVERNANCE.PERMITTED_PURPOSE='TRUSTED_BANKING_OPERATIONS_AI';
ALTER TABLE BRONZE.GOVERNANCE_REFERENCE_RAW SET TAG
  GOVERNANCE.DATA_LAYER='BRONZE', GOVERNANCE.SYNTHETIC_DATA='TRUE',
  GOVERNANCE.DATA_DOMAIN='GOVERNANCE', GOVERNANCE.OWNER_DOMAIN='DATA_GOVERNANCE',
  GOVERNANCE.PERMITTED_PURPOSE='TRUSTED_BANKING_OPERATIONS_AI';

ALTER TABLE BRONZE.CUSTOMER_RAW MODIFY COLUMN CUSTOMER_NAME SET TAG GOVERNANCE.DATA_CLASSIFICATION='DIRECT_PERSONAL_IDENTIFIER', GOVERNANCE.SENSITIVITY_LEVEL='HIGH';
ALTER TABLE BRONZE.CUSTOMER_RAW MODIFY COLUMN DATE_OF_BIRTH SET TAG GOVERNANCE.DATA_CLASSIFICATION='DIRECT_PERSONAL_IDENTIFIER', GOVERNANCE.SENSITIVITY_LEVEL='HIGH';
ALTER TABLE BRONZE.CUSTOMER_RAW MODIFY COLUMN EMAIL SET TAG GOVERNANCE.DATA_CLASSIFICATION='DIRECT_PERSONAL_IDENTIFIER', GOVERNANCE.SENSITIVITY_LEVEL='HIGH';
ALTER TABLE BRONZE.CUSTOMER_RAW MODIFY COLUMN PHONE SET TAG GOVERNANCE.DATA_CLASSIFICATION='DIRECT_PERSONAL_IDENTIFIER', GOVERNANCE.SENSITIVITY_LEVEL='HIGH';
ALTER TABLE BRONZE.CUSTOMER_RAW MODIFY COLUMN ADDRESS_LINE SET TAG GOVERNANCE.DATA_CLASSIFICATION='DIRECT_PERSONAL_IDENTIFIER', GOVERNANCE.SENSITIVITY_LEVEL='HIGH';
ALTER TABLE BRONZE.CUSTOMER_RAW MODIFY COLUMN POSTAL_CODE SET TAG GOVERNANCE.DATA_CLASSIFICATION='DIRECT_PERSONAL_IDENTIFIER', GOVERNANCE.SENSITIVITY_LEVEL='MODERATE';

ALTER TABLE BRONZE.ACCOUNT_RAW MODIFY COLUMN ACCOUNT_ID SET TAG GOVERNANCE.DATA_CLASSIFICATION='FINANCIALLY_SENSITIVE', GOVERNANCE.SENSITIVITY_LEVEL='HIGH';
ALTER TABLE BRONZE.ACCOUNT_RAW MODIFY COLUMN AVAILABLE_BALANCE SET TAG GOVERNANCE.DATA_CLASSIFICATION='FINANCIALLY_SENSITIVE', GOVERNANCE.SENSITIVITY_LEVEL='HIGH';

ALTER TABLE BRONZE.PAYMENT_RAW MODIFY COLUMN ACCOUNT_ID SET TAG GOVERNANCE.DATA_CLASSIFICATION='FINANCIALLY_SENSITIVE', GOVERNANCE.SENSITIVITY_LEVEL='HIGH';
ALTER TABLE BRONZE.PAYMENT_RAW MODIFY COLUMN CUSTOMER_ID SET TAG GOVERNANCE.DATA_CLASSIFICATION='DIRECT_PERSONAL_IDENTIFIER', GOVERNANCE.SENSITIVITY_LEVEL='HIGH';
ALTER TABLE BRONZE.PAYMENT_RAW MODIFY COLUMN PAYMENT_AMOUNT SET TAG GOVERNANCE.DATA_CLASSIFICATION='FINANCIALLY_SENSITIVE', GOVERNANCE.SENSITIVITY_LEVEL='HIGH';
ALTER TABLE BRONZE.PAYMENT_RAW MODIFY COLUMN BENEFICIARY_COUNTRY SET TAG GOVERNANCE.DATA_CLASSIFICATION='FINANCIALLY_SENSITIVE', GOVERNANCE.SENSITIVITY_LEVEL='MODERATE';
ALTER TABLE BRONZE.PAYMENT_RAW MODIFY COLUMN BENEFICIARY_TYPE SET TAG GOVERNANCE.DATA_CLASSIFICATION='FINANCIALLY_SENSITIVE', GOVERNANCE.SENSITIVITY_LEVEL='MODERATE';

ALTER TABLE BRONZE.PAYMENT_EXCEPTION_RAW MODIFY COLUMN CUSTOMER_ID SET TAG GOVERNANCE.DATA_CLASSIFICATION='DIRECT_PERSONAL_IDENTIFIER', GOVERNANCE.SENSITIVITY_LEVEL='HIGH';
ALTER TABLE BRONZE.PAYMENT_EXCEPTION_RAW MODIFY COLUMN ACCOUNT_ID SET TAG GOVERNANCE.DATA_CLASSIFICATION='FINANCIALLY_SENSITIVE', GOVERNANCE.SENSITIVITY_LEVEL='HIGH';
ALTER TABLE BRONZE.PAYMENT_EXCEPTION_RAW MODIFY COLUMN EXCEPTION_REASON_DESCRIPTION SET TAG GOVERNANCE.DATA_CLASSIFICATION='OPERATIONAL_SENSITIVE', GOVERNANCE.SENSITIVITY_LEVEL='MODERATE';
ALTER TABLE BRONZE.PAYMENT_EXCEPTION_RAW MODIFY COLUMN ASSIGNED_ANALYST_ID SET TAG GOVERNANCE.DATA_CLASSIFICATION='OPERATIONAL_SENSITIVE', GOVERNANCE.SENSITIVITY_LEVEL='MODERATE';

ALTER TABLE BRONZE.OPERATIONS_USER_RAW MODIFY COLUMN OPERATIONS_USER_ID SET TAG GOVERNANCE.DATA_CLASSIFICATION='OPERATIONAL_SENSITIVE', GOVERNANCE.SENSITIVITY_LEVEL='MODERATE';
ALTER TABLE BRONZE.OPERATIONS_USER_RAW MODIFY COLUMN DISPLAY_NAME SET TAG GOVERNANCE.DATA_CLASSIFICATION='OPERATIONAL_SENSITIVE', GOVERNANCE.SENSITIVITY_LEVEL='MODERATE';
