-- G2.3 — least-privilege Bronze access controls
-- Execute as a deployment administrator capable of granting object/account privileges.

USE ROLE ACCOUNTADMIN;

GRANT USAGE ON DATABASE TRUSTED_AI_GOVERNANCE TO ROLE TRUSTED_AI_DATA_ENGINEER;
GRANT USAGE ON DATABASE TRUSTED_AI_GOVERNANCE TO ROLE TRUSTED_AI_DATA_STEWARD;
GRANT USAGE ON DATABASE TRUSTED_AI_GOVERNANCE TO ROLE TRUSTED_AI_BRONZE_READER;
GRANT USAGE ON DATABASE TRUSTED_AI_GOVERNANCE TO ROLE TRUSTED_AI_AUDITOR;
GRANT USAGE ON DATABASE TRUSTED_AI_GOVERNANCE TO ROLE TRUSTED_AI_TAG_ADMIN;

GRANT USAGE ON SCHEMA TRUSTED_AI_GOVERNANCE.PLATFORM TO ROLE TRUSTED_AI_DATA_ENGINEER;
GRANT USAGE ON SCHEMA TRUSTED_AI_GOVERNANCE.BRONZE TO ROLE TRUSTED_AI_DATA_ENGINEER;
GRANT USAGE ON SCHEMA TRUSTED_AI_GOVERNANCE.GOVERNANCE TO ROLE TRUSTED_AI_DATA_ENGINEER;
GRANT USAGE ON SCHEMA TRUSTED_AI_GOVERNANCE.AUDIT TO ROLE TRUSTED_AI_DATA_ENGINEER;
GRANT READ, WRITE ON STAGE TRUSTED_AI_GOVERNANCE.PLATFORM.SOURCE_STAGE TO ROLE TRUSTED_AI_DATA_ENGINEER;
GRANT USAGE ON FILE FORMAT TRUSTED_AI_GOVERNANCE.PLATFORM.SYNTHETIC_SOURCE_CSV_FORMAT TO ROLE TRUSTED_AI_DATA_ENGINEER;
GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA TRUSTED_AI_GOVERNANCE.BRONZE TO ROLE TRUSTED_AI_DATA_ENGINEER;
GRANT SELECT ON TABLE TRUSTED_AI_GOVERNANCE.GOVERNANCE.INGESTION_SOURCE_REGISTRY TO ROLE TRUSTED_AI_DATA_ENGINEER;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA TRUSTED_AI_GOVERNANCE.AUDIT TO ROLE TRUSTED_AI_DATA_ENGINEER;

GRANT USAGE ON SCHEMA TRUSTED_AI_GOVERNANCE.BRONZE TO ROLE TRUSTED_AI_BRONZE_READER;
GRANT SELECT ON ALL TABLES IN SCHEMA TRUSTED_AI_GOVERNANCE.BRONZE TO ROLE TRUSTED_AI_BRONZE_READER;

GRANT USAGE ON SCHEMA TRUSTED_AI_GOVERNANCE.BRONZE TO ROLE TRUSTED_AI_DATA_STEWARD;
GRANT USAGE ON SCHEMA TRUSTED_AI_GOVERNANCE.GOVERNANCE TO ROLE TRUSTED_AI_DATA_STEWARD;
GRANT USAGE ON SCHEMA TRUSTED_AI_GOVERNANCE.AUDIT TO ROLE TRUSTED_AI_DATA_STEWARD;
GRANT SELECT ON TABLE TRUSTED_AI_GOVERNANCE.GOVERNANCE.INGESTION_SOURCE_REGISTRY TO ROLE TRUSTED_AI_DATA_STEWARD;
GRANT SELECT ON ALL TABLES IN SCHEMA TRUSTED_AI_GOVERNANCE.AUDIT TO ROLE TRUSTED_AI_DATA_STEWARD;

GRANT USAGE ON SCHEMA TRUSTED_AI_GOVERNANCE.GOVERNANCE TO ROLE TRUSTED_AI_AUDITOR;
GRANT USAGE ON SCHEMA TRUSTED_AI_GOVERNANCE.AUDIT TO ROLE TRUSTED_AI_AUDITOR;
GRANT SELECT ON TABLE TRUSTED_AI_GOVERNANCE.GOVERNANCE.INGESTION_SOURCE_REGISTRY TO ROLE TRUSTED_AI_AUDITOR;
GRANT SELECT ON ALL TABLES IN SCHEMA TRUSTED_AI_GOVERNANCE.AUDIT TO ROLE TRUSTED_AI_AUDITOR;

GRANT USAGE ON SCHEMA TRUSTED_AI_GOVERNANCE.GOVERNANCE TO ROLE TRUSTED_AI_TAG_ADMIN;
GRANT CREATE TAG ON SCHEMA TRUSTED_AI_GOVERNANCE.GOVERNANCE TO ROLE TRUSTED_AI_TAG_ADMIN;
GRANT APPLY TAG ON ACCOUNT TO ROLE TRUSTED_AI_TAG_ADMIN;

-- OPTIONAL NATIVE CLASSIFICATION — ENTERPRISE EDITION OR HIGHER
-- Execute the following grants separately only after the capability gate in the
-- runbook verifies that SNOWFLAKE.DATA_PRIVACY.CLASSIFICATION_PROFILE is
-- available. They are deliberately excluded from mandatory Bronze RBAC so an
-- unsupported optional feature cannot block project-governed classification.
-- GRANT DATABASE ROLE SNOWFLAKE.CLASSIFICATION_ADMIN TO ROLE TRUSTED_AI_TAG_ADMIN;
-- GRANT CREATE SNOWFLAKE.DATA_PRIVACY.CLASSIFICATION_PROFILE ON SCHEMA TRUSTED_AI_GOVERNANCE.GOVERNANCE TO ROLE TRUSTED_AI_TAG_ADMIN;
-- GRANT EXECUTE AUTO CLASSIFICATION ON SCHEMA TRUSTED_AI_GOVERNANCE.BRONZE TO ROLE TRUSTED_AI_TAG_ADMIN;

GRANT DATABASE ROLE SNOWFLAKE.GOVERNANCE_VIEWER TO ROLE TRUSTED_AI_DATA_STEWARD;
GRANT DATABASE ROLE SNOWFLAKE.GOVERNANCE_VIEWER TO ROLE TRUSTED_AI_AUDITOR;

-- TAG_ADMIN gets no SELECT on Bronze. AUDITOR gets no DML. DATA_STEWARD gets
-- no Bronze DML. No project role receives ACCOUNTADMIN or SECURITYADMIN.
-- Grant USAGE on the deployment-approved non-production warehouse to
-- TRUSTED_AI_DATA_ENGINEER outside this portable script; no warehouse is invented here.
