-- G2.4 Silver governance inheritance and least privilege. Execute after Silver transformation.
USE ROLE TRUSTED_AI_TAG_ADMIN;
USE DATABASE TRUSTED_AI_GOVERNANCE;
ALTER TAG GOVERNANCE.DATA_LAYER ADD ALLOWED_VALUES 'SILVER';
-- Explicit table tags for every trusted entity (project-managed tags remain authoritative).
ALTER TABLE SILVER.CUSTOMER SET TAG GOVERNANCE.DATA_LAYER='SILVER',GOVERNANCE.SYNTHETIC_DATA='TRUE',GOVERNANCE.DATA_DOMAIN='CUSTOMER',GOVERNANCE.OWNER_DOMAIN='DATA_GOVERNANCE',GOVERNANCE.PERMITTED_PURPOSE='TRUSTED_BANKING_OPERATIONS_AI';
ALTER TABLE SILVER.ACCOUNT SET TAG GOVERNANCE.DATA_LAYER='SILVER',GOVERNANCE.SYNTHETIC_DATA='TRUE',GOVERNANCE.DATA_DOMAIN='ACCOUNT',GOVERNANCE.OWNER_DOMAIN='DATA_GOVERNANCE',GOVERNANCE.PERMITTED_PURPOSE='TRUSTED_BANKING_OPERATIONS_AI';
ALTER TABLE SILVER.PAYMENT SET TAG GOVERNANCE.DATA_LAYER='SILVER',GOVERNANCE.SYNTHETIC_DATA='TRUE',GOVERNANCE.DATA_DOMAIN='PAYMENT',GOVERNANCE.OWNER_DOMAIN='DATA_GOVERNANCE',GOVERNANCE.PERMITTED_PURPOSE='TRUSTED_BANKING_OPERATIONS_AI';
ALTER TABLE SILVER.PAYMENT_EXCEPTION SET TAG GOVERNANCE.DATA_LAYER='SILVER',GOVERNANCE.SYNTHETIC_DATA='TRUE',GOVERNANCE.DATA_DOMAIN='PAYMENT_EXCEPTION',GOVERNANCE.OWNER_DOMAIN='DATA_GOVERNANCE',GOVERNANCE.PERMITTED_PURPOSE='TRUSTED_BANKING_OPERATIONS_AI';
ALTER TABLE SILVER.SLA_EVENT SET TAG GOVERNANCE.DATA_LAYER='SILVER',GOVERNANCE.SYNTHETIC_DATA='TRUE',GOVERNANCE.DATA_DOMAIN='OPERATIONS',GOVERNANCE.OWNER_DOMAIN='DATA_GOVERNANCE',GOVERNANCE.PERMITTED_PURPOSE='TRUSTED_BANKING_OPERATIONS_AI';
ALTER TABLE SILVER.OPERATIONS_TEAM SET TAG GOVERNANCE.DATA_LAYER='SILVER',GOVERNANCE.SYNTHETIC_DATA='TRUE',GOVERNANCE.DATA_DOMAIN='OPERATIONS',GOVERNANCE.OWNER_DOMAIN='DATA_GOVERNANCE',GOVERNANCE.PERMITTED_PURPOSE='TRUSTED_BANKING_OPERATIONS_AI';
ALTER TABLE SILVER.OPERATIONS_USER SET TAG GOVERNANCE.DATA_LAYER='SILVER',GOVERNANCE.SYNTHETIC_DATA='TRUE',GOVERNANCE.DATA_DOMAIN='OPERATIONS',GOVERNANCE.OWNER_DOMAIN='DATA_GOVERNANCE',GOVERNANCE.PERMITTED_PURPOSE='TRUSTED_BANKING_OPERATIONS_AI';
ALTER TABLE SILVER.REFERENCE_EXCEPTION_REASON SET TAG GOVERNANCE.DATA_LAYER='SILVER',GOVERNANCE.SYNTHETIC_DATA='TRUE',GOVERNANCE.DATA_DOMAIN='REFERENCE',GOVERNANCE.OWNER_DOMAIN='DATA_GOVERNANCE',GOVERNANCE.PERMITTED_PURPOSE='TRUSTED_BANKING_OPERATIONS_AI';
ALTER TABLE SILVER.REFERENCE_PAYMENT_THRESHOLD SET TAG GOVERNANCE.DATA_LAYER='SILVER',GOVERNANCE.SYNTHETIC_DATA='TRUE',GOVERNANCE.DATA_DOMAIN='REFERENCE',GOVERNANCE.OWNER_DOMAIN='DATA_GOVERNANCE',GOVERNANCE.PERMITTED_PURPOSE='TRUSTED_BANKING_OPERATIONS_AI';
ALTER TABLE SILVER.GOVERNANCE_REFERENCE SET TAG GOVERNANCE.DATA_LAYER='SILVER',GOVERNANCE.SYNTHETIC_DATA='TRUE',GOVERNANCE.DATA_DOMAIN='GOVERNANCE',GOVERNANCE.OWNER_DOMAIN='DATA_GOVERNANCE',GOVERNANCE.PERMITTED_PURPOSE='TRUSTED_BANKING_OPERATIONS_AI';
ALTER TABLE SILVER.CUSTOMER MODIFY COLUMN CUSTOMER_NAME SET TAG GOVERNANCE.DATA_CLASSIFICATION='DIRECT_PERSONAL_IDENTIFIER',GOVERNANCE.SENSITIVITY_LEVEL='HIGH';
ALTER TABLE SILVER.ACCOUNT MODIFY COLUMN ACCOUNT_ID SET TAG GOVERNANCE.DATA_CLASSIFICATION='FINANCIALLY_SENSITIVE',GOVERNANCE.SENSITIVITY_LEVEL='HIGH';
ALTER TABLE SILVER.PAYMENT MODIFY COLUMN PAYMENT_AMOUNT SET TAG GOVERNANCE.DATA_CLASSIFICATION='FINANCIALLY_SENSITIVE',GOVERNANCE.SENSITIVITY_LEVEL='HIGH';
ALTER TABLE SILVER.PAYMENT_EXCEPTION MODIFY COLUMN ASSIGNED_ANALYST_ID SET TAG GOVERNANCE.DATA_CLASSIFICATION='OPERATIONAL_SENSITIVE',GOVERNANCE.SENSITIVITY_LEVEL='MODERATE';
USE ROLE SECURITYADMIN;
GRANT USAGE ON SCHEMA TRUSTED_AI_GOVERNANCE.SILVER TO ROLE TRUSTED_AI_DATA_ENGINEER;
GRANT USAGE ON SCHEMA TRUSTED_AI_GOVERNANCE.SILVER_QUARANTINE TO ROLE TRUSTED_AI_DATA_ENGINEER;
GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE ON ALL TABLES IN SCHEMA TRUSTED_AI_GOVERNANCE.SILVER TO ROLE TRUSTED_AI_DATA_ENGINEER;
GRANT SELECT,INSERT,UPDATE ON ALL TABLES IN SCHEMA TRUSTED_AI_GOVERNANCE.SILVER_QUARANTINE TO ROLE TRUSTED_AI_DATA_ENGINEER;
GRANT USAGE ON SCHEMA TRUSTED_AI_GOVERNANCE.SILVER TO ROLE TRUSTED_AI_DATA_STEWARD;
GRANT USAGE ON SCHEMA TRUSTED_AI_GOVERNANCE.SILVER_QUARANTINE TO ROLE TRUSTED_AI_DATA_STEWARD;
GRANT SELECT ON ALL TABLES IN SCHEMA TRUSTED_AI_GOVERNANCE.SILVER TO ROLE TRUSTED_AI_DATA_STEWARD;
GRANT SELECT ON ALL TABLES IN SCHEMA TRUSTED_AI_GOVERNANCE.SILVER_QUARANTINE TO ROLE TRUSTED_AI_DATA_STEWARD;
GRANT SELECT ON TABLE TRUSTED_AI_GOVERNANCE.GOVERNANCE.DQ_RULE_CATALOG TO ROLE TRUSTED_AI_DATA_STEWARD;
GRANT USAGE ON SCHEMA TRUSTED_AI_GOVERNANCE.SILVER_QUARANTINE TO ROLE TRUSTED_AI_AUDITOR;
GRANT SELECT ON ALL TABLES IN SCHEMA TRUSTED_AI_GOVERNANCE.SILVER_QUARANTINE TO ROLE TRUSTED_AI_AUDITOR;
GRANT SELECT ON TABLE TRUSTED_AI_GOVERNANCE.AUDIT.TRANSFORMATION_RUN TO ROLE TRUSTED_AI_AUDITOR;
GRANT SELECT ON TABLE TRUSTED_AI_GOVERNANCE.AUDIT.TRANSFORMATION_ENTITY_EVIDENCE TO ROLE TRUSTED_AI_AUDITOR;
-- BRONZE_READER gets no Silver grant. TAG_ADMIN gets no business-data SELECT.
