-- Additive asynchronous monitoring; deterministic project rules remain admission authority.
USE ROLE TRUSTED_AI_DATA_ENGINEER;
USE DATABASE TRUSTED_AI_GOVERNANCE;
ALTER TABLE SILVER.PAYMENT SET DATA_METRIC_SCHEDULE='TRIGGER_ON_CHANGES';
ALTER TABLE SILVER.PAYMENT ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (PAYMENT_ID);
ALTER TABLE SILVER.PAYMENT_EXCEPTION SET DATA_METRIC_SCHEDULE='TRIGGER_ON_CHANGES';
ALTER TABLE SILVER.PAYMENT_EXCEPTION ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (EXCEPTION_ID);
-- Configuration is CONFIGURED/PENDING until metric results are actually observed.
