-- G2.5 Gold governance inheritance. Reuses the approved seven-tag taxonomy.
USE ROLE TRUSTED_AI_TAG_ADMIN;
USE DATABASE TRUSTED_AI_GOVERNANCE;
ALTER TAG GOVERNANCE.DATA_LAYER ADD ALLOWED_VALUES 'GOLD';

ALTER TABLE GOLD.PAYMENT_EXCEPTION_INVESTIGATION SET TAG GOVERNANCE.DATA_LAYER='GOLD',GOVERNANCE.SYNTHETIC_DATA='TRUE',GOVERNANCE.DATA_DOMAIN='PAYMENT_EXCEPTION',GOVERNANCE.OWNER_DOMAIN='BANKING_OPERATIONS',GOVERNANCE.PERMITTED_PURPOSE='TRUSTED_BANKING_OPERATIONS_AI',GOVERNANCE.DATA_CLASSIFICATION='OPERATIONAL_SENSITIVE',GOVERNANCE.SENSITIVITY_LEVEL='HIGH';
ALTER TABLE GOLD.PAYMENT_EXCEPTION_DAILY_METRICS SET TAG GOVERNANCE.DATA_LAYER='GOLD',GOVERNANCE.SYNTHETIC_DATA='TRUE',GOVERNANCE.DATA_DOMAIN='PAYMENT_EXCEPTION',GOVERNANCE.OWNER_DOMAIN='BANKING_OPERATIONS',GOVERNANCE.PERMITTED_PURPOSE='TRUSTED_BANKING_OPERATIONS_AI',GOVERNANCE.DATA_CLASSIFICATION='GOVERNED_BUSINESS_INFORMATION',GOVERNANCE.SENSITIVITY_LEVEL='MODERATE';
ALTER TABLE GOLD.PAYMENT_EXCEPTION_PERIOD_COMPARISON SET TAG GOVERNANCE.DATA_LAYER='GOLD',GOVERNANCE.SYNTHETIC_DATA='TRUE',GOVERNANCE.DATA_DOMAIN='PAYMENT_EXCEPTION',GOVERNANCE.OWNER_DOMAIN='BANKING_OPERATIONS',GOVERNANCE.PERMITTED_PURPOSE='TRUSTED_BANKING_OPERATIONS_AI',GOVERNANCE.DATA_CLASSIFICATION='GOVERNED_BUSINESS_INFORMATION',GOVERNANCE.SENSITIVITY_LEVEL='MODERATE';
ALTER TABLE GOLD.SLA_OPERATIONAL_EXPOSURE SET TAG GOVERNANCE.DATA_LAYER='GOLD',GOVERNANCE.SYNTHETIC_DATA='TRUE',GOVERNANCE.DATA_DOMAIN='OPERATIONS',GOVERNANCE.OWNER_DOMAIN='BANKING_OPERATIONS',GOVERNANCE.PERMITTED_PURPOSE='TRUSTED_BANKING_OPERATIONS_AI',GOVERNANCE.DATA_CLASSIFICATION='OPERATIONAL_SENSITIVE',GOVERNANCE.SENSITIVITY_LEVEL='HIGH';
ALTER TABLE GOLD.OPERATIONS_WORKLOAD_SUMMARY SET TAG GOVERNANCE.DATA_LAYER='GOLD',GOVERNANCE.SYNTHETIC_DATA='TRUE',GOVERNANCE.DATA_DOMAIN='OPERATIONS',GOVERNANCE.OWNER_DOMAIN='BANKING_OPERATIONS',GOVERNANCE.PERMITTED_PURPOSE='TRUSTED_BANKING_OPERATIONS_AI',GOVERNANCE.DATA_CLASSIFICATION='GOVERNED_BUSINESS_INFORMATION',GOVERNANCE.SENSITIVITY_LEVEL='MODERATE';

ALTER TABLE GOLD.PAYMENT_EXCEPTION_INVESTIGATION MODIFY COLUMN MINIMIZED_ACCOUNT_REFERENCE SET TAG GOVERNANCE.DATA_CLASSIFICATION='FINANCIALLY_SENSITIVE',GOVERNANCE.SENSITIVITY_LEVEL='HIGH';
ALTER TABLE GOLD.PAYMENT_EXCEPTION_INVESTIGATION MODIFY COLUMN MINIMIZED_CUSTOMER_REFERENCE SET TAG GOVERNANCE.DATA_CLASSIFICATION='DIRECT_PERSONAL_IDENTIFIER',GOVERNANCE.SENSITIVITY_LEVEL='HIGH';
ALTER TABLE GOLD.PAYMENT_EXCEPTION_INVESTIGATION MODIFY COLUMN PAYMENT_AMOUNT SET TAG GOVERNANCE.DATA_CLASSIFICATION='FINANCIALLY_SENSITIVE',GOVERNANCE.SENSITIVITY_LEVEL='HIGH';
ALTER TABLE GOLD.PAYMENT_EXCEPTION_DAILY_METRICS MODIFY COLUMN TOTAL_EXCEPTION_PAYMENT_AMOUNT SET TAG GOVERNANCE.DATA_CLASSIFICATION='FINANCIALLY_SENSITIVE',GOVERNANCE.SENSITIVITY_LEVEL='MODERATE';
