-- G2.5 least-privilege Gold access. No application authority uses ACCOUNTADMIN.
USE ROLE SECURITYADMIN;

-- DATA_ENGINEER operates the approved transformation and evidence writes.
GRANT USAGE ON SCHEMA TRUSTED_AI_GOVERNANCE.GOLD TO ROLE TRUSTED_AI_DATA_ENGINEER;
GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE ON ALL TABLES IN SCHEMA TRUSTED_AI_GOVERNANCE.GOLD TO ROLE TRUSTED_AI_DATA_ENGINEER;
GRANT SELECT,INSERT,UPDATE ON TABLE TRUSTED_AI_GOVERNANCE.AUDIT.GOLD_TRANSFORMATION_RUN TO ROLE TRUSTED_AI_DATA_ENGINEER;
GRANT SELECT,INSERT ON TABLE TRUSTED_AI_GOVERNANCE.AUDIT.GOLD_PRODUCT_EVIDENCE TO ROLE TRUSTED_AI_DATA_ENGINEER;
GRANT SELECT,INSERT,UPDATE ON TABLE TRUSTED_AI_GOVERNANCE.GOVERNANCE.GOLD_PRODUCT_CATALOG TO ROLE TRUSTED_AI_DATA_ENGINEER;
GRANT SELECT,INSERT,UPDATE ON TABLE TRUSTED_AI_GOVERNANCE.GOVERNANCE.GOLD_METRIC_CATALOG TO ROLE TRUSTED_AI_DATA_ENGINEER;

-- DATA_STEWARD inspects certified products and definitions but cannot mutate them.
GRANT USAGE ON SCHEMA TRUSTED_AI_GOVERNANCE.GOLD TO ROLE TRUSTED_AI_DATA_STEWARD;
GRANT SELECT ON ALL TABLES IN SCHEMA TRUSTED_AI_GOVERNANCE.GOLD TO ROLE TRUSTED_AI_DATA_STEWARD;
GRANT SELECT ON TABLE TRUSTED_AI_GOVERNANCE.GOVERNANCE.GOLD_PRODUCT_CATALOG TO ROLE TRUSTED_AI_DATA_STEWARD;
GRANT SELECT ON TABLE TRUSTED_AI_GOVERNANCE.GOVERNANCE.GOLD_METRIC_CATALOG TO ROLE TRUSTED_AI_DATA_STEWARD;

-- AUDITOR receives minimized evidence/definition access, not Gold business payload.
GRANT SELECT ON TABLE TRUSTED_AI_GOVERNANCE.AUDIT.GOLD_TRANSFORMATION_RUN TO ROLE TRUSTED_AI_AUDITOR;
GRANT SELECT ON TABLE TRUSTED_AI_GOVERNANCE.AUDIT.GOLD_PRODUCT_EVIDENCE TO ROLE TRUSTED_AI_AUDITOR;
GRANT SELECT ON TABLE TRUSTED_AI_GOVERNANCE.GOVERNANCE.GOLD_PRODUCT_CATALOG TO ROLE TRUSTED_AI_AUDITOR;
GRANT SELECT ON TABLE TRUSTED_AI_GOVERNANCE.GOVERNANCE.GOLD_METRIC_CATALOG TO ROLE TRUSTED_AI_AUDITOR;

-- BRONZE_READER receives no Gold grant. TAG_ADMIN receives no Gold SELECT.
-- A dedicated operations-consumer role is deferred until its persona-to-role contract is approved.
