-- G2.3 — project-managed Bronze metadata and ingestion evidence foundation
-- Prerequisite: 001_environment_foundation.sql.

USE ROLE SYSADMIN;
USE DATABASE TRUSTED_AI_GOVERNANCE;

CREATE TABLE IF NOT EXISTS GOVERNANCE.INGESTION_SOURCE_REGISTRY (
  SOURCE_ID VARCHAR NOT NULL,
  SOURCE_NAME VARCHAR NOT NULL,
  SOURCE_TYPE VARCHAR NOT NULL,
  SOURCE_PATH VARCHAR NOT NULL,
  EXPECTED_ENTITY VARCHAR NOT NULL,
  CLASSIFICATION_SCOPE VARCHAR NOT NULL,
  SYNTHETIC_FLAG BOOLEAN NOT NULL,
  ACTIVE_FLAG BOOLEAN NOT NULL,
  EFFECTIVE_FROM DATE NOT NULL,
  EFFECTIVE_TO DATE,
  OWNER VARCHAR NOT NULL,
  CREATED_AT TIMESTAMP_LTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_INGESTION_SOURCE_REGISTRY PRIMARY KEY (SOURCE_ID)
)
COMMENT = 'Approved synthetic source identity and governance context for Bronze ingestion';

CREATE TABLE IF NOT EXISTS AUDIT.INGESTION_RUN (
  INGESTION_RUN_ID VARCHAR NOT NULL,
  SOURCE_ID VARCHAR NOT NULL,
  INGESTION_STARTED_AT TIMESTAMP_LTZ NOT NULL,
  INGESTION_COMPLETED_AT TIMESTAMP_LTZ,
  EXECUTION_ROLE VARCHAR NOT NULL,
  STATUS VARCHAR NOT NULL,
  FILES_SEEN NUMBER NOT NULL DEFAULT 0,
  FILES_LOADED NUMBER NOT NULL DEFAULT 0,
  RECORDS_LOADED NUMBER NOT NULL DEFAULT 0,
  RECORDS_REJECTED NUMBER NOT NULL DEFAULT 0,
  TRACE_ID VARCHAR NOT NULL,
  ERROR_MESSAGE VARCHAR,
  CONSTRAINT PK_INGESTION_RUN PRIMARY KEY (INGESTION_RUN_ID, SOURCE_ID)
)
COMMENT = 'One evidence row per source within a correlated Bronze ingestion execution';

CREATE TABLE IF NOT EXISTS AUDIT.INGESTION_FILE_EVIDENCE (
  INGESTION_RUN_ID VARCHAR NOT NULL,
  SOURCE_ID VARCHAR NOT NULL,
  SOURCE_FILE_NAME VARCHAR NOT NULL,
  SOURCE_FILE_CONTENT_KEY VARCHAR NOT NULL,
  SOURCE_FILE_LAST_MODIFIED TIMESTAMP_TZ,
  STAGE_SCAN_TIME TIMESTAMP_LTZ NOT NULL,
  RECORDS_LOADED NUMBER NOT NULL,
  LOAD_STATUS VARCHAR NOT NULL,
  EVIDENCE_CREATED_AT TIMESTAMP_LTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_INGESTION_FILE_EVIDENCE PRIMARY KEY (
    INGESTION_RUN_ID, SOURCE_ID, SOURCE_FILE_NAME, SOURCE_FILE_CONTENT_KEY
  )
)
COMMENT = 'File-level Bronze load evidence derived from Snowflake staged-file metadata';

-- Seed exactly the ten approved G2.2 structured business-source datasets.
MERGE INTO GOVERNANCE.INGESTION_SOURCE_REGISTRY AS TARGET
USING (
  SELECT COLUMN1 AS SOURCE_ID, COLUMN2 AS SOURCE_NAME, COLUMN3 AS SOURCE_PATH,
         COLUMN4 AS EXPECTED_ENTITY, COLUMN5 AS CLASSIFICATION_SCOPE
  FROM VALUES
    ('SRC_CUSTOMER', 'CUSTOMER', 'customer/', 'CUSTOMER', 'DIRECT_PERSONAL_IDENTIFIER'),
    ('SRC_ACCOUNT', 'ACCOUNT', 'account/', 'ACCOUNT', 'FINANCIALLY_SENSITIVE'),
    ('SRC_PAYMENT', 'PAYMENT', 'payment/', 'PAYMENT', 'FINANCIALLY_SENSITIVE'),
    ('SRC_PAYMENT_EXCEPTION', 'PAYMENT_EXCEPTION', 'payment_exception/', 'PAYMENT_EXCEPTION', 'OPERATIONAL_SENSITIVE'),
    ('SRC_SLA_EVENT', 'SLA_EVENT', 'sla_event/', 'SLA_EVENT', 'OPERATIONAL_SENSITIVE'),
    ('SRC_OPERATIONS_TEAM', 'OPERATIONS_TEAM', 'operations_team/', 'OPERATIONS_TEAM', 'OPERATIONAL_SENSITIVE'),
    ('SRC_OPERATIONS_USER', 'OPERATIONS_USER', 'operations_user/', 'OPERATIONS_USER', 'OPERATIONAL_SENSITIVE'),
    ('SRC_REFERENCE_EXCEPTION_REASON', 'REFERENCE_EXCEPTION_REASON', 'reference_exception_reason/', 'REFERENCE_EXCEPTION_REASON', 'INTERNAL_REFERENCE'),
    ('SRC_REFERENCE_PAYMENT_THRESHOLD', 'REFERENCE_PAYMENT_THRESHOLD', 'reference_payment_threshold/', 'REFERENCE_PAYMENT_THRESHOLD', 'INTERNAL_REFERENCE'),
    ('SRC_GOVERNANCE_REFERENCE', 'GOVERNANCE_REFERENCE', 'governance_reference/', 'GOVERNANCE_REFERENCE', 'INTERNAL_REFERENCE')
) AS SOURCE
ON TARGET.SOURCE_ID = SOURCE.SOURCE_ID
WHEN MATCHED THEN UPDATE SET
  SOURCE_NAME = SOURCE.SOURCE_NAME,
  SOURCE_TYPE = 'CSV',
  SOURCE_PATH = SOURCE.SOURCE_PATH,
  EXPECTED_ENTITY = SOURCE.EXPECTED_ENTITY,
  CLASSIFICATION_SCOPE = SOURCE.CLASSIFICATION_SCOPE,
  SYNTHETIC_FLAG = TRUE,
  ACTIVE_FLAG = TRUE,
  EFFECTIVE_FROM = '2026-03-15'::DATE,
  EFFECTIVE_TO = NULL,
  OWNER = 'DATA_GOVERNANCE'
WHEN NOT MATCHED THEN INSERT (
  SOURCE_ID, SOURCE_NAME, SOURCE_TYPE, SOURCE_PATH, EXPECTED_ENTITY,
  CLASSIFICATION_SCOPE, SYNTHETIC_FLAG, ACTIVE_FLAG, EFFECTIVE_FROM,
  EFFECTIVE_TO, OWNER
) VALUES (
  SOURCE.SOURCE_ID, SOURCE.SOURCE_NAME, 'CSV', SOURCE.SOURCE_PATH,
  SOURCE.EXPECTED_ENTITY, SOURCE.CLASSIFICATION_SCOPE, TRUE, TRUE,
  '2026-03-15'::DATE, NULL, 'DATA_GOVERNANCE'
);

-- governance_test_manifest.csv is intentionally not registered as a business entity.
