-- G2.5 governed Gold physical and evidence foundation. Implementation only.
USE ROLE SYSADMIN;
USE DATABASE TRUSTED_AI_GOVERNANCE;

CREATE SCHEMA IF NOT EXISTS GOLD
  COMMENT='Certified, purpose-oriented business products derived only from trusted Silver at TB-03';

CREATE TABLE IF NOT EXISTS AUDIT.GOLD_TRANSFORMATION_RUN (
  GOLD_TRANSFORMATION_RUN_ID VARCHAR NOT NULL,
  TRACE_ID VARCHAR NOT NULL,
  TRANSFORMATION_STARTED_AT TIMESTAMP_LTZ NOT NULL,
  TRANSFORMATION_COMPLETED_AT TIMESTAMP_LTZ,
  EXECUTION_ROLE VARCHAR NOT NULL,
  STATUS VARCHAR NOT NULL,
  QUERY_ID VARCHAR,
  ERROR_MESSAGE VARCHAR,
  CONSTRAINT PK_GOLD_TRANSFORMATION_RUN PRIMARY KEY (GOLD_TRANSFORMATION_RUN_ID),
  CONSTRAINT GOLD_TRANSFORMATION_RUN_STATUS CHECK (STATUS IN ('STARTED','COMPLETED','FAILED'))
)
COMMENT='Append-only execution evidence for governed Silver-to-Gold transformations';

CREATE TABLE IF NOT EXISTS AUDIT.GOLD_PRODUCT_EVIDENCE (
  GOLD_TRANSFORMATION_RUN_ID VARCHAR NOT NULL,
  TRACE_ID VARCHAR NOT NULL,
  PRODUCT_NAME VARCHAR NOT NULL,
  SOURCE_SILVER_TRANSFORMATION_RUN_IDS ARRAY NOT NULL,
  SOURCE_SILVER_TRACE_IDS ARRAY NOT NULL,
  SOURCE_SILVER_ROW_COUNT NUMBER NOT NULL,
  GOLD_OUTPUT_ROW_COUNT NUMBER NOT NULL,
  VALIDATION_FAILURE_COUNT NUMBER NOT NULL,
  EXECUTION_STATUS VARCHAR NOT NULL,
  EVIDENCED_AT TIMESTAMP_LTZ NOT NULL,
  QUERY_ID VARCHAR,
  CONSTRAINT GOLD_PRODUCT_EVIDENCE_STATUS CHECK (EXECUTION_STATUS IN ('COMPLETED','FAILED'))
)
COMMENT='Minimized product-level Gold lineage, counts, validation and correlation evidence';

USE ROLE SECURITYADMIN;
GRANT USAGE ON SCHEMA TRUSTED_AI_GOVERNANCE.GOLD TO ROLE TRUSTED_AI_DATA_ENGINEER;
GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE ON FUTURE TABLES IN SCHEMA TRUSTED_AI_GOVERNANCE.GOLD TO ROLE TRUSTED_AI_DATA_ENGINEER;
GRANT SELECT,INSERT,UPDATE ON TABLE TRUSTED_AI_GOVERNANCE.AUDIT.GOLD_TRANSFORMATION_RUN TO ROLE TRUSTED_AI_DATA_ENGINEER;
GRANT SELECT,INSERT ON TABLE TRUSTED_AI_GOVERNANCE.AUDIT.GOLD_PRODUCT_EVIDENCE TO ROLE TRUSTED_AI_DATA_ENGINEER;
