-- G2.5 five governed Gold business-product contracts. No raw entity replicas.
USE ROLE SYSADMIN;
USE DATABASE TRUSTED_AI_GOVERNANCE;
USE SCHEMA GOLD;

-- Grain: one trusted, eligible Silver payment exception.
CREATE TABLE IF NOT EXISTS PAYMENT_EXCEPTION_INVESTIGATION (
  EXCEPTION_ID VARCHAR NOT NULL, PAYMENT_ID VARCHAR NOT NULL,
  MINIMIZED_ACCOUNT_REFERENCE VARCHAR NOT NULL, MINIMIZED_CUSTOMER_REFERENCE VARCHAR NOT NULL,
  EXCEPTION_DATE DATE NOT NULL, EXCEPTION_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
  EXCEPTION_REASON_CODE VARCHAR NOT NULL, EXCEPTION_CATEGORY VARCHAR,
  EXCEPTION_SEVERITY VARCHAR, EXCEPTION_STATUS VARCHAR, RESOLUTION_STATUS VARCHAR,
  RESOLVED_TIMESTAMP TIMESTAMP_NTZ, PAYMENT_AMOUNT NUMBER(18,2), CURRENCY_CODE VARCHAR,
  PAYMENT_CHANNEL VARCHAR, HIGH_VALUE_FLAG BOOLEAN, SLA_EVENT_ID VARCHAR,
  SLA_DUE_TIMESTAMP TIMESTAMP_NTZ, SLA_BREACHED_FLAG BOOLEAN, SLA_BREACH_MINUTES NUMBER,
  ESCALATION_REQUIRED_FLAG BOOLEAN, OWNING_TEAM_ID VARCHAR, OWNING_TEAM_NAME VARCHAR,
  MINIMIZED_ASSIGNED_USER_REFERENCE VARCHAR, INVESTIGATION_PRIORITY VARCHAR NOT NULL,
  PRIORITY_REASON VARCHAR NOT NULL, PRIMARY_PERIOD_CLASSIFICATION VARCHAR NOT NULL,
  GOLD_TRANSFORMATION_RUN_ID VARCHAR NOT NULL, TRACE_ID VARCHAR NOT NULL,
  SOURCE_SILVER_TRANSFORMATION_RUN_ID VARCHAR NOT NULL,
  SOURCE_SILVER_TRACE_ID VARCHAR NOT NULL, GOLD_TRANSFORMED_AT TIMESTAMP_LTZ NOT NULL,
  SYNTHETIC_FLAG BOOLEAN NOT NULL, FITNESS_STATUS VARCHAR NOT NULL,
  CONSTRAINT PK_GOLD_PAYMENT_EXCEPTION_INVESTIGATION PRIMARY KEY (EXCEPTION_ID),
  CONSTRAINT GOLD_INVESTIGATION_PRIORITY CHECK (INVESTIGATION_PRIORITY IN ('CRITICAL','HIGH','MEDIUM','STANDARD'))
)
COMMENT='One minimized, authoritative exception context for governed banking-operations investigation';

-- Grain: one event date, payment channel, currency and high-value flag.
CREATE TABLE IF NOT EXISTS PAYMENT_EXCEPTION_DAILY_METRICS (
  EVENT_DATE DATE NOT NULL, PAYMENT_CHANNEL VARCHAR NOT NULL, CURRENCY_CODE VARCHAR NOT NULL,
  HIGH_VALUE_FLAG BOOLEAN NOT NULL, PAYMENT_COUNT NUMBER NOT NULL,
  EXCEPTION_COUNT NUMBER NOT NULL, HIGH_VALUE_PAYMENT_COUNT NUMBER NOT NULL,
  HIGH_VALUE_EXCEPTION_COUNT NUMBER NOT NULL, EXCEPTION_RATE NUMBER(18,8),
  UNRESOLVED_EXCEPTION_COUNT NUMBER NOT NULL, SLA_BREACH_COUNT NUMBER NOT NULL,
  ESCALATION_REQUIRED_COUNT NUMBER NOT NULL, TOTAL_EXCEPTION_PAYMENT_AMOUNT NUMBER(38,2),
  GOLD_TRANSFORMATION_RUN_ID VARCHAR NOT NULL, TRACE_ID VARCHAR NOT NULL,
  SOURCE_SILVER_TRANSFORMATION_RUN_IDS ARRAY NOT NULL, GOLD_TRANSFORMED_AT TIMESTAMP_LTZ NOT NULL,
  SYNTHETIC_FLAG BOOLEAN NOT NULL, FITNESS_STATUS VARCHAR NOT NULL,
  HIGH_VALUE_EXCEPTION_RATE NUMBER(18,8),
  CONSTRAINT PK_GOLD_DAILY_METRICS PRIMARY KEY (EVENT_DATE,PAYMENT_CHANNEL,CURRENCY_CODE,HIGH_VALUE_FLAG)
)
COMMENT='Daily governed payment/exception metrics; amounts remain currency-grained and rates are recomputed from counts';
ALTER TABLE PAYMENT_EXCEPTION_DAILY_METRICS ADD COLUMN IF NOT EXISTS HIGH_VALUE_EXCEPTION_RATE NUMBER(18,8);

-- Grain: one named comparison window and currency. Windows intentionally overlap and are not additive.
CREATE TABLE IF NOT EXISTS PAYMENT_EXCEPTION_PERIOD_COMPARISON (
  PERIOD_NAME VARCHAR NOT NULL, PERIOD_START_DATE DATE, PERIOD_END_DATE DATE NOT NULL,
  CURRENCY_CODE VARCHAR NOT NULL, PAYMENT_COUNT NUMBER NOT NULL, EXCEPTION_COUNT NUMBER NOT NULL,
  HIGH_VALUE_PAYMENT_COUNT NUMBER NOT NULL, HIGH_VALUE_EXCEPTION_COUNT NUMBER NOT NULL,
  EXCEPTION_RATE NUMBER(18,8), HIGH_VALUE_EXCEPTION_RATE NUMBER(18,8),
  SLA_BREACH_COUNT NUMBER NOT NULL, UNRESOLVED_EXCEPTION_COUNT NUMBER NOT NULL,
  GOLD_TRANSFORMATION_RUN_ID VARCHAR NOT NULL, TRACE_ID VARCHAR NOT NULL,
  SOURCE_SILVER_TRANSFORMATION_RUN_IDS ARRAY NOT NULL, GOLD_TRANSFORMED_AT TIMESTAMP_LTZ NOT NULL,
  SYNTHETIC_FLAG BOOLEAN NOT NULL, FITNESS_STATUS VARCHAR NOT NULL,
  CONSTRAINT PK_GOLD_PERIOD_COMPARISON PRIMARY KEY (PERIOD_NAME,CURRENCY_CODE),
  CONSTRAINT GOLD_PERIOD_NAME CHECK (PERIOD_NAME IN ('INVESTIGATION_WEEK','PREVIOUS_WEEK','TRAILING_FOUR_WEEK','HISTORICAL_BASELINE'))
)
COMMENT='Governed non-additive comparison windows derived from trusted Silver; percentages are never averaged';

-- Grain: one trusted exception with its deterministic representative SLA event, if present.
CREATE TABLE IF NOT EXISTS SLA_OPERATIONAL_EXPOSURE (
  EXCEPTION_ID VARCHAR NOT NULL, SLA_EVENT_ID VARCHAR, EXCEPTION_DATE DATE NOT NULL,
  SLA_DUE_TIMESTAMP TIMESTAMP_NTZ, SLA_STATE VARCHAR NOT NULL, SLA_BREACHED_FLAG BOOLEAN NOT NULL,
  SLA_BREACH_MINUTES NUMBER NOT NULL, ESCALATION_REQUIRED_FLAG BOOLEAN NOT NULL,
  UNRESOLVED_FLAG BOOLEAN NOT NULL, HIGH_VALUE_FLAG BOOLEAN NOT NULL,
  EXCEPTION_REASON_CODE VARCHAR NOT NULL, OWNING_TEAM_ID VARCHAR, OWNING_TEAM_NAME VARCHAR,
  INVESTIGATION_PRIORITY VARCHAR NOT NULL, AGE_DAYS NUMBER NOT NULL,
  GOLD_TRANSFORMATION_RUN_ID VARCHAR NOT NULL, TRACE_ID VARCHAR NOT NULL,
  SOURCE_SILVER_TRANSFORMATION_RUN_ID VARCHAR NOT NULL, SOURCE_SILVER_TRACE_ID VARCHAR NOT NULL,
  GOLD_TRANSFORMED_AT TIMESTAMP_LTZ NOT NULL, SYNTHETIC_FLAG BOOLEAN NOT NULL,
  FITNESS_STATUS VARCHAR NOT NULL, CONSTRAINT PK_GOLD_SLA_EXPOSURE PRIMARY KEY (EXCEPTION_ID)
)
COMMENT='One exception/SLA business case for governed operational exposure without user-sensitive payload';

-- Grain: one reporting date, team, exception reason, channel and currency.
CREATE TABLE IF NOT EXISTS OPERATIONS_WORKLOAD_SUMMARY (
  REPORTING_DATE DATE NOT NULL, OWNING_TEAM_ID VARCHAR NOT NULL, OWNING_TEAM_NAME VARCHAR,
  EXCEPTION_REASON_CODE VARCHAR NOT NULL, PAYMENT_CHANNEL VARCHAR NOT NULL, CURRENCY_CODE VARCHAR NOT NULL,
  OPEN_EXCEPTION_COUNT NUMBER NOT NULL, HIGH_VALUE_OPEN_COUNT NUMBER NOT NULL,
  SLA_BREACH_OPEN_COUNT NUMBER NOT NULL, ESCALATION_REQUIRED_OPEN_COUNT NUMBER NOT NULL,
  RESOLVED_EXCEPTION_COUNT NUMBER NOT NULL, AVERAGE_BREACH_MINUTES NUMBER(18,2),
  GOLD_TRANSFORMATION_RUN_ID VARCHAR NOT NULL, TRACE_ID VARCHAR NOT NULL,
  SOURCE_SILVER_TRANSFORMATION_RUN_IDS ARRAY NOT NULL, GOLD_TRANSFORMED_AT TIMESTAMP_LTZ NOT NULL,
  SYNTHETIC_FLAG BOOLEAN NOT NULL, FITNESS_STATUS VARCHAR NOT NULL,
  CONSTRAINT PK_GOLD_WORKLOAD PRIMARY KEY (REPORTING_DATE,OWNING_TEAM_ID,EXCEPTION_REASON_CODE,PAYMENT_CHANNEL,CURRENCY_CODE)
)
COMMENT='Governed team workload by stable business dimensions; no direct operations-user attributes';

USE ROLE SECURITYADMIN;
GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE ON ALL TABLES IN SCHEMA TRUSTED_AI_GOVERNANCE.GOLD TO ROLE TRUSTED_AI_DATA_ENGINEER;
