-- G2.5 project-managed Gold product and metric definitions; no Semantic View objects.
USE ROLE SYSADMIN;
USE DATABASE TRUSTED_AI_GOVERNANCE;

CREATE TABLE IF NOT EXISTS GOVERNANCE.GOLD_PRODUCT_CATALOG (
  PRODUCT_NAME VARCHAR NOT NULL, BUSINESS_PURPOSE VARCHAR NOT NULL, BUSINESS_GRAIN VARCHAR NOT NULL,
  BUSINESS_KEY VARCHAR NOT NULL, AUTHORITATIVE_SILVER_SOURCES VARCHAR NOT NULL,
  OWNER_DOMAIN VARCHAR NOT NULL, STEWARD_DOMAIN VARCHAR NOT NULL, PERMITTED_PURPOSE VARCHAR NOT NULL,
  CONSUMPTION_INTENT VARCHAR NOT NULL, POTENTIALLY_AI_ELIGIBLE BOOLEAN NOT NULL,
  AI_CONTEXT_ADMISSION_REQUIRED BOOLEAN NOT NULL, CLASSIFICATION VARCHAR NOT NULL,
  SENSITIVITY_LEVEL VARCHAR NOT NULL, FRESHNESS_EXPECTATION VARCHAR NOT NULL,
  FITNESS_CRITERIA VARCHAR NOT NULL, LIMITATIONS VARCHAR NOT NULL,
  DEFINITION_VERSION VARCHAR NOT NULL, EFFECTIVE_STATUS VARCHAR NOT NULL,
  CONSTRAINT PK_GOLD_PRODUCT_CATALOG PRIMARY KEY (PRODUCT_NAME)
)
COMMENT='Versioned certification intent, ownership, purpose, eligibility and fitness metadata for Gold products';

CREATE TABLE IF NOT EXISTS GOVERNANCE.GOLD_METRIC_CATALOG (
  METRIC_ID VARCHAR NOT NULL, BUSINESS_NAME VARCHAR NOT NULL, BUSINESS_DEFINITION VARCHAR NOT NULL,
  NUMERATOR_DEFINITION VARCHAR, DENOMINATOR_DEFINITION VARCHAR, BUSINESS_GRAIN VARCHAR NOT NULL,
  APPROVED_DIMENSIONS VARCHAR NOT NULL, SOURCE_PRODUCT VARCHAR NOT NULL,
  OWNER_DOMAIN VARCHAR NOT NULL, PERMITTED_PURPOSE VARCHAR NOT NULL,
  AGGREGATION_BEHAVIOR VARCHAR NOT NULL, ZERO_DENOMINATOR_BEHAVIOR VARCHAR NOT NULL,
  DEFINITION_VERSION VARCHAR NOT NULL, EFFECTIVE_STATUS VARCHAR NOT NULL,
  CONSTRAINT PK_GOLD_METRIC_CATALOG PRIMARY KEY (METRIC_ID)
)
COMMENT='Auditable governed metric definitions for later semantic mapping; not a Semantic View';

MERGE INTO GOVERNANCE.GOLD_PRODUCT_CATALOG T USING (
  SELECT COLUMN1 PRODUCT_NAME,COLUMN2 BUSINESS_PURPOSE,COLUMN3 BUSINESS_GRAIN,COLUMN4 BUSINESS_KEY,
         COLUMN5 AUTHORITATIVE_SILVER_SOURCES,COLUMN6 CONSUMPTION_INTENT,COLUMN7 POTENTIALLY_AI_ELIGIBLE,
         COLUMN8 CLASSIFICATION,COLUMN9 SENSITIVITY_LEVEL,COLUMN10 FRESHNESS_EXPECTATION,
         COLUMN11 FITNESS_CRITERIA,COLUMN12 LIMITATIONS FROM VALUES
  ('PAYMENT_EXCEPTION_INVESTIGATION','BANKING_OPERATIONS_INVESTIGATION','One trusted eligible payment exception','EXCEPTION_ID','PAYMENT_EXCEPTION; PAYMENT; SLA_EVENT; OPERATIONS_TEAM','OPERATIONAL_INVESTIGATION_ELIGIBLE',TRUE,'OPERATIONAL_SENSITIVE','HIGH','After each approved Silver transformation','Unique non-null exception key; authoritative relationships; lineage present','Gold eligibility does not authorize AI context; no direct personal/contact/address fields'),
  ('PAYMENT_EXCEPTION_DAILY_METRICS','GOVERNED_ANALYTICS','One event date/channel/currency/high-value flag','EVENT_DATE; PAYMENT_CHANNEL; CURRENCY_CODE; HIGH_VALUE_FLAG','PAYMENT; PAYMENT_EXCEPTION; SLA_EVENT','ANALYTICS_ONLY',FALSE,'GOVERNED_BUSINESS_INFORMATION','MODERATE','After each approved Silver transformation','Counts reconcile to Silver; ratios use safe denominators','Rows are additive only across compatible dimensions; amounts cannot cross currencies'),
  ('PAYMENT_EXCEPTION_PERIOD_COMPARISON','GOVERNED_ANALYTICS','One named comparison window/currency','PERIOD_NAME; CURRENCY_CODE','PAYMENT; PAYMENT_EXCEPTION; SLA_EVENT','ANALYTICS_ONLY',FALSE,'GOVERNED_BUSINESS_INFORMATION','MODERATE','After each approved Silver transformation','Rates derive from counts; deterministic approved windows','Comparison windows overlap and must not be summed or their rates averaged'),
  ('SLA_OPERATIONAL_EXPOSURE','BANKING_OPERATIONS_INVESTIGATION','One trusted exception with representative SLA event','EXCEPTION_ID','PAYMENT_EXCEPTION; SLA_EVENT; OPERATIONS_TEAM','OPERATIONAL_INVESTIGATION_ELIGIBLE',TRUE,'OPERATIONAL_SENSITIVE','HIGH','After each approved Silver transformation','Unique exception key; SLA derivations preserved; lineage present','Gold eligibility does not authorize AI context'),
  ('OPERATIONS_WORKLOAD_SUMMARY','OPERATIONS_MANAGEMENT_ANALYTICS','One date/team/reason/channel/currency','REPORTING_DATE; OWNING_TEAM_ID; EXCEPTION_REASON_CODE; PAYMENT_CHANNEL; CURRENCY_CODE','PAYMENT_EXCEPTION_INVESTIGATION','ANALYTICS_ONLY',FALSE,'GOVERNED_BUSINESS_INFORMATION','MODERATE','After each approved Silver transformation','Counts reconcile to investigation detail','No user-level workload or cross-currency amount aggregation')
) S ON T.PRODUCT_NAME=S.PRODUCT_NAME
WHEN MATCHED THEN UPDATE SET BUSINESS_PURPOSE=S.BUSINESS_PURPOSE,BUSINESS_GRAIN=S.BUSINESS_GRAIN,BUSINESS_KEY=S.BUSINESS_KEY,AUTHORITATIVE_SILVER_SOURCES=S.AUTHORITATIVE_SILVER_SOURCES,OWNER_DOMAIN='BANKING_OPERATIONS',STEWARD_DOMAIN='DATA_GOVERNANCE',PERMITTED_PURPOSE='TRUSTED_BANKING_OPERATIONS_AI',CONSUMPTION_INTENT=S.CONSUMPTION_INTENT,POTENTIALLY_AI_ELIGIBLE=S.POTENTIALLY_AI_ELIGIBLE,AI_CONTEXT_ADMISSION_REQUIRED=TRUE,CLASSIFICATION=S.CLASSIFICATION,SENSITIVITY_LEVEL=S.SENSITIVITY_LEVEL,FRESHNESS_EXPECTATION=S.FRESHNESS_EXPECTATION,FITNESS_CRITERIA=S.FITNESS_CRITERIA,LIMITATIONS=S.LIMITATIONS,DEFINITION_VERSION='1.0',EFFECTIVE_STATUS='APPROVED_FOR_EXECUTION'
WHEN NOT MATCHED THEN INSERT VALUES(S.PRODUCT_NAME,S.BUSINESS_PURPOSE,S.BUSINESS_GRAIN,S.BUSINESS_KEY,S.AUTHORITATIVE_SILVER_SOURCES,'BANKING_OPERATIONS','DATA_GOVERNANCE','TRUSTED_BANKING_OPERATIONS_AI',S.CONSUMPTION_INTENT,S.POTENTIALLY_AI_ELIGIBLE,TRUE,S.CLASSIFICATION,S.SENSITIVITY_LEVEL,S.FRESHNESS_EXPECTATION,S.FITNESS_CRITERIA,S.LIMITATIONS,'1.0','APPROVED_FOR_EXECUTION');

MERGE INTO GOVERNANCE.GOLD_METRIC_CATALOG T USING (
  SELECT COLUMN1 METRIC_ID,COLUMN2 BUSINESS_NAME,COLUMN3 BUSINESS_DEFINITION,COLUMN4 NUMERATOR_DEFINITION,
         COLUMN5 DENOMINATOR_DEFINITION,COLUMN6 AGGREGATION_BEHAVIOR,COLUMN7 ZERO_DENOMINATOR_BEHAVIOR FROM VALUES
  ('PAYMENT_COUNT','Payment Count','Distinct trusted payments at the declared date/channel/currency/high-value grain','COUNT(DISTINCT PAYMENT_ID)',NULL,'SUM counts only across compatible, non-overlapping dimensions','NOT_APPLICABLE'),
  ('EXCEPTION_COUNT','Exception Count','Trusted payment exceptions at the declared grain','COUNT(DISTINCT EXCEPTION_ID)',NULL,'SUM counts only across compatible, non-overlapping dimensions','NOT_APPLICABLE'),
  ('HIGH_VALUE_PAYMENT_COUNT','High-Value Payment Count','Trusted payments whose approved Silver high-value context is true','COUNT(DISTINCT PAYMENT_ID) where high-value is true',NULL,'SUM counts only across compatible dimensions','NOT_APPLICABLE'),
  ('HIGH_VALUE_EXCEPTION_COUNT','High-Value Exception Count','Trusted exceptions associated with approved high-value payments','COUNT(DISTINCT EXCEPTION_ID) where high-value is true',NULL,'SUM counts only across compatible dimensions','NOT_APPLICABLE'),
  ('EXCEPTION_RATE','Exception Rate','Trusted exception count divided by trusted payment count at the declared grain','EXCEPTION_COUNT','PAYMENT_COUNT','Recompute from additive numerator and denominator; never average rates','NULL'),
  ('HIGH_VALUE_EXCEPTION_RATE','High-Value Exception Rate','Percentage of high-value payments that became exceptions','HIGH_VALUE_EXCEPTION_COUNT','HIGH_VALUE_PAYMENT_COUNT','Recompute from additive numerator and denominator; never average rates','NULL'),
  ('UNRESOLVED_EXCEPTION_COUNT','Unresolved Exception Count','Trusted exceptions not in a resolved terminal state','COUNT(DISTINCT EXCEPTION_ID) where unresolved',NULL,'SUM counts only across compatible dimensions','NOT_APPLICABLE'),
  ('SLA_BREACH_COUNT','SLA Breach Count','Trusted exceptions with an authoritative breached SLA indicator','COUNT(DISTINCT EXCEPTION_ID) where SLA breached',NULL,'SUM counts only across compatible dimensions','NOT_APPLICABLE'),
  ('SLA_BREACH_RATE','SLA Breach Rate','SLA-breached exceptions divided by exceptions with SLA evidence','SLA_BREACH_COUNT','COUNT(DISTINCT EXCEPTION_ID) with SLA evidence','Recompute from additive numerator and denominator; never average rates','NULL'),
  ('ESCALATION_REQUIRED_COUNT','Escalation Required Count','Trusted exceptions requiring escalation under authoritative SLA derivation','COUNT(DISTINCT EXCEPTION_ID) where escalation required',NULL,'SUM counts only across compatible dimensions','NOT_APPLICABLE')
) S ON T.METRIC_ID=S.METRIC_ID
WHEN MATCHED THEN UPDATE SET BUSINESS_NAME=S.BUSINESS_NAME,BUSINESS_DEFINITION=S.BUSINESS_DEFINITION,NUMERATOR_DEFINITION=S.NUMERATOR_DEFINITION,DENOMINATOR_DEFINITION=S.DENOMINATOR_DEFINITION,BUSINESS_GRAIN='Declared product grain',APPROVED_DIMENSIONS='DATE; PERIOD; CHANNEL; CURRENCY; HIGH_VALUE; REASON; RESOLUTION; TEAM where present',SOURCE_PRODUCT='PAYMENT_EXCEPTION_DAILY_METRICS; PAYMENT_EXCEPTION_PERIOD_COMPARISON; SLA_OPERATIONAL_EXPOSURE; OPERATIONS_WORKLOAD_SUMMARY',OWNER_DOMAIN='BANKING_OPERATIONS',PERMITTED_PURPOSE='TRUSTED_BANKING_OPERATIONS_AI',AGGREGATION_BEHAVIOR=S.AGGREGATION_BEHAVIOR,ZERO_DENOMINATOR_BEHAVIOR=S.ZERO_DENOMINATOR_BEHAVIOR,DEFINITION_VERSION='1.0',EFFECTIVE_STATUS='APPROVED_FOR_EXECUTION'
WHEN NOT MATCHED THEN INSERT VALUES(S.METRIC_ID,S.BUSINESS_NAME,S.BUSINESS_DEFINITION,S.NUMERATOR_DEFINITION,S.DENOMINATOR_DEFINITION,'Declared product grain','DATE; PERIOD; CHANNEL; CURRENCY; HIGH_VALUE; REASON; RESOLUTION; TEAM where present','PAYMENT_EXCEPTION_DAILY_METRICS; PAYMENT_EXCEPTION_PERIOD_COMPARISON; SLA_OPERATIONAL_EXPOSURE; OPERATIONS_WORKLOAD_SUMMARY','BANKING_OPERATIONS','TRUSTED_BANKING_OPERATIONS_AI',S.AGGREGATION_BEHAVIOR,S.ZERO_DENOMINATOR_BEHAVIOR,'1.0','APPROVED_FOR_EXECUTION');
