-- G2.5 deterministic, replay-safe Silver-to-Gold transformation.
-- Execute this file in one session. If any statement fails, stop and use the
-- failure-finalization statement documented in the G2.5 runbook; never delete the STARTED row.
USE ROLE TRUSTED_AI_DATA_ENGINEER;
USE DATABASE TRUSTED_AI_GOVERNANCE;
ALTER SESSION SET TIMEZONE='UTC';

SET GOLD_TRANSFORMATION_RUN_ID=(SELECT UUID_STRING());
SET GOLD_TRACE_ID=(SELECT UUID_STRING());
SET GOLD_TRANSFORMATION_STARTED_AT=(SELECT CURRENT_TIMESTAMP());

INSERT INTO AUDIT.GOLD_TRANSFORMATION_RUN
SELECT $GOLD_TRANSFORMATION_RUN_ID,$GOLD_TRACE_ID,$GOLD_TRANSFORMATION_STARTED_AT,NULL,
       CURRENT_ROLE(),'STARTED',LAST_QUERY_ID(),NULL;

-- One authoritative exception row. When multiple SLA rows exist, choose the
-- breached/escalated/latest-due record deterministically; missing SLA remains explicit.
CREATE OR REPLACE TEMP TABLE G2_5_EXCEPTION_CONTEXT AS
WITH SLA_RANKED AS (
  SELECT S.*,ROW_NUMBER() OVER (
    PARTITION BY S.EXCEPTION_ID
    ORDER BY IFF(S.DERIVED_SLA_BREACHED_FLAG,1,0) DESC,
             IFF(S.DERIVED_ESCALATION_REQUIRED,1,0) DESC,
             S.SLA_DUE_TIMESTAMP DESC,S.SLA_EVENT_ID
  ) SLA_RANK
  FROM SILVER.SLA_EVENT S WHERE S.DQ_ADMISSION_STATUS='PASS'
)
SELECT E.EXCEPTION_ID,E.PAYMENT_ID,E.ACCOUNT_ID,E.CUSTOMER_ID,E.EXCEPTION_DATE,
       E.EXCEPTION_TIMESTAMP,E.EXCEPTION_REASON_CODE,E.EXCEPTION_CATEGORY,E.SEVERITY,
       E.EXCEPTION_STATUS,E.RESOLUTION_STATUS,E.RESOLVED_TIMESTAMP,E.ASSIGNED_TEAM,
       E.ASSIGNED_ANALYST_ID,E.REQUIRES_MANUAL_REVIEW,E.DERIVED_HIGH_VALUE_FLAG,
       P.PAYMENT_AMOUNT,P.CURRENCY_CODE,P.PAYMENT_CHANNEL,S.SLA_EVENT_ID,
       COALESCE(S.SLA_DUE_TIMESTAMP,E.SLA_DUE_TIMESTAMP) SLA_DUE_TIMESTAMP,
       COALESCE(S.DERIVED_SLA_BREACHED_FLAG,FALSE) SLA_BREACHED_FLAG,
       COALESCE(S.DERIVED_BREACH_MINUTES,0) SLA_BREACH_MINUTES,
       COALESCE(S.DERIVED_ESCALATION_REQUIRED,FALSE) ESCALATION_REQUIRED_FLAG,
       T.TEAM_ID OWNING_TEAM_ID,T.TEAM_NAME OWNING_TEAM_NAME,
       E.TRANSFORMATION_RUN_ID SOURCE_SILVER_TRANSFORMATION_RUN_ID,
       E.TRACE_ID SOURCE_SILVER_TRACE_ID,E.SYNTHETIC_FLAG
FROM SILVER.PAYMENT_EXCEPTION E
JOIN SILVER.PAYMENT P ON E.PAYMENT_ID=P.PAYMENT_ID
LEFT JOIN SLA_RANKED S ON E.EXCEPTION_ID=S.EXCEPTION_ID AND S.SLA_RANK=1
LEFT JOIN SILVER.OPERATIONS_TEAM T ON E.ASSIGNED_TEAM=T.TEAM_ID
WHERE E.DQ_ADMISSION_STATUS='PASS' AND P.DQ_ADMISSION_STATUS='PASS';

INSERT OVERWRITE INTO GOLD.PAYMENT_EXCEPTION_INVESTIGATION
SELECT EXCEPTION_ID,PAYMENT_ID,SHA2(ACCOUNT_ID,256),SHA2(CUSTOMER_ID,256),
       EXCEPTION_DATE,EXCEPTION_TIMESTAMP,EXCEPTION_REASON_CODE,EXCEPTION_CATEGORY,
       SEVERITY,EXCEPTION_STATUS,RESOLUTION_STATUS,RESOLVED_TIMESTAMP,PAYMENT_AMOUNT,
       CURRENCY_CODE,PAYMENT_CHANNEL,DERIVED_HIGH_VALUE_FLAG,SLA_EVENT_ID,
       SLA_DUE_TIMESTAMP,SLA_BREACHED_FLAG,SLA_BREACH_MINUTES,ESCALATION_REQUIRED_FLAG,
       OWNING_TEAM_ID,OWNING_TEAM_NAME,IFF(ASSIGNED_ANALYST_ID IS NULL,NULL,SHA2(ASSIGNED_ANALYST_ID,256)),
       CASE
         WHEN UPPER(COALESCE(RESOLUTION_STATUS,'')) NOT IN ('RESOLVED','CLOSED')
          AND DERIVED_HIGH_VALUE_FLAG AND (SLA_BREACHED_FLAG OR ESCALATION_REQUIRED_FLAG) THEN 'CRITICAL'
         WHEN UPPER(COALESCE(RESOLUTION_STATUS,'')) NOT IN ('RESOLVED','CLOSED')
          AND (DERIVED_HIGH_VALUE_FLAG OR SLA_BREACHED_FLAG OR ESCALATION_REQUIRED_FLAG
               OR UPPER(COALESCE(SEVERITY,'')) IN ('CRITICAL','HIGH')) THEN 'HIGH'
         WHEN UPPER(COALESCE(RESOLUTION_STATUS,'')) NOT IN ('RESOLVED','CLOSED')
          AND (REQUIRES_MANUAL_REVIEW OR DATEDIFF('DAY',EXCEPTION_DATE,'2026-03-15'::DATE)>=3) THEN 'MEDIUM'
         ELSE 'STANDARD' END,
       ARRAY_TO_STRING(ARRAY_CONSTRUCT_COMPACT(
         IFF(UPPER(COALESCE(RESOLUTION_STATUS,'')) NOT IN ('RESOLVED','CLOSED'),'UNRESOLVED',NULL),
         IFF(DERIVED_HIGH_VALUE_FLAG,'HIGH_VALUE',NULL),IFF(SLA_BREACHED_FLAG,'SLA_BREACHED',NULL),
         IFF(ESCALATION_REQUIRED_FLAG,'ESCALATION_REQUIRED',NULL),
         IFF(REQUIRES_MANUAL_REVIEW,'MANUAL_REVIEW',NULL),
         'SEVERITY='||COALESCE(SEVERITY,'UNKNOWN')),';'),
       CASE WHEN EXCEPTION_DATE BETWEEN '2026-03-09' AND '2026-03-15' THEN 'INVESTIGATION_WEEK'
            WHEN EXCEPTION_DATE BETWEEN '2026-03-02' AND '2026-03-08' THEN 'PREVIOUS_WEEK'
            WHEN EXCEPTION_DATE BETWEEN '2026-02-09' AND '2026-03-01' THEN 'TRAILING_FOUR_WEEK'
            ELSE 'HISTORICAL_BASELINE' END,
       $GOLD_TRANSFORMATION_RUN_ID,$GOLD_TRACE_ID,SOURCE_SILVER_TRANSFORMATION_RUN_ID,
       SOURCE_SILVER_TRACE_ID,CURRENT_TIMESTAMP(),SYNTHETIC_FLAG,'PASS'
FROM G2_5_EXCEPTION_CONTEXT;

-- Payment-grain denominator prevents exception joins from inflating PAYMENT_COUNT.
INSERT OVERWRITE INTO GOLD.PAYMENT_EXCEPTION_DAILY_METRICS (
  EVENT_DATE,PAYMENT_CHANNEL,CURRENCY_CODE,HIGH_VALUE_FLAG,PAYMENT_COUNT,EXCEPTION_COUNT,
  HIGH_VALUE_PAYMENT_COUNT,HIGH_VALUE_EXCEPTION_COUNT,EXCEPTION_RATE,
  UNRESOLVED_EXCEPTION_COUNT,SLA_BREACH_COUNT,ESCALATION_REQUIRED_COUNT,
  TOTAL_EXCEPTION_PAYMENT_AMOUNT,GOLD_TRANSFORMATION_RUN_ID,TRACE_ID,
  SOURCE_SILVER_TRANSFORMATION_RUN_IDS,GOLD_TRANSFORMED_AT,SYNTHETIC_FLAG,
  FITNESS_STATUS,HIGH_VALUE_EXCEPTION_RATE
)
WITH PAYMENT_GRAIN AS (
  SELECT P.PAYMENT_ID,P.PAYMENT_DATE,P.PAYMENT_CHANNEL,P.CURRENCY_CODE,P.PAYMENT_AMOUNT,
         IFF(R.HIGH_VALUE_THRESHOLD IS NOT NULL AND P.PAYMENT_AMOUNT>=R.HIGH_VALUE_THRESHOLD,TRUE,FALSE) HIGH_VALUE_FLAG,
         P.TRANSFORMATION_RUN_ID
  FROM SILVER.PAYMENT P LEFT JOIN SILVER.REFERENCE_PAYMENT_THRESHOLD R
    ON P.CURRENCY_CODE=R.CURRENCY_CODE AND R.APPROVAL_STATUS='APPROVED'
   AND P.PAYMENT_DATE BETWEEN R.EFFECTIVE_DATE AND COALESCE(R.EXPIRY_DATE,'9999-12-31'::DATE)
  WHERE P.DQ_ADMISSION_STATUS='PASS'
), EXCEPTION_GRAIN AS (
  SELECT PAYMENT_ID,COUNT(DISTINCT EXCEPTION_ID) EXCEPTION_COUNT,
         COUNT(DISTINCT IFF(DERIVED_HIGH_VALUE_FLAG,EXCEPTION_ID,NULL)) HIGH_VALUE_EXCEPTION_COUNT,
         COUNT(DISTINCT IFF(UPPER(COALESCE(RESOLUTION_STATUS,'')) NOT IN ('RESOLVED','CLOSED'),EXCEPTION_ID,NULL)) UNRESOLVED_COUNT,
         COUNT(DISTINCT IFF(SLA_BREACHED_FLAG,EXCEPTION_ID,NULL)) SLA_BREACH_COUNT,
         COUNT(DISTINCT IFF(ESCALATION_REQUIRED_FLAG,EXCEPTION_ID,NULL)) ESCALATION_COUNT,
         SUM(PAYMENT_AMOUNT) EXCEPTION_AMOUNT
  FROM G2_5_EXCEPTION_CONTEXT GROUP BY PAYMENT_ID
)
SELECT P.PAYMENT_DATE,P.PAYMENT_CHANNEL,P.CURRENCY_CODE,P.HIGH_VALUE_FLAG,
       COUNT(DISTINCT P.PAYMENT_ID),SUM(COALESCE(E.EXCEPTION_COUNT,0)),
       COUNT(DISTINCT IFF(P.HIGH_VALUE_FLAG,P.PAYMENT_ID,NULL)),
       SUM(COALESCE(E.HIGH_VALUE_EXCEPTION_COUNT,0)),
       SUM(COALESCE(E.EXCEPTION_COUNT,0))/NULLIF(COUNT(DISTINCT P.PAYMENT_ID),0),
       SUM(COALESCE(E.UNRESOLVED_COUNT,0)),SUM(COALESCE(E.SLA_BREACH_COUNT,0)),
       SUM(COALESCE(E.ESCALATION_COUNT,0)),SUM(COALESCE(E.EXCEPTION_AMOUNT,0)),
       $GOLD_TRANSFORMATION_RUN_ID,$GOLD_TRACE_ID,ARRAY_AGG(DISTINCT P.TRANSFORMATION_RUN_ID),
       CURRENT_TIMESTAMP(),TRUE,'PASS',
       SUM(COALESCE(E.HIGH_VALUE_EXCEPTION_COUNT,0))
         /NULLIF(COUNT(DISTINCT IFF(P.HIGH_VALUE_FLAG,P.PAYMENT_ID,NULL)),0)
FROM PAYMENT_GRAIN P LEFT JOIN EXCEPTION_GRAIN E ON P.PAYMENT_ID=E.PAYMENT_ID
GROUP BY P.PAYMENT_DATE,P.PAYMENT_CHANNEL,P.CURRENCY_CODE,P.HIGH_VALUE_FLAG;

-- Comparison windows intentionally overlap: PREVIOUS_WEEK is a component of
-- TRAILING_FOUR_WEEK. Each period/currency row is independently computed and non-additive.
INSERT OVERWRITE INTO GOLD.PAYMENT_EXCEPTION_PERIOD_COMPARISON
WITH PERIODS AS (
  SELECT COLUMN1 PERIOD_NAME,COLUMN2::DATE START_DATE,COLUMN3::DATE END_DATE FROM VALUES
  ('INVESTIGATION_WEEK','2026-03-09','2026-03-15'),
  ('PREVIOUS_WEEK','2026-03-02','2026-03-08'),
  ('TRAILING_FOUR_WEEK','2026-02-09','2026-03-08'),
  ('HISTORICAL_BASELINE',NULL,'2026-02-08')
), PAYMENT_GRAIN AS (
  SELECT P.PAYMENT_ID,P.PAYMENT_DATE,P.CURRENCY_CODE,P.TRANSFORMATION_RUN_ID,
         IFF(R.HIGH_VALUE_THRESHOLD IS NOT NULL AND P.PAYMENT_AMOUNT>=R.HIGH_VALUE_THRESHOLD,TRUE,FALSE) HIGH_VALUE_FLAG
  FROM SILVER.PAYMENT P LEFT JOIN SILVER.REFERENCE_PAYMENT_THRESHOLD R
    ON P.CURRENCY_CODE=R.CURRENCY_CODE AND R.APPROVAL_STATUS='APPROVED'
   AND P.PAYMENT_DATE BETWEEN R.EFFECTIVE_DATE AND COALESCE(R.EXPIRY_DATE,'9999-12-31'::DATE)
  WHERE P.DQ_ADMISSION_STATUS='PASS'
)
SELECT W.PERIOD_NAME,W.START_DATE,W.END_DATE,P.CURRENCY_CODE,
       COUNT(DISTINCT P.PAYMENT_ID),COUNT(DISTINCT E.EXCEPTION_ID),
       COUNT(DISTINCT IFF(P.HIGH_VALUE_FLAG,P.PAYMENT_ID,NULL)),
       COUNT(DISTINCT IFF(E.DERIVED_HIGH_VALUE_FLAG,E.EXCEPTION_ID,NULL)),
       COUNT(DISTINCT E.EXCEPTION_ID)/NULLIF(COUNT(DISTINCT P.PAYMENT_ID),0),
       COUNT(DISTINCT IFF(E.DERIVED_HIGH_VALUE_FLAG,E.EXCEPTION_ID,NULL))
         /NULLIF(COUNT(DISTINCT IFF(P.HIGH_VALUE_FLAG,P.PAYMENT_ID,NULL)),0),
       COUNT(DISTINCT IFF(E.SLA_BREACHED_FLAG,E.EXCEPTION_ID,NULL)),
       COUNT(DISTINCT IFF(UPPER(COALESCE(E.RESOLUTION_STATUS,'')) NOT IN ('RESOLVED','CLOSED'),E.EXCEPTION_ID,NULL)),
       $GOLD_TRANSFORMATION_RUN_ID,$GOLD_TRACE_ID,ARRAY_AGG(DISTINCT P.TRANSFORMATION_RUN_ID),
       CURRENT_TIMESTAMP(),TRUE,'PASS'
FROM PERIODS W JOIN PAYMENT_GRAIN P
  ON P.PAYMENT_DATE<=W.END_DATE AND (W.START_DATE IS NULL OR P.PAYMENT_DATE>=W.START_DATE)
LEFT JOIN G2_5_EXCEPTION_CONTEXT E ON P.PAYMENT_ID=E.PAYMENT_ID
GROUP BY W.PERIOD_NAME,W.START_DATE,W.END_DATE,P.CURRENCY_CODE;

INSERT OVERWRITE INTO GOLD.SLA_OPERATIONAL_EXPOSURE
SELECT I.EXCEPTION_ID,I.SLA_EVENT_ID,I.EXCEPTION_DATE,I.SLA_DUE_TIMESTAMP,
       CASE WHEN I.SLA_EVENT_ID IS NULL THEN 'NO_SLA_EVIDENCE'
            WHEN I.SLA_BREACHED_FLAG THEN 'BREACHED'
            WHEN I.SLA_DUE_TIMESTAMP<'2026-03-15'::TIMESTAMP_NTZ THEN 'DUE'
            ELSE 'WITHIN_SLA' END,
       I.SLA_BREACHED_FLAG,I.SLA_BREACH_MINUTES,I.ESCALATION_REQUIRED_FLAG,
       UPPER(COALESCE(I.RESOLUTION_STATUS,'')) NOT IN ('RESOLVED','CLOSED'),I.HIGH_VALUE_FLAG,
       I.EXCEPTION_REASON_CODE,I.OWNING_TEAM_ID,I.OWNING_TEAM_NAME,I.INVESTIGATION_PRIORITY,
       GREATEST(0,DATEDIFF('DAY',I.EXCEPTION_DATE,'2026-03-15'::DATE)),
       $GOLD_TRANSFORMATION_RUN_ID,$GOLD_TRACE_ID,I.SOURCE_SILVER_TRANSFORMATION_RUN_ID,
       I.SOURCE_SILVER_TRACE_ID,CURRENT_TIMESTAMP(),I.SYNTHETIC_FLAG,'PASS'
FROM GOLD.PAYMENT_EXCEPTION_INVESTIGATION I;

INSERT OVERWRITE INTO GOLD.OPERATIONS_WORKLOAD_SUMMARY
SELECT EXCEPTION_DATE,COALESCE(OWNING_TEAM_ID,'UNASSIGNED'),OWNING_TEAM_NAME,
       EXCEPTION_REASON_CODE,PAYMENT_CHANNEL,CURRENCY_CODE,
       COUNT_IF(UPPER(COALESCE(RESOLUTION_STATUS,'')) NOT IN ('RESOLVED','CLOSED')),
       COUNT_IF(UPPER(COALESCE(RESOLUTION_STATUS,'')) NOT IN ('RESOLVED','CLOSED') AND HIGH_VALUE_FLAG),
       COUNT_IF(UPPER(COALESCE(RESOLUTION_STATUS,'')) NOT IN ('RESOLVED','CLOSED') AND SLA_BREACHED_FLAG),
       COUNT_IF(UPPER(COALESCE(RESOLUTION_STATUS,'')) NOT IN ('RESOLVED','CLOSED') AND ESCALATION_REQUIRED_FLAG),
       COUNT_IF(UPPER(COALESCE(RESOLUTION_STATUS,'')) IN ('RESOLVED','CLOSED')),
       AVG(IFF(SLA_BREACHED_FLAG,SLA_BREACH_MINUTES,NULL)),
       $GOLD_TRANSFORMATION_RUN_ID,$GOLD_TRACE_ID,
       ARRAY_AGG(DISTINCT SOURCE_SILVER_TRANSFORMATION_RUN_ID),CURRENT_TIMESTAMP(),TRUE,'PASS'
FROM GOLD.PAYMENT_EXCEPTION_INVESTIGATION
GROUP BY EXCEPTION_DATE,COALESCE(OWNING_TEAM_ID,'UNASSIGNED'),OWNING_TEAM_NAME,
         EXCEPTION_REASON_CODE,PAYMENT_CHANNEL,CURRENCY_CODE;

INSERT INTO AUDIT.GOLD_PRODUCT_EVIDENCE
WITH PRODUCTS AS (
  SELECT 'PAYMENT_EXCEPTION_INVESTIGATION' PRODUCT_NAME,(SELECT COUNT(*) FROM SILVER.PAYMENT_EXCEPTION) SOURCE_COUNT,(SELECT COUNT(*) FROM GOLD.PAYMENT_EXCEPTION_INVESTIGATION) OUTPUT_COUNT,
         (SELECT COUNT(*) FROM GOLD.PAYMENT_EXCEPTION_INVESTIGATION WHERE EXCEPTION_ID IS NULL OR FITNESS_STATUS<>'PASS') FAILURE_COUNT
  UNION ALL SELECT 'PAYMENT_EXCEPTION_DAILY_METRICS',(SELECT COUNT(*) FROM SILVER.PAYMENT),(SELECT COUNT(*) FROM GOLD.PAYMENT_EXCEPTION_DAILY_METRICS),(SELECT COUNT(*) FROM GOLD.PAYMENT_EXCEPTION_DAILY_METRICS WHERE EVENT_DATE IS NULL OR PAYMENT_COUNT<EXCEPTION_COUNT OR FITNESS_STATUS<>'PASS')
  UNION ALL SELECT 'PAYMENT_EXCEPTION_PERIOD_COMPARISON',(SELECT COUNT(*) FROM SILVER.PAYMENT),(SELECT COUNT(*) FROM GOLD.PAYMENT_EXCEPTION_PERIOD_COMPARISON),(SELECT COUNT(*) FROM GOLD.PAYMENT_EXCEPTION_PERIOD_COMPARISON WHERE PERIOD_NAME IS NULL OR FITNESS_STATUS<>'PASS')
  UNION ALL SELECT 'SLA_OPERATIONAL_EXPOSURE',(SELECT COUNT(*) FROM SILVER.PAYMENT_EXCEPTION),(SELECT COUNT(*) FROM GOLD.SLA_OPERATIONAL_EXPOSURE),(SELECT COUNT(*) FROM GOLD.SLA_OPERATIONAL_EXPOSURE WHERE EXCEPTION_ID IS NULL OR FITNESS_STATUS<>'PASS')
  UNION ALL SELECT 'OPERATIONS_WORKLOAD_SUMMARY',(SELECT COUNT(*) FROM GOLD.PAYMENT_EXCEPTION_INVESTIGATION),(SELECT COUNT(*) FROM GOLD.OPERATIONS_WORKLOAD_SUMMARY),(SELECT COUNT(*) FROM GOLD.OPERATIONS_WORKLOAD_SUMMARY WHERE REPORTING_DATE IS NULL OR FITNESS_STATUS<>'PASS')
), LINEAGE AS (
  SELECT ARRAY_AGG(DISTINCT TRANSFORMATION_RUN_ID) RUN_IDS,ARRAY_AGG(DISTINCT TRACE_ID) TRACE_IDS
  FROM SILVER.PAYMENT_EXCEPTION
)
SELECT $GOLD_TRANSFORMATION_RUN_ID,$GOLD_TRACE_ID,P.PRODUCT_NAME,L.RUN_IDS,L.TRACE_IDS,
       P.SOURCE_COUNT,P.OUTPUT_COUNT,P.FAILURE_COUNT,'COMPLETED',CURRENT_TIMESTAMP(),LAST_QUERY_ID()
FROM PRODUCTS P CROSS JOIN LINEAGE L;

UPDATE AUDIT.GOLD_TRANSFORMATION_RUN SET STATUS='COMPLETED',
  TRANSFORMATION_COMPLETED_AT=CURRENT_TIMESTAMP(),QUERY_ID=LAST_QUERY_ID()
WHERE GOLD_TRANSFORMATION_RUN_ID=$GOLD_TRANSFORMATION_RUN_ID;
