-- G2.5 operational validation. Execute only during the later approved G2.5E action.
USE DATABASE TRUSTED_AI_GOVERNANCE;

SELECT 'FIVE_GOLD_PRODUCTS' CHECK_NAME,5 EXPECTED,COUNT(*) ACTUAL,IFF(COUNT(*)=5,'PASS','FAIL') RESULT
FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='GOLD' AND TABLE_NAME IN
('PAYMENT_EXCEPTION_INVESTIGATION','PAYMENT_EXCEPTION_DAILY_METRICS',
 'PAYMENT_EXCEPTION_PERIOD_COMPARISON','SLA_OPERATIONAL_EXPOSURE','OPERATIONS_WORKLOAD_SUMMARY');

SELECT 'INVESTIGATION_UNIQUE_GRAIN' CHECK_NAME,0 EXPECTED,COUNT(*) ACTUAL,IFF(COUNT(*)=0,'PASS','FAIL') RESULT
FROM (SELECT EXCEPTION_ID FROM GOLD.PAYMENT_EXCEPTION_INVESTIGATION GROUP BY EXCEPTION_ID HAVING COUNT(*)<>1);
SELECT 'INVESTIGATION_REQUIRED_KEYS' CHECK_NAME,0 EXPECTED,COUNT(*) ACTUAL,IFF(COUNT(*)=0,'PASS','FAIL') RESULT
FROM GOLD.PAYMENT_EXCEPTION_INVESTIGATION WHERE EXCEPTION_ID IS NULL OR PAYMENT_ID IS NULL
 OR MINIMIZED_ACCOUNT_REFERENCE IS NULL OR MINIMIZED_CUSTOMER_REFERENCE IS NULL;
SELECT 'INVESTIGATION_SILVER_RECONCILIATION' CHECK_NAME,
 (SELECT COUNT(*) FROM SILVER.PAYMENT_EXCEPTION WHERE DQ_ADMISSION_STATUS='PASS') EXPECTED,
 (SELECT COUNT(*) FROM GOLD.PAYMENT_EXCEPTION_INVESTIGATION) ACTUAL,IFF(EXPECTED=ACTUAL,'PASS','FAIL') RESULT;

SELECT 'DAILY_METRIC_SAFE_DENOMINATORS' CHECK_NAME,0 EXPECTED,COUNT(*) ACTUAL,IFF(COUNT(*)=0,'PASS','FAIL') RESULT
FROM GOLD.PAYMENT_EXCEPTION_DAILY_METRICS
WHERE PAYMENT_COUNT<0 OR EXCEPTION_COUNT<0 OR (PAYMENT_COUNT=0 AND EXCEPTION_RATE IS NOT NULL)
   OR (PAYMENT_COUNT>0 AND EXCEPTION_RATE<>EXCEPTION_COUNT/NULLIF(PAYMENT_COUNT,0));
SELECT 'DAILY_HIGH_VALUE_RATE' CHECK_NAME,0 EXPECTED,COUNT(*) ACTUAL,IFF(COUNT(*)=0,'PASS','FAIL') RESULT
FROM GOLD.PAYMENT_EXCEPTION_DAILY_METRICS
WHERE HIGH_VALUE_EXCEPTION_RATE<>HIGH_VALUE_EXCEPTION_COUNT/NULLIF(HIGH_VALUE_PAYMENT_COUNT,0)
   OR (HIGH_VALUE_PAYMENT_COUNT=0 AND HIGH_VALUE_EXCEPTION_RATE IS NOT NULL);
SELECT 'DAILY_CURRENCY_DIMENSION' CHECK_NAME,0 EXPECTED,COUNT(*) ACTUAL,IFF(COUNT(*)=0,'PASS','FAIL') RESULT
FROM GOLD.PAYMENT_EXCEPTION_DAILY_METRICS WHERE CURRENCY_CODE IS NULL;

SELECT 'FOUR_PERIODS_PER_CURRENCY' CHECK_NAME,0 EXPECTED,COUNT(*) ACTUAL,IFF(COUNT(*)=0,'PASS','FAIL') RESULT
FROM (SELECT CURRENCY_CODE FROM GOLD.PAYMENT_EXCEPTION_PERIOD_COMPARISON GROUP BY CURRENCY_CODE HAVING COUNT(DISTINCT PERIOD_NAME)<>4);
SELECT PERIOD_NAME,CURRENCY_CODE,HIGH_VALUE_PAYMENT_COUNT,HIGH_VALUE_EXCEPTION_COUNT,HIGH_VALUE_EXCEPTION_RATE,
 IFF(HIGH_VALUE_EXCEPTION_RATE=HIGH_VALUE_EXCEPTION_COUNT/NULLIF(HIGH_VALUE_PAYMENT_COUNT,0),'PASS','FAIL') RESULT
FROM GOLD.PAYMENT_EXCEPTION_PERIOD_COMPARISON ORDER BY CURRENCY_CODE,PERIOD_START_DATE;
WITH R AS (
 SELECT PERIOD_NAME,SUM(HIGH_VALUE_EXCEPTION_COUNT) N,SUM(HIGH_VALUE_PAYMENT_COUNT) D
 FROM GOLD.PAYMENT_EXCEPTION_PERIOD_COMPARISON GROUP BY PERIOD_NAME
), P AS (SELECT PERIOD_NAME,N/NULLIF(D,0) RATE FROM R)
SELECT 'INVESTIGATION_HIGH_VALUE_SPIKE' CHECK_NAME,
 MAX(IFF(PERIOD_NAME='INVESTIGATION_WEEK',RATE,NULL)) INVESTIGATION_RATE,
 MAX(IFF(PERIOD_NAME='PREVIOUS_WEEK',RATE,NULL)) PREVIOUS_RATE,
 MAX(IFF(PERIOD_NAME='TRAILING_FOUR_WEEK',RATE,NULL)) TRAILING_RATE,
 IFF(INVESTIGATION_RATE>PREVIOUS_RATE AND INVESTIGATION_RATE>TRAILING_RATE,'PASS','FAIL') RESULT FROM P;

SELECT 'DETERMINISTIC_PRIORITY' CHECK_NAME,0 EXPECTED,COUNT(*) ACTUAL,IFF(COUNT(*)=0,'PASS','FAIL') RESULT
FROM GOLD.PAYMENT_EXCEPTION_INVESTIGATION WHERE INVESTIGATION_PRIORITY NOT IN ('CRITICAL','HIGH','MEDIUM','STANDARD')
 OR PRIORITY_REASON IS NULL;
SELECT 'EXC_DEMO_001_DISPOSITION' CHECK_NAME,1 EXPECTED,COUNT(*) ACTUAL,IFF(COUNT(*)=1,'PASS','FAIL') RESULT
FROM GOLD.PAYMENT_EXCEPTION_INVESTIGATION WHERE EXCEPTION_ID='EXC_DEMO_001';
SELECT 'SLA_DEMO_BREACH_001' CHECK_NAME,'75 / TRUE' EXPECTED,
 CONCAT(SLA_BREACH_MINUTES,' / ',SLA_BREACHED_FLAG) ACTUAL,
 IFF(SLA_BREACH_MINUTES=75 AND SLA_BREACHED_FLAG,'PASS','FAIL') RESULT
FROM GOLD.SLA_OPERATIONAL_EXPOSURE WHERE SLA_EVENT_ID='SLA_DEMO_BREACH_001';
SELECT 'PAY_DQ_DUP_001_EXCLUDED' CHECK_NAME,0 EXPECTED,COUNT(*) ACTUAL,IFF(COUNT(*)=0,'PASS','FAIL') RESULT
FROM GOLD.PAYMENT_EXCEPTION_INVESTIGATION WHERE PAYMENT_ID='PAY_DQ_DUP_001';

SELECT 'MINIMIZATION' CHECK_NAME,0 EXPECTED,COUNT(*) ACTUAL,IFF(COUNT(*)=0,'PASS','FAIL') RESULT
FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='GOLD' AND COLUMN_NAME IN
('CUSTOMER_NAME','EMAIL','PHONE','ADDRESS','CITY','STATE','POSTAL_CODE','BENEFICIARY_COUNTRY',
 'BENEFICIARY_TYPE','ASSIGNED_ANALYST_ID','ACCOUNT_ID','CUSTOMER_ID');
SELECT 'LINEAGE_COMPLETENESS' CHECK_NAME,0 EXPECTED,COUNT(*) ACTUAL,IFF(COUNT(*)=0,'PASS','FAIL') RESULT
FROM GOLD.PAYMENT_EXCEPTION_INVESTIGATION WHERE GOLD_TRANSFORMATION_RUN_ID IS NULL OR TRACE_ID IS NULL
 OR SOURCE_SILVER_TRANSFORMATION_RUN_ID IS NULL OR SOURCE_SILVER_TRACE_ID IS NULL;
SELECT 'FIVE_PRODUCT_EVIDENCE_ROWS' CHECK_NAME,5 EXPECTED,COUNT(*) ACTUAL,IFF(COUNT(*)=5,'PASS','FAIL') RESULT
FROM AUDIT.GOLD_PRODUCT_EVIDENCE WHERE GOLD_TRANSFORMATION_RUN_ID=(SELECT GOLD_TRANSFORMATION_RUN_ID
 FROM AUDIT.GOLD_TRANSFORMATION_RUN QUALIFY ROW_NUMBER() OVER(ORDER BY TRANSFORMATION_STARTED_AT DESC)=1);
