-- G2.3 Bronze source-preservation tests
-- These are raw-preservation assertions, not Silver quality disposition.

USE DATABASE TRUSTED_AI_GOVERNANCE;

SELECT 'PAY_DQ_NEGATIVE_001' RECORD_ID, PAYMENT_AMOUNT OBSERVED_VALUE,
       '-1250.00' EXPECTED_VALUE,
       IFF(PAYMENT_AMOUNT='-1250.00','PASS','FAIL') RESULT
FROM BRONZE.PAYMENT_RAW WHERE PAYMENT_ID='PAY_DQ_NEGATIVE_001';

SELECT 'PAY_DQ_CURRENCY_001' RECORD_ID, CURRENCY_CODE OBSERVED_VALUE,
       'ZZZ' EXPECTED_VALUE, IFF(CURRENCY_CODE='ZZZ','PASS','FAIL') RESULT
FROM BRONZE.PAYMENT_RAW WHERE PAYMENT_ID='PAY_DQ_CURRENCY_001';

SELECT 'PAY_DQ_DUP_001' RECORD_ID, SOURCE_REFERENCE,
       COUNT(*) OVER (PARTITION BY SOURCE_REFERENCE) BUSINESS_KEY_OCCURRENCES,
       IFF(COUNT(*) OVER (PARTITION BY SOURCE_REFERENCE)=2,'PASS','FAIL') RESULT
FROM BRONZE.PAYMENT_RAW
WHERE SOURCE_REFERENCE='SYN-DUPLICATE-BUSINESS-KEY-001';

SELECT E.EXCEPTION_ID, E.EXCEPTION_TIMESTAMP, P.PAYMENT_TIMESTAMP,
       IFF(TRY_TO_TIMESTAMP_NTZ(E.EXCEPTION_TIMESTAMP) < TRY_TO_TIMESTAMP_NTZ(P.PAYMENT_TIMESTAMP),'PASS','FAIL') RESULT
FROM BRONZE.PAYMENT_EXCEPTION_RAW E
JOIN BRONZE.PAYMENT_RAW P ON E.PAYMENT_ID=P.PAYMENT_ID
WHERE E.EXCEPTION_ID='EXC_DQ_TIMESTAMP_001';

SELECT 'EXC_DQ_REASON_001' RECORD_ID, EXCEPTION_REASON_CODE,
       IFF(EXCEPTION_REASON_CODE IS NULL,'PASS','FAIL') RESULT
FROM BRONZE.PAYMENT_EXCEPTION_RAW WHERE EXCEPTION_ID='EXC_DQ_REASON_001';

SELECT 'EXC_DQ_EXPIRED_REF_001' RECORD_ID, EXCEPTION_REASON_CODE,
       IFF(EXCEPTION_REASON_CODE='R_EXP','PASS','FAIL') RESULT
FROM BRONZE.PAYMENT_EXCEPTION_RAW WHERE EXCEPTION_ID='EXC_DQ_EXPIRED_REF_001';

SELECT 'SLA_DQ_DUE_001' RECORD_ID, SLA_START_TIMESTAMP, SLA_DUE_TIMESTAMP,
       IFF(TRY_TO_TIMESTAMP_NTZ(SLA_DUE_TIMESTAMP) < TRY_TO_TIMESTAMP_NTZ(SLA_START_TIMESTAMP),'PASS','FAIL') RESULT
FROM BRONZE.SLA_EVENT_RAW WHERE SLA_EVENT_ID='SLA_DQ_DUE_001';

-- Provenance must accompany every deliberate defect.
SELECT 'DQ_ROWS_WITHOUT_PROVENANCE' CHECK_NAME, COUNT(*) OBSERVED, 0 EXPECTED,
       IFF(COUNT(*)=0,'PASS','FAIL') RESULT
FROM (
  SELECT _SOURCE_FILE_NAME, _SOURCE_FILE_ROW_NUMBER, _SOURCE_FILE_CONTENT_KEY, _INGESTION_RUN_ID FROM BRONZE.PAYMENT_RAW WHERE PAYMENT_ID IN ('PAY_DQ_NEGATIVE_001','PAY_DQ_CURRENCY_001','PAY_DQ_DUP_001')
  UNION ALL SELECT _SOURCE_FILE_NAME, _SOURCE_FILE_ROW_NUMBER, _SOURCE_FILE_CONTENT_KEY, _INGESTION_RUN_ID FROM BRONZE.PAYMENT_EXCEPTION_RAW WHERE EXCEPTION_ID IN ('EXC_DQ_TIMESTAMP_001','EXC_DQ_REASON_001','EXC_DQ_EXPIRED_REF_001')
  UNION ALL SELECT _SOURCE_FILE_NAME, _SOURCE_FILE_ROW_NUMBER, _SOURCE_FILE_CONTENT_KEY, _INGESTION_RUN_ID FROM BRONZE.SLA_EVENT_RAW WHERE SLA_EVENT_ID='SLA_DQ_DUE_001'
)
WHERE _SOURCE_FILE_NAME IS NULL OR _SOURCE_FILE_ROW_NUMBER IS NULL
   OR _SOURCE_FILE_CONTENT_KEY IS NULL OR _INGESTION_RUN_ID IS NULL;
