-- G3.1 runtime tests: governed metric equivalence and five source-grain checks. No AI invocation.
USE DATABASE TRUSTED_AI_GOVERNANCE;

SELECT 'TEN_CATALOG_MAPPINGS',10 EXPECTED,COUNT(*) ACTUAL,IFF(COUNT(*)=10,'PASS','FAIL') RESULT
FROM GOVERNANCE.SEMANTIC_METRIC_MAPPING M JOIN GOVERNANCE.GOLD_METRIC_CATALOG G USING(METRIC_ID)
WHERE M.SEMANTIC_OBJECT_ID='SEM-TRUSTED-BANKING-OPERATIONS'
  AND M.GOLD_DEFINITION_VERSION=G.DEFINITION_VERSION AND G.EFFECTIVE_STATUS='APPROVED_FOR_EXECUTION';

SELECT 'HIGH_VALUE_RATE_COMPONENTS','HIGH_VALUE_EXCEPTION_COUNT / HIGH_VALUE_PAYMENT_COUNT' EXPECTED,
       M.SEMANTIC_NUMERATOR||' / '||M.SEMANTIC_DENOMINATOR ACTUAL,
       IFF(M.SEMANTIC_NUMERATOR=G.NUMERATOR_DEFINITION AND M.SEMANTIC_DENOMINATOR=G.DENOMINATOR_DEFINITION,'PASS','FAIL') RESULT
FROM GOVERNANCE.SEMANTIC_METRIC_MAPPING M JOIN GOVERNANCE.GOLD_METRIC_CATALOG G USING(METRIC_ID)
WHERE M.SEMANTIC_OBJECT_ID='SEM-TRUSTED-BANKING-OPERATIONS' AND M.METRIC_ID='HIGH_VALUE_EXCEPTION_RATE';

-- Runtime semantic result is reconciled to an independent Gold calculation, not only metadata text.
WITH S AS (
  SELECT * FROM SEMANTIC_VIEW(
    SEMANTIC.TRUSTED_BANKING_OPERATIONS
    DIMENSIONS daily_metrics.event_date,daily_metrics.channel,daily_metrics.currency,daily_metrics.high_value
    METRICS daily_metrics.payment_count,daily_metrics.exception_count,
            daily_metrics.high_value_payment_count,daily_metrics.high_value_exception_count,
            daily_metrics.exception_rate,daily_metrics.high_value_exception_rate,
            daily_metrics.unresolved_exception_count,daily_metrics.sla_breach_count,
            daily_metrics.escalation_required_count
  )
), G AS (
  SELECT EVENT_DATE,PAYMENT_CHANNEL CHANNEL,CURRENCY_CODE CURRENCY,HIGH_VALUE_FLAG HIGH_VALUE,
         SUM(PAYMENT_COUNT) PAYMENT_COUNT,SUM(EXCEPTION_COUNT) EXCEPTION_COUNT,
         SUM(HIGH_VALUE_PAYMENT_COUNT) HIGH_VALUE_PAYMENT_COUNT,
         SUM(HIGH_VALUE_EXCEPTION_COUNT) HIGH_VALUE_EXCEPTION_COUNT,
         SUM(EXCEPTION_COUNT)/NULLIF(SUM(PAYMENT_COUNT),0) EXCEPTION_RATE,
         SUM(HIGH_VALUE_EXCEPTION_COUNT)/NULLIF(SUM(HIGH_VALUE_PAYMENT_COUNT),0) HIGH_VALUE_EXCEPTION_RATE
         ,SUM(UNRESOLVED_EXCEPTION_COUNT) UNRESOLVED_EXCEPTION_COUNT
         ,SUM(SLA_BREACH_COUNT) SLA_BREACH_COUNT
         ,SUM(ESCALATION_REQUIRED_COUNT) ESCALATION_REQUIRED_COUNT
  FROM GOLD.PAYMENT_EXCEPTION_DAILY_METRICS GROUP BY 1,2,3,4
)
SELECT 'SEMANTIC_DAILY_METRIC_RECONCILIATION',0 EXPECTED,COUNT(*) ACTUAL,IFF(COUNT(*)=0,'PASS','FAIL') RESULT
FROM S FULL JOIN G USING(EVENT_DATE,CHANNEL,CURRENCY,HIGH_VALUE)
WHERE COALESCE(S.PAYMENT_COUNT,-1)<>COALESCE(G.PAYMENT_COUNT,-1)
   OR COALESCE(S.EXCEPTION_COUNT,-1)<>COALESCE(G.EXCEPTION_COUNT,-1)
   OR COALESCE(S.HIGH_VALUE_PAYMENT_COUNT,-1)<>COALESCE(G.HIGH_VALUE_PAYMENT_COUNT,-1)
   OR COALESCE(S.HIGH_VALUE_EXCEPTION_COUNT,-1)<>COALESCE(G.HIGH_VALUE_EXCEPTION_COUNT,-1)
   OR COALESCE(S.EXCEPTION_RATE,-1)<>COALESCE(G.EXCEPTION_RATE,-1)
   OR COALESCE(S.HIGH_VALUE_EXCEPTION_RATE,-1)<>COALESCE(G.HIGH_VALUE_EXCEPTION_RATE,-1)
   OR COALESCE(S.UNRESOLVED_EXCEPTION_COUNT,-1)<>COALESCE(G.UNRESOLVED_EXCEPTION_COUNT,-1)
   OR COALESCE(S.SLA_BREACH_COUNT,-1)<>COALESCE(G.SLA_BREACH_COUNT,-1)
   OR COALESCE(S.ESCALATION_REQUIRED_COUNT,-1)<>COALESCE(G.ESCALATION_REQUIRED_COUNT,-1);

WITH S AS (
  SELECT * FROM SEMANTIC_VIEW(
    SEMANTIC.TRUSTED_BANKING_OPERATIONS
    METRICS sla_exposure.sla_evidence_case_count,sla_exposure.sla_breach_count,
            sla_exposure.sla_breach_rate
  )
), G AS (
  SELECT COUNT_IF(SLA_EVENT_ID IS NOT NULL) SLA_EVIDENCE_CASE_COUNT,
         COUNT_IF(SLA_BREACHED_FLAG) SLA_BREACH_COUNT,
         COUNT_IF(SLA_BREACHED_FLAG)/NULLIF(COUNT_IF(SLA_EVENT_ID IS NOT NULL),0) SLA_BREACH_RATE
  FROM GOLD.SLA_OPERATIONAL_EXPOSURE
)
SELECT 'SEMANTIC_SLA_RATE_RECONCILIATION',0 EXPECTED,COUNT(*) ACTUAL,IFF(COUNT(*)=0,'PASS','FAIL') RESULT
FROM S CROSS JOIN G
WHERE COALESCE(S.SLA_EVIDENCE_CASE_COUNT,-1)<>COALESCE(G.SLA_EVIDENCE_CASE_COUNT,-1)
   OR COALESCE(S.SLA_BREACH_COUNT,-1)<>COALESCE(G.SLA_BREACH_COUNT,-1)
   OR COALESCE(S.SLA_BREACH_RATE,-1)<>COALESCE(G.SLA_BREACH_RATE,-1);

SELECT 'INVESTIGATION_GRAIN',0,COUNT(*),IFF(COUNT(*)=0,'PASS','FAIL') FROM
 (SELECT EXCEPTION_ID FROM GOLD.PAYMENT_EXCEPTION_INVESTIGATION GROUP BY 1 HAVING COUNT(*)<>1);
SELECT 'DAILY_METRIC_GRAIN',0,COUNT(*),IFF(COUNT(*)=0,'PASS','FAIL') FROM
 (SELECT EVENT_DATE,PAYMENT_CHANNEL,CURRENCY_CODE,HIGH_VALUE_FLAG FROM GOLD.PAYMENT_EXCEPTION_DAILY_METRICS GROUP BY ALL HAVING COUNT(*)<>1);
SELECT 'PERIOD_COMPARISON_GRAIN',0,COUNT(*),IFF(COUNT(*)=0,'PASS','FAIL') FROM
 (SELECT PERIOD_NAME,CURRENCY_CODE FROM GOLD.PAYMENT_EXCEPTION_PERIOD_COMPARISON GROUP BY ALL HAVING COUNT(*)<>1);
SELECT 'SLA_EXPOSURE_GRAIN',0,COUNT(*),IFF(COUNT(*)=0,'PASS','FAIL') FROM
 (SELECT EXCEPTION_ID FROM GOLD.SLA_OPERATIONAL_EXPOSURE GROUP BY 1 HAVING COUNT(*)<>1);
SELECT 'WORKLOAD_GRAIN',0,COUNT(*),IFF(COUNT(*)=0,'PASS','FAIL') FROM
 (SELECT REPORTING_DATE,OWNING_TEAM_ID,EXCEPTION_REASON_CODE,PAYMENT_CHANNEL,CURRENCY_CODE
  FROM GOLD.OPERATIONS_WORKLOAD_SUMMARY GROUP BY ALL HAVING COUNT(*)<>1);
