-- G2.5 runtime business-product tests; execute after 030-034 during G2.5E.
USE DATABASE TRUSTED_AI_GOVERNANCE;

SELECT 'FIVE_PRODUCTS' TEST_NAME,5 EXPECTED,COUNT(*) ACTUAL,IFF(COUNT(*)=5,'PASS','FAIL') RESULT
FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='GOLD' AND TABLE_NAME IN
('PAYMENT_EXCEPTION_INVESTIGATION','PAYMENT_EXCEPTION_DAILY_METRICS','PAYMENT_EXCEPTION_PERIOD_COMPARISON','SLA_OPERATIONAL_EXPOSURE','OPERATIONS_WORKLOAD_SUMMARY');
SELECT 'ONE_ROW_PER_EXCEPTION',0,COUNT(*),IFF(COUNT(*)=0,'PASS','FAIL') FROM
(SELECT EXCEPTION_ID FROM GOLD.PAYMENT_EXCEPTION_INVESTIGATION GROUP BY 1 HAVING COUNT(*)<>1);
SELECT 'NON_NULL_BUSINESS_KEYS',0,COUNT(*),IFF(COUNT(*)=0,'PASS','FAIL')
FROM GOLD.PAYMENT_EXCEPTION_INVESTIGATION WHERE EXCEPTION_ID IS NULL OR PAYMENT_ID IS NULL;
WITH COUNTS AS (
 SELECT (SELECT COUNT(*) FROM SILVER.PAYMENT_EXCEPTION WHERE DQ_ADMISSION_STATUS='PASS') EXPECTED,
        (SELECT COUNT(*) FROM GOLD.PAYMENT_EXCEPTION_INVESTIGATION) ACTUAL
)
SELECT 'SILVER_TO_INVESTIGATION',EXPECTED,ACTUAL,IFF(EXPECTED=ACTUAL,'PASS','FAIL') FROM COUNTS;

-- Independent metric reconciliation at the exact date/channel/currency/high-value grain.
WITH EXPECTED AS (
 SELECT P.PAYMENT_DATE EVENT_DATE,P.PAYMENT_CHANNEL,P.CURRENCY_CODE,
        IFF(R.HIGH_VALUE_THRESHOLD IS NOT NULL AND P.PAYMENT_AMOUNT>=R.HIGH_VALUE_THRESHOLD,TRUE,FALSE) HIGH_VALUE_FLAG,
        COUNT(DISTINCT P.PAYMENT_ID) PAYMENT_COUNT
 FROM SILVER.PAYMENT P LEFT JOIN SILVER.REFERENCE_PAYMENT_THRESHOLD R
   ON P.CURRENCY_CODE=R.CURRENCY_CODE AND R.APPROVAL_STATUS='APPROVED'
  AND P.PAYMENT_DATE BETWEEN R.EFFECTIVE_DATE AND COALESCE(R.EXPIRY_DATE,'9999-12-31'::DATE)
 WHERE P.DQ_ADMISSION_STATUS='PASS' GROUP BY 1,2,3,4
)
SELECT 'DAILY_PAYMENT_RECONCILIATION',0,COUNT(*),IFF(COUNT(*)=0,'PASS','FAIL') FROM EXPECTED E
FULL JOIN GOLD.PAYMENT_EXCEPTION_DAILY_METRICS G USING(EVENT_DATE,PAYMENT_CHANNEL,CURRENCY_CODE,HIGH_VALUE_FLAG)
WHERE COALESCE(E.PAYMENT_COUNT,-1)<>COALESCE(G.PAYMENT_COUNT,-1);

SELECT 'SAFE_RATE_MATH',0,COUNT(*),IFF(COUNT(*)=0,'PASS','FAIL')
FROM GOLD.PAYMENT_EXCEPTION_DAILY_METRICS
WHERE EXCEPTION_RATE<>EXCEPTION_COUNT/NULLIF(PAYMENT_COUNT,0)
   OR (PAYMENT_COUNT=0 AND EXCEPTION_RATE IS NOT NULL);
SELECT 'DAILY_HIGH_VALUE_RATE',0,COUNT(*),IFF(COUNT(*)=0,'PASS','FAIL')
FROM GOLD.PAYMENT_EXCEPTION_DAILY_METRICS
WHERE HIGH_VALUE_EXCEPTION_RATE<>HIGH_VALUE_EXCEPTION_COUNT/NULLIF(HIGH_VALUE_PAYMENT_COUNT,0)
   OR (HIGH_VALUE_PAYMENT_COUNT=0 AND HIGH_VALUE_EXCEPTION_RATE IS NOT NULL);
SELECT 'CURRENCY_PRESERVED_FOR_AMOUNTS',0,COUNT(*),IFF(COUNT(*)=0,'PASS','FAIL')
FROM GOLD.PAYMENT_EXCEPTION_DAILY_METRICS WHERE CURRENCY_CODE IS NULL;
SELECT 'VALID_PRIMARY_PERIOD',0,COUNT(*),IFF(COUNT(*)=0,'PASS','FAIL')
FROM GOLD.PAYMENT_EXCEPTION_INVESTIGATION WHERE PRIMARY_PERIOD_CLASSIFICATION NOT IN
('INVESTIGATION_WEEK','PREVIOUS_WEEK','TRAILING_FOUR_WEEK','HISTORICAL_BASELINE');
SELECT 'VALID_PRIORITY',0,COUNT(*),IFF(COUNT(*)=0,'PASS','FAIL')
FROM GOLD.PAYMENT_EXCEPTION_INVESTIGATION WHERE INVESTIGATION_PRIORITY NOT IN ('CRITICAL','HIGH','MEDIUM','STANDARD');

WITH R AS (SELECT PERIOD_NAME,SUM(HIGH_VALUE_EXCEPTION_COUNT) N,SUM(HIGH_VALUE_PAYMENT_COUNT) D
 FROM GOLD.PAYMENT_EXCEPTION_PERIOD_COMPARISON GROUP BY 1),
P AS (SELECT PERIOD_NAME,N/NULLIF(D,0) RATE FROM R),
RATES AS (
 SELECT MAX(IFF(PERIOD_NAME='INVESTIGATION_WEEK',RATE,NULL)) INVESTIGATION_WEEK_RATE,
        MAX(IFF(PERIOD_NAME='PREVIOUS_WEEK',RATE,NULL)) PREVIOUS_WEEK_RATE,
        MAX(IFF(PERIOD_NAME='TRAILING_FOUR_WEEK',RATE,NULL)) TRAILING_FOUR_WEEK_RATE
 FROM P
),
EVALUATED AS (
 SELECT INVESTIGATION_WEEK_RATE>PREVIOUS_WEEK_RATE
        AND INVESTIGATION_WEEK_RATE>TRAILING_FOUR_WEEK_RATE ACTUAL
 FROM RATES
)
SELECT 'HIGH_VALUE_SPIKE',TRUE,ACTUAL,IFF(ACTUAL,'PASS','FAIL') FROM EVALUATED;
SELECT 'SLA_DEMO_BREACH_001','75 / TRUE',CONCAT(SLA_BREACH_MINUTES,' / ',SLA_BREACHED_FLAG),
 IFF(SLA_BREACH_MINUTES=75 AND SLA_BREACHED_FLAG,'PASS','FAIL')
FROM GOLD.SLA_OPERATIONAL_EXPOSURE WHERE SLA_EVENT_ID='SLA_DEMO_BREACH_001';
SELECT 'PAY_DQ_DUP_001_EXCLUDED',0,COUNT(*),IFF(COUNT(*)=0,'PASS','FAIL')
FROM GOLD.PAYMENT_EXCEPTION_INVESTIGATION WHERE PAYMENT_ID='PAY_DQ_DUP_001';
SELECT 'LINEAGE_PRESENT',0,COUNT(*),IFF(COUNT(*)=0,'PASS','FAIL')
FROM GOLD.PAYMENT_EXCEPTION_INVESTIGATION WHERE GOLD_TRANSFORMATION_RUN_ID IS NULL OR TRACE_ID IS NULL
 OR SOURCE_SILVER_TRANSFORMATION_RUN_ID IS NULL OR SOURCE_SILVER_TRACE_ID IS NULL;
