-- G3.1 governed Semantic Layer foundation. Execute only during an approved G3.1E action.
USE ROLE SYSADMIN;
USE DATABASE TRUSTED_AI_GOVERNANCE;

CREATE SCHEMA IF NOT EXISTS SEMANTIC
  COMMENT='Independently authorized structured-intelligence objects derived only from governed Gold at TB-04';

CREATE TABLE IF NOT EXISTS AUDIT.SEMANTIC_DEPLOYMENT_EVIDENCE (
  SEMANTIC_DEPLOYMENT_RUN_ID VARCHAR NOT NULL,
  TRACE_ID VARCHAR NOT NULL,
  SEMANTIC_OBJECT_ID VARCHAR NOT NULL,
  SEMANTIC_OBJECT_NAME VARCHAR NOT NULL,
  SEMANTIC_VERSION VARCHAR NOT NULL,
  GOLD_DEPENDENCIES ARRAY NOT NULL,
  GOLD_TRANSFORMATION_RUN_IDS ARRAY NOT NULL,
  DEPLOYMENT_ROLE VARCHAR NOT NULL,
  DEPLOYED_AT TIMESTAMP_LTZ NOT NULL,
  VALIDATION_STATUS VARCHAR NOT NULL,
  CERTIFICATION_STATUS VARCHAR NOT NULL,
  QUERY_ID VARCHAR,
  CONSTRAINT PK_SEMANTIC_DEPLOYMENT_EVIDENCE PRIMARY KEY (SEMANTIC_DEPLOYMENT_RUN_ID),
  CONSTRAINT SEMANTIC_VALIDATION_STATUS CHECK (VALIDATION_STATUS IN ('PASS','FAIL')),
  CONSTRAINT SEMANTIC_CERTIFICATION_STATUS CHECK (CERTIFICATION_STATUS IN ('READY_FOR_CERTIFICATION','CERTIFIED','REJECTED'))
)
COMMENT='Minimized deployment, version, governed-Gold dependency and validation evidence for Semantic Views';
