-- G3.1 minimal project-managed semantic registry, dependency and governed-metric mappings.
USE ROLE SYSADMIN;
USE DATABASE TRUSTED_AI_GOVERNANCE;

CREATE TABLE IF NOT EXISTS GOVERNANCE.SEMANTIC_OBJECT_REGISTRY (
  SEMANTIC_OBJECT_ID VARCHAR NOT NULL, SEMANTIC_OBJECT_NAME VARCHAR NOT NULL,
  BUSINESS_DOMAIN VARCHAR NOT NULL, OWNER_DOMAIN VARCHAR NOT NULL, STEWARD_DOMAIN VARCHAR NOT NULL,
  PERMITTED_PURPOSE VARCHAR NOT NULL, LIFECYCLE_STATUS VARCHAR NOT NULL,
  SEMANTIC_VERSION VARCHAR NOT NULL, AI_ELIGIBILITY VARCHAR NOT NULL,
  AI_CONTEXT_ADMISSION_REQUIRED BOOLEAN NOT NULL, CERTIFICATION_STATUS VARCHAR NOT NULL,
  EFFECTIVE_AT TIMESTAMP_LTZ NOT NULL, GOVERNANCE_REQUIREMENTS VARCHAR NOT NULL,
  CONTROL_FAMILIES VARCHAR NOT NULL, LIMITATIONS VARCHAR NOT NULL,
  CONSTRAINT PK_SEMANTIC_OBJECT_REGISTRY PRIMARY KEY (SEMANTIC_OBJECT_ID),
  CONSTRAINT SEMANTIC_LIFECYCLE_STATUS CHECK (LIFECYCLE_STATUS IN ('DRAFT','READY_FOR_EXECUTION','APPROVED','RETIRED')),
  CONSTRAINT SEMANTIC_REGISTRY_CERTIFICATION CHECK (CERTIFICATION_STATUS IN ('NOT_CERTIFIED','READY_FOR_CERTIFICATION','CERTIFIED','REJECTED'))
)
COMMENT='Purpose, ownership, lifecycle, version, eligibility and certification intent for governed semantic objects';

CREATE TABLE IF NOT EXISTS GOVERNANCE.SEMANTIC_GOLD_DEPENDENCY (
  SEMANTIC_OBJECT_ID VARCHAR NOT NULL, GOLD_PRODUCT_NAME VARCHAR NOT NULL,
  GOLD_DEFINITION_VERSION VARCHAR NOT NULL, DEPENDENCY_PURPOSE VARCHAR NOT NULL,
  APPROVAL_STATUS VARCHAR NOT NULL,
  CONSTRAINT PK_SEMANTIC_GOLD_DEPENDENCY PRIMARY KEY (SEMANTIC_OBJECT_ID,GOLD_PRODUCT_NAME)
)
COMMENT='Explicit approved Gold-only dependency contract for each semantic object';

CREATE TABLE IF NOT EXISTS GOVERNANCE.SEMANTIC_METRIC_MAPPING (
  SEMANTIC_OBJECT_ID VARCHAR NOT NULL, METRIC_ID VARCHAR NOT NULL,
  LOGICAL_TABLE_NAME VARCHAR NOT NULL, SEMANTIC_METRIC_NAME VARCHAR NOT NULL,
  SEMANTIC_NUMERATOR VARCHAR, SEMANTIC_DENOMINATOR VARCHAR,
  GOLD_DEFINITION_VERSION VARCHAR NOT NULL, MAPPING_STATUS VARCHAR NOT NULL,
  CONSTRAINT PK_SEMANTIC_METRIC_MAPPING PRIMARY KEY (SEMANTIC_OBJECT_ID,METRIC_ID)
)
COMMENT='Deterministic mapping from semantic metrics to authoritative governed Gold metric definitions';

MERGE INTO GOVERNANCE.SEMANTIC_OBJECT_REGISTRY T USING (
  SELECT 'SEM-TRUSTED-BANKING-OPERATIONS' SEMANTIC_OBJECT_ID,
         'TRUSTED_AI_GOVERNANCE.SEMANTIC.TRUSTED_BANKING_OPERATIONS' SEMANTIC_OBJECT_NAME
) S ON T.SEMANTIC_OBJECT_ID=S.SEMANTIC_OBJECT_ID
WHEN MATCHED THEN UPDATE SET SEMANTIC_OBJECT_NAME=S.SEMANTIC_OBJECT_NAME,
  BUSINESS_DOMAIN='TRUSTED_BANKING_OPERATIONS',OWNER_DOMAIN='BANKING_OPERATIONS',STEWARD_DOMAIN='DATA_GOVERNANCE',
  PERMITTED_PURPOSE='TRUSTED_BANKING_OPERATIONS_AI',LIFECYCLE_STATUS='READY_FOR_EXECUTION',SEMANTIC_VERSION='1.0.0',
  AI_ELIGIBILITY='POTENTIALLY_AI_ELIGIBLE',AI_CONTEXT_ADMISSION_REQUIRED=TRUE,CERTIFICATION_STATUS='NOT_CERTIFIED',
  EFFECTIVE_AT=CAST('2026-08-18 00:00:00 +00:00' AS TIMESTAMP_LTZ),
  GOVERNANCE_REQUIREMENTS='GOV-SEM-001;GOV-SEM-002;GOV-SEM-003;GOV-SEM-004;GOV-SEM-005;GOV-SEM-006;GOV-SEM-007',
  CONTROL_FAMILIES='CF-SEM-01;CF-SEM-02;CF-SEM-03;CF-SEM-04;CF-SEM-05;CF-SEM-06',
  LIMITATIONS='Gold only; disconnected logical tables; no cross-currency amount total; overlapping periods are non-additive; Semantic Result is not AI Context Authorization'
WHEN NOT MATCHED THEN INSERT VALUES(
  S.SEMANTIC_OBJECT_ID,S.SEMANTIC_OBJECT_NAME,'TRUSTED_BANKING_OPERATIONS','BANKING_OPERATIONS','DATA_GOVERNANCE',
  'TRUSTED_BANKING_OPERATIONS_AI','READY_FOR_EXECUTION','1.0.0','POTENTIALLY_AI_ELIGIBLE',TRUE,'NOT_CERTIFIED',
  CAST('2026-08-18 00:00:00 +00:00' AS TIMESTAMP_LTZ),
  'GOV-SEM-001;GOV-SEM-002;GOV-SEM-003;GOV-SEM-004;GOV-SEM-005;GOV-SEM-006;GOV-SEM-007',
  'CF-SEM-01;CF-SEM-02;CF-SEM-03;CF-SEM-04;CF-SEM-05;CF-SEM-06',
  'Gold only; disconnected logical tables; no cross-currency amount total; overlapping periods are non-additive; Semantic Result is not AI Context Authorization');

MERGE INTO GOVERNANCE.SEMANTIC_GOLD_DEPENDENCY T USING (
  SELECT 'SEM-TRUSTED-BANKING-OPERATIONS' SEMANTIC_OBJECT_ID,COLUMN1 GOLD_PRODUCT_NAME,COLUMN2 DEPENDENCY_PURPOSE FROM VALUES
  ('PAYMENT_EXCEPTION_INVESTIGATION','Controlled case investigation'),
  ('PAYMENT_EXCEPTION_DAILY_METRICS','Additive daily governed metrics'),
  ('PAYMENT_EXCEPTION_PERIOD_COMPARISON','Non-additive period comparison'),
  ('SLA_OPERATIONAL_EXPOSURE','Representative SLA case analytics'),
  ('OPERATIONS_WORKLOAD_SUMMARY','Team workload analytics')
) S ON T.SEMANTIC_OBJECT_ID=S.SEMANTIC_OBJECT_ID AND T.GOLD_PRODUCT_NAME=S.GOLD_PRODUCT_NAME
WHEN MATCHED THEN UPDATE SET GOLD_DEFINITION_VERSION='1.0',DEPENDENCY_PURPOSE=S.DEPENDENCY_PURPOSE,APPROVAL_STATUS='APPROVED_FOR_EXECUTION'
WHEN NOT MATCHED THEN INSERT VALUES(S.SEMANTIC_OBJECT_ID,S.GOLD_PRODUCT_NAME,'1.0',S.DEPENDENCY_PURPOSE,'APPROVED_FOR_EXECUTION');

MERGE INTO GOVERNANCE.SEMANTIC_METRIC_MAPPING T USING (
  SELECT 'SEM-TRUSTED-BANKING-OPERATIONS' SEMANTIC_OBJECT_ID,COLUMN1 METRIC_ID,COLUMN2 LOGICAL_TABLE_NAME,
         COLUMN3 SEMANTIC_METRIC_NAME,COLUMN4 SEMANTIC_NUMERATOR,COLUMN5 SEMANTIC_DENOMINATOR FROM VALUES
  ('PAYMENT_COUNT','DAILY_METRICS','PAYMENT_COUNT','PAYMENT_COUNT',NULL),
  ('EXCEPTION_COUNT','DAILY_METRICS','EXCEPTION_COUNT','EXCEPTION_COUNT',NULL),
  ('HIGH_VALUE_PAYMENT_COUNT','DAILY_METRICS','HIGH_VALUE_PAYMENT_COUNT','HIGH_VALUE_PAYMENT_COUNT',NULL),
  ('HIGH_VALUE_EXCEPTION_COUNT','DAILY_METRICS','HIGH_VALUE_EXCEPTION_COUNT','HIGH_VALUE_EXCEPTION_COUNT',NULL),
  ('EXCEPTION_RATE','DAILY_METRICS','EXCEPTION_RATE','EXCEPTION_COUNT','PAYMENT_COUNT'),
  ('HIGH_VALUE_EXCEPTION_RATE','DAILY_METRICS','HIGH_VALUE_EXCEPTION_RATE','HIGH_VALUE_EXCEPTION_COUNT','HIGH_VALUE_PAYMENT_COUNT'),
  ('UNRESOLVED_EXCEPTION_COUNT','DAILY_METRICS','UNRESOLVED_EXCEPTION_COUNT','UNRESOLVED_EXCEPTION_COUNT',NULL),
  ('SLA_BREACH_COUNT','DAILY_METRICS','SLA_BREACH_COUNT','SLA_BREACH_COUNT',NULL),
  ('SLA_BREACH_RATE','SLA_EXPOSURE','SLA_BREACH_RATE','SLA_BREACH_COUNT','SLA_EVIDENCE_CASE_COUNT'),
  ('ESCALATION_REQUIRED_COUNT','DAILY_METRICS','ESCALATION_REQUIRED_COUNT','ESCALATION_REQUIRED_COUNT',NULL)
) S ON T.SEMANTIC_OBJECT_ID=S.SEMANTIC_OBJECT_ID AND T.METRIC_ID=S.METRIC_ID
WHEN MATCHED THEN UPDATE SET LOGICAL_TABLE_NAME=S.LOGICAL_TABLE_NAME,SEMANTIC_METRIC_NAME=S.SEMANTIC_METRIC_NAME,
  SEMANTIC_NUMERATOR=S.SEMANTIC_NUMERATOR,SEMANTIC_DENOMINATOR=S.SEMANTIC_DENOMINATOR,
  GOLD_DEFINITION_VERSION='1.0',MAPPING_STATUS='APPROVED_FOR_EXECUTION'
WHEN NOT MATCHED THEN INSERT VALUES(S.SEMANTIC_OBJECT_ID,S.METRIC_ID,S.LOGICAL_TABLE_NAME,S.SEMANTIC_METRIC_NAME,
  S.SEMANTIC_NUMERATOR,S.SEMANTIC_DENOMINATOR,'1.0','APPROVED_FOR_EXECUTION');
