-- G3.1 independent Semantic View authorization. Execute after 050-052 during approved deployment.
USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS TRUSTED_AI_SEMANTIC_CONSUMER
  COMMENT='Queries the approved Trusted Banking Operations Semantic View; no implicit Bronze, Silver, or Gold privileges';
GRANT ROLE TRUSTED_AI_SEMANTIC_CONSUMER TO ROLE SYSADMIN;

USE ROLE SECURITYADMIN;
-- Explicit least-privilege compute dependency for governed Semantic View query execution.
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE TRUSTED_AI_SEMANTIC_CONSUMER;
GRANT USAGE ON DATABASE TRUSTED_AI_GOVERNANCE TO ROLE TRUSTED_AI_SEMANTIC_CONSUMER;
GRANT USAGE ON SCHEMA TRUSTED_AI_GOVERNANCE.SEMANTIC TO ROLE TRUSTED_AI_SEMANTIC_CONSUMER;
GRANT REFERENCES,SELECT ON SEMANTIC VIEW TRUSTED_AI_GOVERNANCE.SEMANTIC.TRUSTED_BANKING_OPERATIONS TO ROLE TRUSTED_AI_SEMANTIC_CONSUMER;

-- Steward and auditor may inspect the governed semantic contract without gaining semantic business-result access.
GRANT USAGE ON SCHEMA TRUSTED_AI_GOVERNANCE.SEMANTIC TO ROLE TRUSTED_AI_DATA_STEWARD;
GRANT REFERENCES ON SEMANTIC VIEW TRUSTED_AI_GOVERNANCE.SEMANTIC.TRUSTED_BANKING_OPERATIONS TO ROLE TRUSTED_AI_DATA_STEWARD;
GRANT USAGE ON SCHEMA TRUSTED_AI_GOVERNANCE.SEMANTIC TO ROLE TRUSTED_AI_AUDITOR;
GRANT REFERENCES ON SEMANTIC VIEW TRUSTED_AI_GOVERNANCE.SEMANTIC.TRUSTED_BANKING_OPERATIONS TO ROLE TRUSTED_AI_AUDITOR;
GRANT SELECT ON TABLE TRUSTED_AI_GOVERNANCE.GOVERNANCE.SEMANTIC_OBJECT_REGISTRY TO ROLE TRUSTED_AI_DATA_STEWARD;
GRANT SELECT ON TABLE TRUSTED_AI_GOVERNANCE.GOVERNANCE.SEMANTIC_GOLD_DEPENDENCY TO ROLE TRUSTED_AI_DATA_STEWARD;
GRANT SELECT ON TABLE TRUSTED_AI_GOVERNANCE.GOVERNANCE.SEMANTIC_METRIC_MAPPING TO ROLE TRUSTED_AI_DATA_STEWARD;
GRANT SELECT ON TABLE TRUSTED_AI_GOVERNANCE.GOVERNANCE.SEMANTIC_OBJECT_REGISTRY TO ROLE TRUSTED_AI_AUDITOR;
GRANT SELECT ON TABLE TRUSTED_AI_GOVERNANCE.GOVERNANCE.SEMANTIC_GOLD_DEPENDENCY TO ROLE TRUSTED_AI_AUDITOR;
GRANT SELECT ON TABLE TRUSTED_AI_GOVERNANCE.GOVERNANCE.SEMANTIC_METRIC_MAPPING TO ROLE TRUSTED_AI_AUDITOR;
GRANT SELECT ON TABLE TRUSTED_AI_GOVERNANCE.AUDIT.SEMANTIC_DEPLOYMENT_EVIDENCE TO ROLE TRUSTED_AI_AUDITOR;

-- BRONZE_READER and TAG_ADMIN intentionally receive no Semantic View privileges.
-- Semantic consumers intentionally receive no direct Gold grants in G3.1.
-- Future Cortex Analyst execution-role requirements must be validated separately before adding any source access.
