-- G3.1 deployment-time structural, registry, metric and evidence validation. No Cortex Analyst invocation.
USE ROLE SYSADMIN;
USE DATABASE TRUSTED_AI_GOVERNANCE;

SHOW SEMANTIC VIEWS LIKE 'TRUSTED_BANKING_OPERATIONS' IN SCHEMA SEMANTIC;
SHOW SEMANTIC DIMENSIONS IN SEMANTIC.TRUSTED_BANKING_OPERATIONS;
SHOW SEMANTIC FACTS IN SEMANTIC.TRUSTED_BANKING_OPERATIONS;
SHOW SEMANTIC METRICS IN SEMANTIC.TRUSTED_BANKING_OPERATIONS;

SELECT 'SEMANTIC_REGISTRY',1 EXPECTED,COUNT(*) ACTUAL,IFF(COUNT(*)=1,'PASS','FAIL') RESULT
FROM GOVERNANCE.SEMANTIC_OBJECT_REGISTRY
WHERE SEMANTIC_OBJECT_ID='SEM-TRUSTED-BANKING-OPERATIONS' AND SEMANTIC_VERSION='1.0.0'
  AND LIFECYCLE_STATUS='READY_FOR_EXECUTION' AND CERTIFICATION_STATUS='NOT_CERTIFIED'
  AND AI_ELIGIBILITY='POTENTIALLY_AI_ELIGIBLE' AND AI_CONTEXT_ADMISSION_REQUIRED;
SELECT 'GOLD_ONLY_DEPENDENCIES',5 EXPECTED,COUNT(*) ACTUAL,IFF(COUNT(*)=5,'PASS','FAIL') RESULT
FROM GOVERNANCE.SEMANTIC_GOLD_DEPENDENCY
WHERE SEMANTIC_OBJECT_ID='SEM-TRUSTED-BANKING-OPERATIONS' AND APPROVAL_STATUS='APPROVED_FOR_EXECUTION';
SELECT 'GOVERNED_METRIC_MAPPINGS',10 EXPECTED,COUNT(*) ACTUAL,IFF(COUNT(*)=10,'PASS','FAIL') RESULT
FROM GOVERNANCE.SEMANTIC_METRIC_MAPPING
WHERE SEMANTIC_OBJECT_ID='SEM-TRUSTED-BANKING-OPERATIONS' AND MAPPING_STATUS='APPROVED_FOR_EXECUTION';
SELECT 'HIGH_VALUE_RATE_MAPPING','HIGH_VALUE_EXCEPTION_COUNT / HIGH_VALUE_PAYMENT_COUNT' EXPECTED,
       SEMANTIC_NUMERATOR||' / '||SEMANTIC_DENOMINATOR ACTUAL,
       IFF(SEMANTIC_NUMERATOR='HIGH_VALUE_EXCEPTION_COUNT' AND SEMANTIC_DENOMINATOR='HIGH_VALUE_PAYMENT_COUNT','PASS','FAIL') RESULT
FROM GOVERNANCE.SEMANTIC_METRIC_MAPPING
WHERE SEMANTIC_OBJECT_ID='SEM-TRUSTED-BANKING-OPERATIONS' AND METRIC_ID='HIGH_VALUE_EXCEPTION_RATE';

-- Record one minimized deployment result only after the preceding validation completes in the approved execution action.
SET SEMANTIC_DEPLOYMENT_RUN_ID=(SELECT UUID_STRING());
SET SEMANTIC_TRACE_ID=(SELECT UUID_STRING());
INSERT INTO AUDIT.SEMANTIC_DEPLOYMENT_EVIDENCE
WITH VALIDATION AS (
  SELECT IFF(
    (SELECT COUNT(*) FROM GOVERNANCE.SEMANTIC_OBJECT_REGISTRY
      WHERE SEMANTIC_OBJECT_ID='SEM-TRUSTED-BANKING-OPERATIONS' AND SEMANTIC_VERSION='1.0.0')=1
    AND (SELECT COUNT(*) FROM GOVERNANCE.SEMANTIC_GOLD_DEPENDENCY
      WHERE SEMANTIC_OBJECT_ID='SEM-TRUSTED-BANKING-OPERATIONS' AND APPROVAL_STATUS='APPROVED_FOR_EXECUTION')=5
    AND (SELECT COUNT(*) FROM GOVERNANCE.SEMANTIC_METRIC_MAPPING
      WHERE SEMANTIC_OBJECT_ID='SEM-TRUSTED-BANKING-OPERATIONS' AND MAPPING_STATUS='APPROVED_FOR_EXECUTION')=10
    AND (SELECT COUNT(*) FROM GOVERNANCE.SEMANTIC_METRIC_MAPPING
      WHERE SEMANTIC_OBJECT_ID='SEM-TRUSTED-BANKING-OPERATIONS' AND METRIC_ID='HIGH_VALUE_EXCEPTION_RATE'
        AND SEMANTIC_NUMERATOR='HIGH_VALUE_EXCEPTION_COUNT' AND SEMANTIC_DENOMINATOR='HIGH_VALUE_PAYMENT_COUNT')=1,
    'PASS','FAIL') VALIDATION_STATUS
)
SELECT $SEMANTIC_DEPLOYMENT_RUN_ID,$SEMANTIC_TRACE_ID,'SEM-TRUSTED-BANKING-OPERATIONS',
       'TRUSTED_AI_GOVERNANCE.SEMANTIC.TRUSTED_BANKING_OPERATIONS','1.0.0',
       ARRAY_CONSTRUCT('PAYMENT_EXCEPTION_INVESTIGATION','PAYMENT_EXCEPTION_DAILY_METRICS',
         'PAYMENT_EXCEPTION_PERIOD_COMPARISON','SLA_OPERATIONAL_EXPOSURE','OPERATIONS_WORKLOAD_SUMMARY'),
       (SELECT ARRAY_AGG(DISTINCT GOLD_TRANSFORMATION_RUN_ID) FROM AUDIT.GOLD_TRANSFORMATION_RUN WHERE STATUS='COMPLETED'),
       CURRENT_ROLE(),CURRENT_TIMESTAMP(),V.VALIDATION_STATUS,
       IFF(V.VALIDATION_STATUS='PASS','READY_FOR_CERTIFICATION','REJECTED'),LAST_QUERY_ID()
FROM VALIDATION V;
