-- G2.4 governed Silver and quarantine physical foundation (review-only).
USE ROLE SYSADMIN;
USE DATABASE TRUSTED_AI_GOVERNANCE;

CREATE SCHEMA IF NOT EXISTS SILVER COMMENT='Trusted, conformed synthetic banking data admitted at TB-02';
CREATE SCHEMA IF NOT EXISTS SILVER_QUARANTINE COMMENT='Governed references to Bronze rows rejected at TB-02';

CREATE TABLE IF NOT EXISTS GOVERNANCE.DQ_RULE_CATALOG (
  DQ_RULE_ID VARCHAR NOT NULL, SOURCE_ENTITY VARCHAR NOT NULL, RULE_NAME VARCHAR NOT NULL,
  RULE_DESCRIPTION VARCHAR NOT NULL, RULE_TYPE VARCHAR NOT NULL, DQ_SEVERITY VARCHAR NOT NULL,
  BLOCKING_FLAG BOOLEAN NOT NULL, EXPECTED_OUTCOME VARCHAR NOT NULL, DQ_SCENARIO_ID VARCHAR,
  GOVERNING_REQUIREMENT VARCHAR NOT NULL, CONTROL_FAMILY VARCHAR NOT NULL,
  ACTIVE_FLAG BOOLEAN NOT NULL, EFFECTIVE_FROM DATE NOT NULL, EFFECTIVE_TO DATE,
  CONSTRAINT DQ_RULE_OUTCOME CHECK (EXPECTED_OUTCOME IN ('PASS','FAIL','QUARANTINE','ALLOW','DENY','MASK','REDACT','ABSTAIN','ESCALATE','REQUIRE_APPROVAL','FLAG_FOR_REVIEW'))
) COMMENT='Deterministic project-managed Silver admission rules; identifiers are technical, not governance requirements';

CREATE TABLE IF NOT EXISTS AUDIT.TRANSFORMATION_RUN (
  TRANSFORMATION_RUN_ID VARCHAR NOT NULL, TRACE_ID VARCHAR NOT NULL,
  TRANSFORMATION_STARTED_AT TIMESTAMP_LTZ NOT NULL, TRANSFORMATION_COMPLETED_AT TIMESTAMP_LTZ,
  EXECUTION_ROLE VARCHAR NOT NULL, STATUS VARCHAR NOT NULL, QUERY_ID VARCHAR,
  CONSTRAINT TRANSFORMATION_RUN_STATUS CHECK (STATUS IN ('STARTED','COMPLETED','FAILED'))
) COMMENT='Persistent execution-level Silver transformation evidence';

CREATE TABLE IF NOT EXISTS AUDIT.TRANSFORMATION_ENTITY_EVIDENCE (
  TRANSFORMATION_RUN_ID VARCHAR NOT NULL, TRACE_ID VARCHAR NOT NULL, SOURCE_ENTITY VARCHAR NOT NULL,
  INGESTION_RUN_ID VARCHAR NOT NULL, BRONZE_INPUT_COUNT NUMBER NOT NULL,
  SILVER_ADMITTED_COUNT NUMBER NOT NULL, QUARANTINED_COUNT NUMBER NOT NULL,
  FAILED_VALIDATION_COUNT NUMBER NOT NULL, EXECUTION_STATUS VARCHAR NOT NULL,
  EVIDENCED_AT TIMESTAMP_LTZ NOT NULL, QUERY_ID VARCHAR
) COMMENT='Entity reconciliation evidence: Bronze equals admitted plus blocking quarantine';

CREATE TABLE IF NOT EXISTS SILVER_QUARANTINE.REJECTED_RECORD (
  QUARANTINE_ID VARCHAR NOT NULL, TRANSFORMATION_RUN_ID VARCHAR NOT NULL, TRACE_ID VARCHAR NOT NULL,
  SOURCE_ENTITY VARCHAR NOT NULL, SOURCE_RECORD_ID VARCHAR NOT NULL,
  BRONZE_RECORD_REFERENCE VARCHAR NOT NULL, SOURCE_FILE_NAME VARCHAR NOT NULL,
  SOURCE_FILE_ROW_NUMBER NUMBER NOT NULL, INGESTION_RUN_ID VARCHAR NOT NULL,
  DQ_RULE_ID VARCHAR NOT NULL, DQ_SCENARIO_ID VARCHAR, DQ_SEVERITY VARCHAR NOT NULL,
  GOVERNANCE_OUTCOME VARCHAR NOT NULL, QUARANTINE_REASON VARCHAR NOT NULL,
  QUARANTINED_AT TIMESTAMP_LTZ NOT NULL, SYNTHETIC_FLAG BOOLEAN NOT NULL,
  CONSTRAINT QUARANTINE_OUTCOME CHECK (GOVERNANCE_OUTCOME='QUARANTINE')
) COMMENT='Minimized rejection evidence referencing immutable Bronze; no raw sensitive payload copy';

-- Bootstrap only the privileges required by the runtime transformation. Broader read grants follow in 044.
USE ROLE SECURITYADMIN;
GRANT USAGE ON SCHEMA TRUSTED_AI_GOVERNANCE.SILVER TO ROLE TRUSTED_AI_DATA_ENGINEER;
GRANT USAGE ON SCHEMA TRUSTED_AI_GOVERNANCE.SILVER_QUARANTINE TO ROLE TRUSTED_AI_DATA_ENGINEER;
GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE ON ALL TABLES IN SCHEMA TRUSTED_AI_GOVERNANCE.SILVER TO ROLE TRUSTED_AI_DATA_ENGINEER;
GRANT SELECT,INSERT,UPDATE ON ALL TABLES IN SCHEMA TRUSTED_AI_GOVERNANCE.SILVER_QUARANTINE TO ROLE TRUSTED_AI_DATA_ENGINEER;
GRANT SELECT,INSERT,UPDATE ON TABLE TRUSTED_AI_GOVERNANCE.GOVERNANCE.DQ_RULE_CATALOG TO ROLE TRUSTED_AI_DATA_ENGINEER;
GRANT SELECT,INSERT,UPDATE ON TABLE TRUSTED_AI_GOVERNANCE.AUDIT.TRANSFORMATION_RUN TO ROLE TRUSTED_AI_DATA_ENGINEER;
GRANT SELECT,INSERT ON TABLE TRUSTED_AI_GOVERNANCE.AUDIT.TRANSFORMATION_ENTITY_EVIDENCE TO ROLE TRUSTED_AI_DATA_ENGINEER;
