-- G2.4 stable technical rule catalog. MERGE is rerunnable and preserves governance metadata.
USE ROLE TRUSTED_AI_DATA_ENGINEER;
USE DATABASE TRUSTED_AI_GOVERNANCE;
MERGE INTO GOVERNANCE.DQ_RULE_CATALOG T USING (
 SELECT * FROM VALUES
 ('SLV-PAY-001','PAYMENT','Required customer','Payment customer identifier is required','COMPLETENESS','ERROR',TRUE,'QUARANTINE','DQ-01','GOV-SLV-002; GOV-SLV-005','CF-SLV-02; CF-SLV-05',TRUE,'2026-03-15'::DATE,NULL),
 ('SLV-PAY-002','PAYMENT','Approved currency','Currency must resolve to an effective approved threshold','REFERENCE','ERROR',TRUE,'QUARANTINE','DQ-02','GOV-SLV-002; GOV-SLV-005','CF-SLV-02; CF-SLV-05',TRUE,'2026-03-15'::DATE,NULL),
 ('SLV-PAY-003','PAYMENT','Positive amount','Payment amount must be non-negative','DOMAIN','ERROR',TRUE,'QUARANTINE','DQ-03','GOV-SLV-002; GOV-SLV-005','CF-SLV-02; CF-SLV-05',TRUE,'2026-03-15'::DATE,NULL),
 ('SLV-PAY-004','PAYMENT','Deterministic duplicate','Lowest file-content-key/row tuple is canonical per source reference','UNIQUENESS','ERROR',TRUE,'QUARANTINE','DQ-04','GOV-SLV-004; GOV-SLV-005','CF-SLV-04; CF-SLV-05',TRUE,'2026-03-15'::DATE,NULL),
 ('SLV-EXC-001','PAYMENT_EXCEPTION','Exception ordering','Exception timestamp cannot precede payment','TEMPORAL','ERROR',TRUE,'QUARANTINE','DQ-05','GOV-SLV-002; GOV-SLV-005','CF-SLV-02; CF-SLV-05',TRUE,'2026-03-15'::DATE,NULL),
 ('SLV-EXC-002','PAYMENT_EXCEPTION','Required reason','Exception reason code is required','COMPLETENESS','ERROR',TRUE,'QUARANTINE','DQ-06','GOV-SLV-002; GOV-SLV-005','CF-SLV-02; CF-SLV-05',TRUE,'2026-03-15'::DATE,NULL),
 ('SLV-SLA-001','SLA_EVENT','SLA ordering','SLA due timestamp cannot precede start','TEMPORAL','ERROR',TRUE,'QUARANTINE','DQ-07','GOV-SLV-002; GOV-SLV-005','CF-SLV-02; CF-SLV-05',TRUE,'2026-03-15'::DATE,NULL),
 ('SLV-EXC-003','PAYMENT_EXCEPTION','Effective reason','Reason must be active and effective on exception date','REFERENCE','ERROR',TRUE,'QUARANTINE','DQ-08','GOV-SLV-002; GOV-SLV-005','CF-SLV-02; CF-SLV-05',TRUE,'2026-03-15'::DATE,NULL),
 ('SLV-REL-001','ALL','Relationship integrity','Approved parent and ownership relationships must resolve','RELATIONSHIP','ERROR',TRUE,'QUARANTINE',NULL,'GOV-SLV-002','CF-SLV-02',TRUE,'2026-03-15'::DATE,NULL),
 ('SLV-STD-001','ALL','Type and code standardization','Required typed values parse and codes are trimmed upper case','SCHEMA','ERROR',TRUE,'QUARANTINE',NULL,'GOV-SLV-001; GOV-SLV-003','CF-SLV-01; CF-SLV-03',TRUE,'2026-03-15'::DATE,NULL)
) S(DQ_RULE_ID,SOURCE_ENTITY,RULE_NAME,RULE_DESCRIPTION,RULE_TYPE,DQ_SEVERITY,BLOCKING_FLAG,EXPECTED_OUTCOME,DQ_SCENARIO_ID,GOVERNING_REQUIREMENT,CONTROL_FAMILY,ACTIVE_FLAG,EFFECTIVE_FROM,EFFECTIVE_TO)
ON T.DQ_RULE_ID=S.DQ_RULE_ID WHEN MATCHED THEN UPDATE SET RULE_DESCRIPTION=S.RULE_DESCRIPTION,ACTIVE_FLAG=S.ACTIVE_FLAG WHEN NOT MATCHED THEN INSERT VALUES(S.DQ_RULE_ID,S.SOURCE_ENTITY,S.RULE_NAME,S.RULE_DESCRIPTION,S.RULE_TYPE,S.DQ_SEVERITY,S.BLOCKING_FLAG,S.EXPECTED_OUTCOME,S.DQ_SCENARIO_ID,S.GOVERNING_REQUIREMENT,S.CONTROL_FAMILY,S.ACTIVE_FLAG,S.EFFECTIVE_FROM,S.EFFECTIVE_TO);
