-- G2.5 Gold execution, product evidence and reconstruction validation.
USE DATABASE TRUSTED_AI_GOVERNANCE;
WITH L AS (SELECT * FROM AUDIT.GOLD_TRANSFORMATION_RUN
 QUALIFY ROW_NUMBER() OVER(ORDER BY TRANSFORMATION_STARTED_AT DESC)=1)
SELECT 'LATEST_GOLD_RUN' CHECK_NAME,'COMPLETED / ONE TRACE / TIMESTAMPS' EXPECTED,
 CONCAT_WS(' / ',STATUS,IFF(TRACE_ID IS NOT NULL,'ONE TRACE','NO TRACE'),
 IFF(TRANSFORMATION_STARTED_AT IS NOT NULL AND TRANSFORMATION_COMPLETED_AT IS NOT NULL,'TIMESTAMPS','MISSING')) ACTUAL,
 IFF(STATUS='COMPLETED' AND TRACE_ID IS NOT NULL AND TRANSFORMATION_COMPLETED_AT>=TRANSFORMATION_STARTED_AT,'PASS','FAIL') RESULT FROM L;

WITH L AS (SELECT GOLD_TRANSFORMATION_RUN_ID,TRACE_ID FROM AUDIT.GOLD_TRANSFORMATION_RUN
 QUALIFY ROW_NUMBER() OVER(ORDER BY TRANSFORMATION_STARTED_AT DESC)=1)
SELECT 'FIVE_PRODUCT_EVIDENCE_ROWS' CHECK_NAME,5 EXPECTED,COUNT(*) ACTUAL,
 IFF(COUNT(*)=5 AND COUNT(DISTINCT E.TRACE_ID)=1 AND MIN(E.TRACE_ID)=MIN(L.TRACE_ID),'PASS','FAIL') RESULT
FROM AUDIT.GOLD_PRODUCT_EVIDENCE E JOIN L USING(GOLD_TRANSFORMATION_RUN_ID);

WITH L AS (SELECT GOLD_TRANSFORMATION_RUN_ID FROM AUDIT.GOLD_TRANSFORMATION_RUN
 QUALIFY ROW_NUMBER() OVER(ORDER BY TRANSFORMATION_STARTED_AT DESC)=1)
SELECT PRODUCT_NAME,SOURCE_SILVER_ROW_COUNT,GOLD_OUTPUT_ROW_COUNT,VALIDATION_FAILURE_COUNT,
 IFF(ARRAY_SIZE(SOURCE_SILVER_TRANSFORMATION_RUN_IDS)>0 AND ARRAY_SIZE(SOURCE_SILVER_TRACE_IDS)>0
  AND VALIDATION_FAILURE_COUNT=0 AND EXECUTION_STATUS='COMPLETED' AND EVIDENCED_AT IS NOT NULL,'PASS','FAIL') RESULT
FROM AUDIT.GOLD_PRODUCT_EVIDENCE JOIN L USING(GOLD_TRANSFORMATION_RUN_ID) ORDER BY PRODUCT_NAME;

-- Reconstruction: Gold row -> Silver exception -> Silver evidence -> Bronze ingestion/source context.
SELECT I.EXCEPTION_ID,I.GOLD_TRANSFORMATION_RUN_ID,I.TRACE_ID,I.SOURCE_SILVER_TRANSFORMATION_RUN_ID,
 I.SOURCE_SILVER_TRACE_ID,S.INGESTION_RUN_ID,S.BRONZE_RECORD_REFERENCE,S.SOURCE_FILE_NAME,
 IFF(S.INGESTION_RUN_ID IS NOT NULL AND S.BRONZE_RECORD_REFERENCE IS NOT NULL AND S.SOURCE_FILE_NAME IS NOT NULL,'PASS','FAIL') RESULT
FROM GOLD.PAYMENT_EXCEPTION_INVESTIGATION I
JOIN SILVER.PAYMENT_EXCEPTION S ON I.EXCEPTION_ID=S.EXCEPTION_ID
WHERE I.EXCEPTION_ID='EXC_DEMO_001';
