-- G3.1 semantic deployment evidence and Gold-lineage continuity tests.
USE DATABASE TRUSTED_AI_GOVERNANCE;

WITH L AS (SELECT * FROM AUDIT.SEMANTIC_DEPLOYMENT_EVIDENCE
 QUALIFY ROW_NUMBER() OVER(ORDER BY DEPLOYED_AT DESC)=1)
SELECT 'LATEST_SEMANTIC_DEPLOYMENT','PASS / READY_FOR_CERTIFICATION / ONE TRACE' EXPECTED,
       CONCAT_WS(' / ',VALIDATION_STATUS,CERTIFICATION_STATUS,IFF(TRACE_ID IS NOT NULL,'ONE TRACE','NO TRACE')) ACTUAL,
       IFF(VALIDATION_STATUS='PASS' AND CERTIFICATION_STATUS='READY_FOR_CERTIFICATION' AND TRACE_ID IS NOT NULL,'PASS','FAIL') RESULT
FROM L;

WITH L AS (SELECT * FROM AUDIT.SEMANTIC_DEPLOYMENT_EVIDENCE
 QUALIFY ROW_NUMBER() OVER(ORDER BY DEPLOYED_AT DESC)=1)
SELECT 'SEMANTIC_VERSION_AND_DEPENDENCIES','1.0.0 / 5' EXPECTED,
       SEMANTIC_VERSION||' / '||ARRAY_SIZE(GOLD_DEPENDENCIES) ACTUAL,
       IFF(SEMANTIC_OBJECT_ID='SEM-TRUSTED-BANKING-OPERATIONS' AND SEMANTIC_VERSION='1.0.0'
         AND ARRAY_SIZE(GOLD_DEPENDENCIES)=5 AND ARRAY_SIZE(GOLD_TRANSFORMATION_RUN_IDS)>0,'PASS','FAIL') RESULT
FROM L;

WITH L AS (SELECT GOLD_TRANSFORMATION_RUN_IDS FROM AUDIT.SEMANTIC_DEPLOYMENT_EVIDENCE
 QUALIFY ROW_NUMBER() OVER(ORDER BY DEPLOYED_AT DESC)=1),
F AS (
 SELECT FLAT.VALUE::VARCHAR GOLD_TRANSFORMATION_RUN_ID
 FROM L, LATERAL FLATTEN(INPUT=>L.GOLD_TRANSFORMATION_RUN_IDS) FLAT
)
SELECT 'GOLD_RUN_RECONSTRUCTION',0 EXPECTED,COUNT(*) ACTUAL,IFF(COUNT(*)=0,'PASS','FAIL') RESULT
FROM F
LEFT JOIN AUDIT.GOLD_TRANSFORMATION_RUN G USING(GOLD_TRANSFORMATION_RUN_ID)
WHERE G.GOLD_TRANSFORMATION_RUN_ID IS NULL OR G.STATUS<>'COMPLETED';

WITH L AS (SELECT GOLD_TRANSFORMATION_RUN_IDS FROM AUDIT.SEMANTIC_DEPLOYMENT_EVIDENCE
 QUALIFY ROW_NUMBER() OVER(ORDER BY DEPLOYED_AT DESC)=1),
SEMANTIC_GOLD_RUNS AS (
 SELECT FLAT.VALUE::VARCHAR GOLD_TRANSFORMATION_RUN_ID
 FROM L, LATERAL FLATTEN(INPUT=>L.GOLD_TRANSFORMATION_RUN_IDS) FLAT
),
GOLD_PRODUCTS AS (
 SELECT R.GOLD_TRANSFORMATION_RUN_ID,P.PRODUCT_NAME,P.SOURCE_SILVER_TRANSFORMATION_RUN_IDS
 FROM SEMANTIC_GOLD_RUNS R
 JOIN AUDIT.GOLD_PRODUCT_EVIDENCE P USING(GOLD_TRANSFORMATION_RUN_ID)
),
SILVER_RUNS AS (
 SELECT P.GOLD_TRANSFORMATION_RUN_ID,P.PRODUCT_NAME,
        FLAT.VALUE::VARCHAR SILVER_TRANSFORMATION_RUN_ID
 FROM GOLD_PRODUCTS P,
      LATERAL FLATTEN(INPUT=>P.SOURCE_SILVER_TRANSFORMATION_RUN_IDS) FLAT
),
DEFECTS AS (
 SELECT COUNT(*) DEFECT_COUNT
 FROM GOVERNANCE.SEMANTIC_GOLD_DEPENDENCY D
 LEFT JOIN GOLD_PRODUCTS P ON D.GOLD_PRODUCT_NAME=P.PRODUCT_NAME
 WHERE D.SEMANTIC_OBJECT_ID='SEM-TRUSTED-BANKING-OPERATIONS'
   AND P.PRODUCT_NAME IS NULL
 UNION ALL
 SELECT COUNT(*)
 FROM GOLD_PRODUCTS
 WHERE ARRAY_SIZE(SOURCE_SILVER_TRANSFORMATION_RUN_IDS)=0
 UNION ALL
 SELECT COUNT(*)
 FROM SILVER_RUNS S
 LEFT JOIN AUDIT.TRANSFORMATION_RUN T
   ON S.SILVER_TRANSFORMATION_RUN_ID=T.TRANSFORMATION_RUN_ID
 WHERE T.TRANSFORMATION_RUN_ID IS NULL OR T.STATUS<>'COMPLETED'
 UNION ALL
 SELECT COUNT(*)
 FROM (SELECT DISTINCT SILVER_TRANSFORMATION_RUN_ID FROM SILVER_RUNS) S
 WHERE NOT EXISTS (
   SELECT 1
   FROM AUDIT.TRANSFORMATION_ENTITY_EVIDENCE E
   JOIN AUDIT.INGESTION_RUN I ON E.INGESTION_RUN_ID=I.INGESTION_RUN_ID
   WHERE E.TRANSFORMATION_RUN_ID=S.SILVER_TRANSFORMATION_RUN_ID
     AND E.EXECUTION_STATUS='COMPLETED' AND I.STATUS='COMPLETED'
 )
)
SELECT 'SEMANTIC_TO_BRONZE_RECONSTRUCTION',0 EXPECTED,SUM(DEFECT_COUNT) ACTUAL,
       IFF(SUM(DEFECT_COUNT)=0,'PASS','FAIL') RESULT
FROM DEFECTS;
