USE DATABASE TRUSTED_AI_GOVERNANCE;
SELECT * FROM AUDIT.TRANSFORMATION_RUN ORDER BY TRANSFORMATION_STARTED_AT DESC;
SELECT SOURCE_ENTITY,BRONZE_INPUT_COUNT,SILVER_ADMITTED_COUNT,QUARANTINED_COUNT,BRONZE_INPUT_COUNT-SILVER_ADMITTED_COUNT-QUARANTINED_COUNT RECONCILIATION_DELTA,IFF(RECONCILIATION_DELTA=0,'PASS','FAIL') RESULT FROM AUDIT.TRANSFORMATION_ENTITY_EVIDENCE WHERE TRANSFORMATION_RUN_ID=(SELECT TRANSFORMATION_RUN_ID FROM AUDIT.TRANSFORMATION_RUN QUALIFY ROW_NUMBER() OVER(ORDER BY TRANSFORMATION_STARTED_AT DESC)=1);
SELECT SOURCE_ENTITY,SOURCE_RECORD_ID,BRONZE_RECORD_REFERENCE,INGESTION_RUN_ID,TRANSFORMATION_RUN_ID,TRACE_ID,DQ_RULE_ID,DQ_SCENARIO_ID,GOVERNANCE_OUTCOME FROM SILVER_QUARANTINE.REJECTED_RECORD ORDER BY SOURCE_ENTITY,SOURCE_RECORD_ID;
