-- G3.1 semantic registration, dependency, lifecycle and certification-intent tests.
USE DATABASE TRUSTED_AI_GOVERNANCE;

SELECT 'SEMANTIC_REGISTRY',1 EXPECTED,COUNT(*) ACTUAL,IFF(COUNT(*)=1,'PASS','FAIL') RESULT
FROM GOVERNANCE.SEMANTIC_OBJECT_REGISTRY
WHERE SEMANTIC_OBJECT_ID='SEM-TRUSTED-BANKING-OPERATIONS'
  AND SEMANTIC_OBJECT_NAME='TRUSTED_AI_GOVERNANCE.SEMANTIC.TRUSTED_BANKING_OPERATIONS'
  AND BUSINESS_DOMAIN='TRUSTED_BANKING_OPERATIONS' AND OWNER_DOMAIN='BANKING_OPERATIONS'
  AND STEWARD_DOMAIN='DATA_GOVERNANCE' AND PERMITTED_PURPOSE='TRUSTED_BANKING_OPERATIONS_AI'
  AND LIFECYCLE_STATUS='READY_FOR_EXECUTION' AND SEMANTIC_VERSION='1.0.0'
  AND AI_ELIGIBILITY='POTENTIALLY_AI_ELIGIBLE' AND AI_CONTEXT_ADMISSION_REQUIRED
  AND CERTIFICATION_STATUS='NOT_CERTIFIED';
SELECT 'APPROVED_GOLD_DEPENDENCIES',5 EXPECTED,COUNT(*) ACTUAL,IFF(COUNT(*)=5,'PASS','FAIL') RESULT
FROM GOVERNANCE.SEMANTIC_GOLD_DEPENDENCY D JOIN GOVERNANCE.GOLD_PRODUCT_CATALOG G
  ON D.GOLD_PRODUCT_NAME=G.PRODUCT_NAME AND D.GOLD_DEFINITION_VERSION=G.DEFINITION_VERSION
WHERE D.SEMANTIC_OBJECT_ID='SEM-TRUSTED-BANKING-OPERATIONS'
  AND D.APPROVAL_STATUS='APPROVED_FOR_EXECUTION' AND G.EFFECTIVE_STATUS='APPROVED_FOR_EXECUTION';
SELECT 'TRACEABLE_METRICS',10 EXPECTED,COUNT(*) ACTUAL,IFF(COUNT(*)=10,'PASS','FAIL') RESULT
FROM GOVERNANCE.SEMANTIC_METRIC_MAPPING M JOIN GOVERNANCE.GOLD_METRIC_CATALOG G USING(METRIC_ID)
WHERE M.SEMANTIC_OBJECT_ID='SEM-TRUSTED-BANKING-OPERATIONS'
  AND M.MAPPING_STATUS='APPROVED_FOR_EXECUTION' AND G.EFFECTIVE_STATUS='APPROVED_FOR_EXECUTION';
