-- G2.3 governance tests
-- Execute after ingestion with a validation role authorized to inspect objects.
-- These queries report observations; they do not fabricate Snowflake execution evidence.

USE DATABASE TRUSTED_AI_GOVERNANCE;

-- PROJECT GOVERNANCE TAGS — MANDATORY
-- Exactly ten expected tables.
SELECT 'EXPECTED_BRONZE_TABLES' CHECK_NAME, COUNT(*) OBSERVED, 10 EXPECTED,
       IFF(COUNT(*)=10,'PASS','FAIL') RESULT
FROM TRUSTED_AI_GOVERNANCE.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA='BRONZE'
  AND TABLE_NAME IN ('CUSTOMER_RAW','ACCOUNT_RAW','PAYMENT_RAW',
    'PAYMENT_EXCEPTION_RAW','SLA_EVENT_RAW','OPERATIONS_TEAM_RAW',
    'OPERATIONS_USER_RAW','REFERENCE_EXCEPTION_REASON_RAW',
    'REFERENCE_PAYMENT_THRESHOLD_RAW','GOVERNANCE_REFERENCE_RAW');

-- All ten tables must explicitly carry DATA_LAYER=BRONZE and SYNTHETIC_DATA=TRUE.
WITH TAG_RESULTS AS (
  SELECT 'CUSTOMER_RAW' TABLE_NAME, SYSTEM$GET_TAG('TRUSTED_AI_GOVERNANCE.GOVERNANCE.DATA_LAYER','TRUSTED_AI_GOVERNANCE.BRONZE.CUSTOMER_RAW','TABLE') DATA_LAYER, SYSTEM$GET_TAG('TRUSTED_AI_GOVERNANCE.GOVERNANCE.SYNTHETIC_DATA','TRUSTED_AI_GOVERNANCE.BRONZE.CUSTOMER_RAW','TABLE') SYNTHETIC_DATA
  UNION ALL SELECT 'ACCOUNT_RAW', SYSTEM$GET_TAG('TRUSTED_AI_GOVERNANCE.GOVERNANCE.DATA_LAYER','TRUSTED_AI_GOVERNANCE.BRONZE.ACCOUNT_RAW','TABLE'), SYSTEM$GET_TAG('TRUSTED_AI_GOVERNANCE.GOVERNANCE.SYNTHETIC_DATA','TRUSTED_AI_GOVERNANCE.BRONZE.ACCOUNT_RAW','TABLE')
  UNION ALL SELECT 'PAYMENT_RAW', SYSTEM$GET_TAG('TRUSTED_AI_GOVERNANCE.GOVERNANCE.DATA_LAYER','TRUSTED_AI_GOVERNANCE.BRONZE.PAYMENT_RAW','TABLE'), SYSTEM$GET_TAG('TRUSTED_AI_GOVERNANCE.GOVERNANCE.SYNTHETIC_DATA','TRUSTED_AI_GOVERNANCE.BRONZE.PAYMENT_RAW','TABLE')
  UNION ALL SELECT 'PAYMENT_EXCEPTION_RAW', SYSTEM$GET_TAG('TRUSTED_AI_GOVERNANCE.GOVERNANCE.DATA_LAYER','TRUSTED_AI_GOVERNANCE.BRONZE.PAYMENT_EXCEPTION_RAW','TABLE'), SYSTEM$GET_TAG('TRUSTED_AI_GOVERNANCE.GOVERNANCE.SYNTHETIC_DATA','TRUSTED_AI_GOVERNANCE.BRONZE.PAYMENT_EXCEPTION_RAW','TABLE')
  UNION ALL SELECT 'SLA_EVENT_RAW', SYSTEM$GET_TAG('TRUSTED_AI_GOVERNANCE.GOVERNANCE.DATA_LAYER','TRUSTED_AI_GOVERNANCE.BRONZE.SLA_EVENT_RAW','TABLE'), SYSTEM$GET_TAG('TRUSTED_AI_GOVERNANCE.GOVERNANCE.SYNTHETIC_DATA','TRUSTED_AI_GOVERNANCE.BRONZE.SLA_EVENT_RAW','TABLE')
  UNION ALL SELECT 'OPERATIONS_TEAM_RAW', SYSTEM$GET_TAG('TRUSTED_AI_GOVERNANCE.GOVERNANCE.DATA_LAYER','TRUSTED_AI_GOVERNANCE.BRONZE.OPERATIONS_TEAM_RAW','TABLE'), SYSTEM$GET_TAG('TRUSTED_AI_GOVERNANCE.GOVERNANCE.SYNTHETIC_DATA','TRUSTED_AI_GOVERNANCE.BRONZE.OPERATIONS_TEAM_RAW','TABLE')
  UNION ALL SELECT 'OPERATIONS_USER_RAW', SYSTEM$GET_TAG('TRUSTED_AI_GOVERNANCE.GOVERNANCE.DATA_LAYER','TRUSTED_AI_GOVERNANCE.BRONZE.OPERATIONS_USER_RAW','TABLE'), SYSTEM$GET_TAG('TRUSTED_AI_GOVERNANCE.GOVERNANCE.SYNTHETIC_DATA','TRUSTED_AI_GOVERNANCE.BRONZE.OPERATIONS_USER_RAW','TABLE')
  UNION ALL SELECT 'REFERENCE_EXCEPTION_REASON_RAW', SYSTEM$GET_TAG('TRUSTED_AI_GOVERNANCE.GOVERNANCE.DATA_LAYER','TRUSTED_AI_GOVERNANCE.BRONZE.REFERENCE_EXCEPTION_REASON_RAW','TABLE'), SYSTEM$GET_TAG('TRUSTED_AI_GOVERNANCE.GOVERNANCE.SYNTHETIC_DATA','TRUSTED_AI_GOVERNANCE.BRONZE.REFERENCE_EXCEPTION_REASON_RAW','TABLE')
  UNION ALL SELECT 'REFERENCE_PAYMENT_THRESHOLD_RAW', SYSTEM$GET_TAG('TRUSTED_AI_GOVERNANCE.GOVERNANCE.DATA_LAYER','TRUSTED_AI_GOVERNANCE.BRONZE.REFERENCE_PAYMENT_THRESHOLD_RAW','TABLE'), SYSTEM$GET_TAG('TRUSTED_AI_GOVERNANCE.GOVERNANCE.SYNTHETIC_DATA','TRUSTED_AI_GOVERNANCE.BRONZE.REFERENCE_PAYMENT_THRESHOLD_RAW','TABLE')
  UNION ALL SELECT 'GOVERNANCE_REFERENCE_RAW', SYSTEM$GET_TAG('TRUSTED_AI_GOVERNANCE.GOVERNANCE.DATA_LAYER','TRUSTED_AI_GOVERNANCE.BRONZE.GOVERNANCE_REFERENCE_RAW','TABLE'), SYSTEM$GET_TAG('TRUSTED_AI_GOVERNANCE.GOVERNANCE.SYNTHETIC_DATA','TRUSTED_AI_GOVERNANCE.BRONZE.GOVERNANCE_REFERENCE_RAW','TABLE')
)
SELECT TABLE_NAME, DATA_LAYER, SYNTHETIC_DATA,
       IFF(DATA_LAYER='BRONZE' AND SYNTHETIC_DATA='TRUE','PASS','FAIL') RESULT
FROM TAG_RESULTS ORDER BY TABLE_NAME;

-- Representative required column classifications.
WITH COLUMN_TAGS AS (
  SELECT 'CUSTOMER_RAW.CUSTOMER_NAME' OBJECT_COLUMN, 'DIRECT_PERSONAL_IDENTIFIER' EXPECTED_CLASSIFICATION, SYSTEM$GET_TAG('TRUSTED_AI_GOVERNANCE.GOVERNANCE.DATA_CLASSIFICATION','TRUSTED_AI_GOVERNANCE.BRONZE.CUSTOMER_RAW.CUSTOMER_NAME','COLUMN') OBSERVED_CLASSIFICATION
  UNION ALL SELECT 'CUSTOMER_RAW.DATE_OF_BIRTH','DIRECT_PERSONAL_IDENTIFIER',SYSTEM$GET_TAG('TRUSTED_AI_GOVERNANCE.GOVERNANCE.DATA_CLASSIFICATION','TRUSTED_AI_GOVERNANCE.BRONZE.CUSTOMER_RAW.DATE_OF_BIRTH','COLUMN')
  UNION ALL SELECT 'CUSTOMER_RAW.EMAIL','DIRECT_PERSONAL_IDENTIFIER',SYSTEM$GET_TAG('TRUSTED_AI_GOVERNANCE.GOVERNANCE.DATA_CLASSIFICATION','TRUSTED_AI_GOVERNANCE.BRONZE.CUSTOMER_RAW.EMAIL','COLUMN')
  UNION ALL SELECT 'CUSTOMER_RAW.PHONE','DIRECT_PERSONAL_IDENTIFIER',SYSTEM$GET_TAG('TRUSTED_AI_GOVERNANCE.GOVERNANCE.DATA_CLASSIFICATION','TRUSTED_AI_GOVERNANCE.BRONZE.CUSTOMER_RAW.PHONE','COLUMN')
  UNION ALL SELECT 'CUSTOMER_RAW.ADDRESS_LINE','DIRECT_PERSONAL_IDENTIFIER',SYSTEM$GET_TAG('TRUSTED_AI_GOVERNANCE.GOVERNANCE.DATA_CLASSIFICATION','TRUSTED_AI_GOVERNANCE.BRONZE.CUSTOMER_RAW.ADDRESS_LINE','COLUMN')
  UNION ALL SELECT 'CUSTOMER_RAW.POSTAL_CODE','DIRECT_PERSONAL_IDENTIFIER',SYSTEM$GET_TAG('TRUSTED_AI_GOVERNANCE.GOVERNANCE.DATA_CLASSIFICATION','TRUSTED_AI_GOVERNANCE.BRONZE.CUSTOMER_RAW.POSTAL_CODE','COLUMN')
  UNION ALL SELECT 'ACCOUNT_RAW.ACCOUNT_ID','FINANCIALLY_SENSITIVE',SYSTEM$GET_TAG('TRUSTED_AI_GOVERNANCE.GOVERNANCE.DATA_CLASSIFICATION','TRUSTED_AI_GOVERNANCE.BRONZE.ACCOUNT_RAW.ACCOUNT_ID','COLUMN')
  UNION ALL SELECT 'ACCOUNT_RAW.AVAILABLE_BALANCE','FINANCIALLY_SENSITIVE',SYSTEM$GET_TAG('TRUSTED_AI_GOVERNANCE.GOVERNANCE.DATA_CLASSIFICATION','TRUSTED_AI_GOVERNANCE.BRONZE.ACCOUNT_RAW.AVAILABLE_BALANCE','COLUMN')
  UNION ALL SELECT 'PAYMENT_RAW.ACCOUNT_ID','FINANCIALLY_SENSITIVE',SYSTEM$GET_TAG('TRUSTED_AI_GOVERNANCE.GOVERNANCE.DATA_CLASSIFICATION','TRUSTED_AI_GOVERNANCE.BRONZE.PAYMENT_RAW.ACCOUNT_ID','COLUMN')
  UNION ALL SELECT 'PAYMENT_RAW.CUSTOMER_ID','DIRECT_PERSONAL_IDENTIFIER',SYSTEM$GET_TAG('TRUSTED_AI_GOVERNANCE.GOVERNANCE.DATA_CLASSIFICATION','TRUSTED_AI_GOVERNANCE.BRONZE.PAYMENT_RAW.CUSTOMER_ID','COLUMN')
  UNION ALL SELECT 'PAYMENT_RAW.PAYMENT_AMOUNT','FINANCIALLY_SENSITIVE',SYSTEM$GET_TAG('TRUSTED_AI_GOVERNANCE.GOVERNANCE.DATA_CLASSIFICATION','TRUSTED_AI_GOVERNANCE.BRONZE.PAYMENT_RAW.PAYMENT_AMOUNT','COLUMN')
  UNION ALL SELECT 'PAYMENT_RAW.BENEFICIARY_COUNTRY','FINANCIALLY_SENSITIVE',SYSTEM$GET_TAG('TRUSTED_AI_GOVERNANCE.GOVERNANCE.DATA_CLASSIFICATION','TRUSTED_AI_GOVERNANCE.BRONZE.PAYMENT_RAW.BENEFICIARY_COUNTRY','COLUMN')
  UNION ALL SELECT 'PAYMENT_RAW.BENEFICIARY_TYPE','FINANCIALLY_SENSITIVE',SYSTEM$GET_TAG('TRUSTED_AI_GOVERNANCE.GOVERNANCE.DATA_CLASSIFICATION','TRUSTED_AI_GOVERNANCE.BRONZE.PAYMENT_RAW.BENEFICIARY_TYPE','COLUMN')
  UNION ALL SELECT 'PAYMENT_EXCEPTION_RAW.CUSTOMER_ID','DIRECT_PERSONAL_IDENTIFIER',SYSTEM$GET_TAG('TRUSTED_AI_GOVERNANCE.GOVERNANCE.DATA_CLASSIFICATION','TRUSTED_AI_GOVERNANCE.BRONZE.PAYMENT_EXCEPTION_RAW.CUSTOMER_ID','COLUMN')
  UNION ALL SELECT 'PAYMENT_EXCEPTION_RAW.ACCOUNT_ID','FINANCIALLY_SENSITIVE',SYSTEM$GET_TAG('TRUSTED_AI_GOVERNANCE.GOVERNANCE.DATA_CLASSIFICATION','TRUSTED_AI_GOVERNANCE.BRONZE.PAYMENT_EXCEPTION_RAW.ACCOUNT_ID','COLUMN')
  UNION ALL SELECT 'PAYMENT_EXCEPTION_RAW.EXCEPTION_REASON_DESCRIPTION','OPERATIONAL_SENSITIVE',SYSTEM$GET_TAG('TRUSTED_AI_GOVERNANCE.GOVERNANCE.DATA_CLASSIFICATION','TRUSTED_AI_GOVERNANCE.BRONZE.PAYMENT_EXCEPTION_RAW.EXCEPTION_REASON_DESCRIPTION','COLUMN')
  UNION ALL SELECT 'PAYMENT_EXCEPTION_RAW.ASSIGNED_ANALYST_ID','OPERATIONAL_SENSITIVE',SYSTEM$GET_TAG('TRUSTED_AI_GOVERNANCE.GOVERNANCE.DATA_CLASSIFICATION','TRUSTED_AI_GOVERNANCE.BRONZE.PAYMENT_EXCEPTION_RAW.ASSIGNED_ANALYST_ID','COLUMN')
  UNION ALL SELECT 'OPERATIONS_USER_RAW.OPERATIONS_USER_ID','OPERATIONAL_SENSITIVE',SYSTEM$GET_TAG('TRUSTED_AI_GOVERNANCE.GOVERNANCE.DATA_CLASSIFICATION','TRUSTED_AI_GOVERNANCE.BRONZE.OPERATIONS_USER_RAW.OPERATIONS_USER_ID','COLUMN')
  UNION ALL SELECT 'OPERATIONS_USER_RAW.DISPLAY_NAME','OPERATIONAL_SENSITIVE',SYSTEM$GET_TAG('TRUSTED_AI_GOVERNANCE.GOVERNANCE.DATA_CLASSIFICATION','TRUSTED_AI_GOVERNANCE.BRONZE.OPERATIONS_USER_RAW.DISPLAY_NAME','COLUMN')
)
SELECT OBJECT_COLUMN, EXPECTED_CLASSIFICATION, OBSERVED_CLASSIFICATION,
       IFF(OBSERVED_CLASSIFICATION=EXPECTED_CLASSIFICATION,'PASS','FAIL') RESULT
FROM COLUMN_TAGS ORDER BY OBJECT_COLUMN;

SELECT 'ACTIVE_SYNTHETIC_SOURCES' CHECK_NAME, COUNT(*) OBSERVED, 10 EXPECTED,
       IFF(COUNT(*)=10,'PASS','FAIL') RESULT
FROM GOVERNANCE.INGESTION_SOURCE_REGISTRY
WHERE ACTIVE_FLAG=TRUE AND SYNTHETIC_FLAG=TRUE;

SELECT 'ROWS_WITHOUT_INGESTION_CONTEXT' CHECK_NAME, SUM(MISSING_ROWS) OBSERVED, 0 EXPECTED,
       IFF(SUM(MISSING_ROWS)=0,'PASS','FAIL') RESULT
FROM (
  SELECT COUNT_IF(_INGESTION_RUN_ID IS NULL OR _SOURCE_FILE_NAME IS NULL OR _SOURCE_FILE_ROW_NUMBER IS NULL OR _SOURCE_FILE_CONTENT_KEY IS NULL OR _STAGE_SCAN_TIME IS NULL OR _INGESTED_AT IS NULL OR _SYNTHETIC_FLAG IS DISTINCT FROM TRUE) MISSING_ROWS FROM BRONZE.CUSTOMER_RAW
  UNION ALL SELECT COUNT_IF(_INGESTION_RUN_ID IS NULL OR _SOURCE_FILE_NAME IS NULL OR _SOURCE_FILE_ROW_NUMBER IS NULL OR _SOURCE_FILE_CONTENT_KEY IS NULL OR _STAGE_SCAN_TIME IS NULL OR _INGESTED_AT IS NULL OR _SYNTHETIC_FLAG IS DISTINCT FROM TRUE) FROM BRONZE.ACCOUNT_RAW
  UNION ALL SELECT COUNT_IF(_INGESTION_RUN_ID IS NULL OR _SOURCE_FILE_NAME IS NULL OR _SOURCE_FILE_ROW_NUMBER IS NULL OR _SOURCE_FILE_CONTENT_KEY IS NULL OR _STAGE_SCAN_TIME IS NULL OR _INGESTED_AT IS NULL OR _SYNTHETIC_FLAG IS DISTINCT FROM TRUE) FROM BRONZE.PAYMENT_RAW
  UNION ALL SELECT COUNT_IF(_INGESTION_RUN_ID IS NULL OR _SOURCE_FILE_NAME IS NULL OR _SOURCE_FILE_ROW_NUMBER IS NULL OR _SOURCE_FILE_CONTENT_KEY IS NULL OR _STAGE_SCAN_TIME IS NULL OR _INGESTED_AT IS NULL OR _SYNTHETIC_FLAG IS DISTINCT FROM TRUE) FROM BRONZE.PAYMENT_EXCEPTION_RAW
  UNION ALL SELECT COUNT_IF(_INGESTION_RUN_ID IS NULL OR _SOURCE_FILE_NAME IS NULL OR _SOURCE_FILE_ROW_NUMBER IS NULL OR _SOURCE_FILE_CONTENT_KEY IS NULL OR _STAGE_SCAN_TIME IS NULL OR _INGESTED_AT IS NULL OR _SYNTHETIC_FLAG IS DISTINCT FROM TRUE) FROM BRONZE.SLA_EVENT_RAW
  UNION ALL SELECT COUNT_IF(_INGESTION_RUN_ID IS NULL OR _SOURCE_FILE_NAME IS NULL OR _SOURCE_FILE_ROW_NUMBER IS NULL OR _SOURCE_FILE_CONTENT_KEY IS NULL OR _STAGE_SCAN_TIME IS NULL OR _INGESTED_AT IS NULL OR _SYNTHETIC_FLAG IS DISTINCT FROM TRUE) FROM BRONZE.OPERATIONS_TEAM_RAW
  UNION ALL SELECT COUNT_IF(_INGESTION_RUN_ID IS NULL OR _SOURCE_FILE_NAME IS NULL OR _SOURCE_FILE_ROW_NUMBER IS NULL OR _SOURCE_FILE_CONTENT_KEY IS NULL OR _STAGE_SCAN_TIME IS NULL OR _INGESTED_AT IS NULL OR _SYNTHETIC_FLAG IS DISTINCT FROM TRUE) FROM BRONZE.OPERATIONS_USER_RAW
  UNION ALL SELECT COUNT_IF(_INGESTION_RUN_ID IS NULL OR _SOURCE_FILE_NAME IS NULL OR _SOURCE_FILE_ROW_NUMBER IS NULL OR _SOURCE_FILE_CONTENT_KEY IS NULL OR _STAGE_SCAN_TIME IS NULL OR _INGESTED_AT IS NULL OR _SYNTHETIC_FLAG IS DISTINCT FROM TRUE) FROM BRONZE.REFERENCE_EXCEPTION_REASON_RAW
  UNION ALL SELECT COUNT_IF(_INGESTION_RUN_ID IS NULL OR _SOURCE_FILE_NAME IS NULL OR _SOURCE_FILE_ROW_NUMBER IS NULL OR _SOURCE_FILE_CONTENT_KEY IS NULL OR _STAGE_SCAN_TIME IS NULL OR _INGESTED_AT IS NULL OR _SYNTHETIC_FLAG IS DISTINCT FROM TRUE) FROM BRONZE.REFERENCE_PAYMENT_THRESHOLD_RAW
  UNION ALL SELECT COUNT_IF(_INGESTION_RUN_ID IS NULL OR _SOURCE_FILE_NAME IS NULL OR _SOURCE_FILE_ROW_NUMBER IS NULL OR _SOURCE_FILE_CONTENT_KEY IS NULL OR _STAGE_SCAN_TIME IS NULL OR _INGESTED_AT IS NULL OR _SYNTHETIC_FLAG IS DISTINCT FROM TRUE) FROM BRONZE.GOVERNANCE_REFERENCE_RAW
);

SELECT INGESTION_RUN_ID, SOURCE_ID, SOURCE_FILE_NAME, SOURCE_FILE_CONTENT_KEY,
       RECORDS_LOADED, LOAD_STATUS
FROM AUDIT.INGESTION_FILE_EVIDENCE
ORDER BY INGESTION_RUN_ID, SOURCE_ID;

-- SNOWFLAKE NATIVE CLASSIFICATION — OPTIONAL
-- EXECUTE ONLY WHEN FEATURE AVAILABLE.
-- Empty results mean PENDING/NOT OBSERVED, never a project-tag PASS.
-- SELECT *
-- FROM TABLE(TRUSTED_AI_GOVERNANCE.INFORMATION_SCHEMA.TAG_REFERENCES_ALL_COLUMNS(
--   'TRUSTED_AI_GOVERNANCE.BRONZE.CUSTOMER_RAW', 'TABLE'
-- ))
-- WHERE TAG_DATABASE='SNOWFLAKE'
--   AND TAG_NAME IN ('SEMANTIC_CATEGORY','PRIVACY_CATEGORY');
