-- G2.3 — source-preserving Bronze business tables
-- All business attributes remain VARCHAR so deliberate semantic defects survive
-- ingestion. Only the mandatory provenance columns use native metadata types.

USE ROLE SYSADMIN;
USE DATABASE TRUSTED_AI_GOVERNANCE;
USE SCHEMA BRONZE;

CREATE TABLE IF NOT EXISTS BRONZE.CUSTOMER_RAW (
  CUSTOMER_ID VARCHAR, CUSTOMER_TYPE VARCHAR, CUSTOMER_NAME VARCHAR,
  DATE_OF_BIRTH VARCHAR, EMAIL VARCHAR, PHONE VARCHAR, ADDRESS_LINE VARCHAR,
  CITY VARCHAR, STATE VARCHAR, COUNTRY VARCHAR, POSTAL_CODE VARCHAR,
  CUSTOMER_SEGMENT VARCHAR, RISK_TIER VARCHAR, CUSTOMER_STATUS VARCHAR,
  CREATED_DATE VARCHAR,
  _SOURCE_ID VARCHAR NOT NULL, _SOURCE_FILE_NAME VARCHAR NOT NULL,
  _SOURCE_FILE_ROW_NUMBER NUMBER NOT NULL, _SOURCE_FILE_CONTENT_KEY VARCHAR NOT NULL,
  _SOURCE_FILE_LAST_MODIFIED TIMESTAMP_TZ, _STAGE_SCAN_TIME TIMESTAMP_LTZ NOT NULL,
  _INGESTION_RUN_ID VARCHAR NOT NULL, _INGESTED_AT TIMESTAMP_LTZ NOT NULL,
  _SYNTHETIC_FLAG BOOLEAN NOT NULL
) COMMENT = 'Synthetic customer source values preserved at governed Bronze with provenance';

CREATE TABLE IF NOT EXISTS BRONZE.ACCOUNT_RAW (
  ACCOUNT_ID VARCHAR, CUSTOMER_ID VARCHAR, ACCOUNT_TYPE VARCHAR,
  ACCOUNT_STATUS VARCHAR, CURRENCY_CODE VARCHAR, BRANCH_CODE VARCHAR,
  OPEN_DATE VARCHAR, AVAILABLE_BALANCE VARCHAR, ACCOUNT_COUNTRY VARCHAR,
  RELATIONSHIP_TIER VARCHAR,
  _SOURCE_ID VARCHAR NOT NULL, _SOURCE_FILE_NAME VARCHAR NOT NULL,
  _SOURCE_FILE_ROW_NUMBER NUMBER NOT NULL, _SOURCE_FILE_CONTENT_KEY VARCHAR NOT NULL,
  _SOURCE_FILE_LAST_MODIFIED TIMESTAMP_TZ, _STAGE_SCAN_TIME TIMESTAMP_LTZ NOT NULL,
  _INGESTION_RUN_ID VARCHAR NOT NULL, _INGESTED_AT TIMESTAMP_LTZ NOT NULL,
  _SYNTHETIC_FLAG BOOLEAN NOT NULL
) COMMENT = 'Synthetic account source values preserved at governed Bronze with provenance';

CREATE TABLE IF NOT EXISTS BRONZE.PAYMENT_RAW (
  PAYMENT_ID VARCHAR, ACCOUNT_ID VARCHAR, CUSTOMER_ID VARCHAR,
  PAYMENT_TIMESTAMP VARCHAR, PAYMENT_DATE VARCHAR, PAYMENT_TYPE VARCHAR,
  PAYMENT_CHANNEL VARCHAR, CURRENCY_CODE VARCHAR, PAYMENT_AMOUNT VARCHAR,
  BENEFICIARY_COUNTRY VARCHAR, BENEFICIARY_TYPE VARCHAR, PAYMENT_STATUS VARCHAR,
  PROCESSING_SYSTEM VARCHAR, REQUESTED_EXECUTION_DATE VARCHAR,
  ACTUAL_EXECUTION_DATE VARCHAR, SOURCE_REFERENCE VARCHAR,
  _SOURCE_ID VARCHAR NOT NULL, _SOURCE_FILE_NAME VARCHAR NOT NULL,
  _SOURCE_FILE_ROW_NUMBER NUMBER NOT NULL, _SOURCE_FILE_CONTENT_KEY VARCHAR NOT NULL,
  _SOURCE_FILE_LAST_MODIFIED TIMESTAMP_TZ, _STAGE_SCAN_TIME TIMESTAMP_LTZ NOT NULL,
  _INGESTION_RUN_ID VARCHAR NOT NULL, _INGESTED_AT TIMESTAMP_LTZ NOT NULL,
  _SYNTHETIC_FLAG BOOLEAN NOT NULL
) COMMENT = 'Synthetic payment source text, including deliberate DQ defects, preserved at governed Bronze';

CREATE TABLE IF NOT EXISTS BRONZE.PAYMENT_EXCEPTION_RAW (
  EXCEPTION_ID VARCHAR, PAYMENT_ID VARCHAR, CUSTOMER_ID VARCHAR, ACCOUNT_ID VARCHAR,
  EXCEPTION_TIMESTAMP VARCHAR, EXCEPTION_DATE VARCHAR, EXCEPTION_TYPE VARCHAR,
  EXCEPTION_REASON_CODE VARCHAR, EXCEPTION_REASON_DESCRIPTION VARCHAR,
  SEVERITY VARCHAR, EXCEPTION_STATUS VARCHAR, ASSIGNED_TEAM VARCHAR,
  ASSIGNED_ANALYST_ID VARCHAR, RESOLUTION_STATUS VARCHAR, RESOLUTION_CODE VARCHAR,
  RESOLVED_TIMESTAMP VARCHAR, SLA_DUE_TIMESTAMP VARCHAR, HIGH_VALUE_FLAG VARCHAR,
  REQUIRES_MANUAL_REVIEW VARCHAR,
  _SOURCE_ID VARCHAR NOT NULL, _SOURCE_FILE_NAME VARCHAR NOT NULL,
  _SOURCE_FILE_ROW_NUMBER NUMBER NOT NULL, _SOURCE_FILE_CONTENT_KEY VARCHAR NOT NULL,
  _SOURCE_FILE_LAST_MODIFIED TIMESTAMP_TZ, _STAGE_SCAN_TIME TIMESTAMP_LTZ NOT NULL,
  _INGESTION_RUN_ID VARCHAR NOT NULL, _INGESTED_AT TIMESTAMP_LTZ NOT NULL,
  _SYNTHETIC_FLAG BOOLEAN NOT NULL
) COMMENT = 'Synthetic payment-exception source values preserved without Silver validation';

CREATE TABLE IF NOT EXISTS BRONZE.SLA_EVENT_RAW (
  SLA_EVENT_ID VARCHAR, EXCEPTION_ID VARCHAR, SLA_TYPE VARCHAR,
  SLA_START_TIMESTAMP VARCHAR, SLA_DUE_TIMESTAMP VARCHAR,
  SLA_BREACHED_FLAG VARCHAR, BREACH_MINUTES VARCHAR,
  ESCALATION_REQUIRED VARCHAR, SLA_STATUS VARCHAR,
  _SOURCE_ID VARCHAR NOT NULL, _SOURCE_FILE_NAME VARCHAR NOT NULL,
  _SOURCE_FILE_ROW_NUMBER NUMBER NOT NULL, _SOURCE_FILE_CONTENT_KEY VARCHAR NOT NULL,
  _SOURCE_FILE_LAST_MODIFIED TIMESTAMP_TZ, _STAGE_SCAN_TIME TIMESTAMP_LTZ NOT NULL,
  _INGESTION_RUN_ID VARCHAR NOT NULL, _INGESTED_AT TIMESTAMP_LTZ NOT NULL,
  _SYNTHETIC_FLAG BOOLEAN NOT NULL
) COMMENT = 'Synthetic SLA source values, including invalid-time DQ evidence, preserved at Bronze';

CREATE TABLE IF NOT EXISTS BRONZE.OPERATIONS_TEAM_RAW (
  TEAM_ID VARCHAR, TEAM_NAME VARCHAR, REGION VARCHAR, MANAGER_ID VARCHAR,
  TEAM_STATUS VARCHAR,
  _SOURCE_ID VARCHAR NOT NULL, _SOURCE_FILE_NAME VARCHAR NOT NULL,
  _SOURCE_FILE_ROW_NUMBER NUMBER NOT NULL, _SOURCE_FILE_CONTENT_KEY VARCHAR NOT NULL,
  _SOURCE_FILE_LAST_MODIFIED TIMESTAMP_TZ, _STAGE_SCAN_TIME TIMESTAMP_LTZ NOT NULL,
  _INGESTION_RUN_ID VARCHAR NOT NULL, _INGESTED_AT TIMESTAMP_LTZ NOT NULL,
  _SYNTHETIC_FLAG BOOLEAN NOT NULL
) COMMENT = 'Synthetic operations-team source values preserved at governed Bronze';

CREATE TABLE IF NOT EXISTS BRONZE.OPERATIONS_USER_RAW (
  OPERATIONS_USER_ID VARCHAR, TEAM_ID VARCHAR, DISPLAY_NAME VARCHAR,
  BUSINESS_PERSONA VARCHAR, REGION VARCHAR, EMPLOYMENT_STATUS VARCHAR,
  _SOURCE_ID VARCHAR NOT NULL, _SOURCE_FILE_NAME VARCHAR NOT NULL,
  _SOURCE_FILE_ROW_NUMBER NUMBER NOT NULL, _SOURCE_FILE_CONTENT_KEY VARCHAR NOT NULL,
  _SOURCE_FILE_LAST_MODIFIED TIMESTAMP_TZ, _STAGE_SCAN_TIME TIMESTAMP_LTZ NOT NULL,
  _INGESTION_RUN_ID VARCHAR NOT NULL, _INGESTED_AT TIMESTAMP_LTZ NOT NULL,
  _SYNTHETIC_FLAG BOOLEAN NOT NULL
) COMMENT = 'Synthetic operations-user source values preserved at governed Bronze';

CREATE TABLE IF NOT EXISTS BRONZE.REFERENCE_EXCEPTION_REASON_RAW (
  EXCEPTION_REASON_CODE VARCHAR, EXCEPTION_CATEGORY VARCHAR,
  BUSINESS_DEFINITION VARCHAR, DEFAULT_SEVERITY VARCHAR,
  MANUAL_REVIEW_DEFAULT VARCHAR, ACTIVE_FLAG VARCHAR,
  EFFECTIVE_DATE VARCHAR, EXPIRY_DATE VARCHAR,
  _SOURCE_ID VARCHAR NOT NULL, _SOURCE_FILE_NAME VARCHAR NOT NULL,
  _SOURCE_FILE_ROW_NUMBER NUMBER NOT NULL, _SOURCE_FILE_CONTENT_KEY VARCHAR NOT NULL,
  _SOURCE_FILE_LAST_MODIFIED TIMESTAMP_TZ, _STAGE_SCAN_TIME TIMESTAMP_LTZ NOT NULL,
  _INGESTION_RUN_ID VARCHAR NOT NULL, _INGESTED_AT TIMESTAMP_LTZ NOT NULL,
  _SYNTHETIC_FLAG BOOLEAN NOT NULL
) COMMENT = 'Synthetic exception-reason reference values preserved at governed Bronze';

CREATE TABLE IF NOT EXISTS BRONZE.REFERENCE_PAYMENT_THRESHOLD_RAW (
  THRESHOLD_ID VARCHAR, CURRENCY_CODE VARCHAR, HIGH_VALUE_THRESHOLD VARCHAR,
  EFFECTIVE_DATE VARCHAR, EXPIRY_DATE VARCHAR, APPROVAL_STATUS VARCHAR,
  _SOURCE_ID VARCHAR NOT NULL, _SOURCE_FILE_NAME VARCHAR NOT NULL,
  _SOURCE_FILE_ROW_NUMBER NUMBER NOT NULL, _SOURCE_FILE_CONTENT_KEY VARCHAR NOT NULL,
  _SOURCE_FILE_LAST_MODIFIED TIMESTAMP_TZ, _STAGE_SCAN_TIME TIMESTAMP_LTZ NOT NULL,
  _INGESTION_RUN_ID VARCHAR NOT NULL, _INGESTED_AT TIMESTAMP_LTZ NOT NULL,
  _SYNTHETIC_FLAG BOOLEAN NOT NULL
) COMMENT = 'Synthetic governed payment-threshold reference values preserved at Bronze';

CREATE TABLE IF NOT EXISTS BRONZE.GOVERNANCE_REFERENCE_RAW (
  GOVERNANCE_REFERENCE_ID VARCHAR, ASSET_TYPE VARCHAR, ASSET_IDENTIFIER VARCHAR,
  CLASSIFICATION VARCHAR, SENSITIVITY_LEVEL VARCHAR, PERMITTED_PURPOSE VARCHAR,
  OWNER VARCHAR, EFFECTIVE_DATE VARCHAR, EXPIRY_DATE VARCHAR, GOVERNANCE_STATUS VARCHAR,
  _SOURCE_ID VARCHAR NOT NULL, _SOURCE_FILE_NAME VARCHAR NOT NULL,
  _SOURCE_FILE_ROW_NUMBER NUMBER NOT NULL, _SOURCE_FILE_CONTENT_KEY VARCHAR NOT NULL,
  _SOURCE_FILE_LAST_MODIFIED TIMESTAMP_TZ, _STAGE_SCAN_TIME TIMESTAMP_LTZ NOT NULL,
  _INGESTION_RUN_ID VARCHAR NOT NULL, _INGESTED_AT TIMESTAMP_LTZ NOT NULL,
  _SYNTHETIC_FLAG BOOLEAN NOT NULL
) COMMENT = 'Synthetic project governance-reference source values preserved at Bronze';
