-- G2.3 — controlled Bronze ingestion for the ten approved G2.2 datasets
-- Run this and 014_bronze_ingestion_evidence.sql in the same Snowflake session.
-- Snowflake COPY load history plus FORCE = FALSE prevents silent file replay.
-- ON_ERROR = ABORT_STATEMENT makes structural failures visible; source values
-- remain VARCHAR so semantic DQ defects are preserved for future Silver handling.

USE ROLE TRUSTED_AI_DATA_ENGINEER;
USE DATABASE TRUSTED_AI_GOVERNANCE;
ALTER SESSION SET TIMEZONE = 'UTC';

SET INGESTION_RUN_ID = (SELECT UUID_STRING());
SET TRACE_ID = (SELECT UUID_STRING());
SET INGESTION_STARTED_AT = (SELECT CURRENT_TIMESTAMP());

INSERT INTO AUDIT.INGESTION_RUN (
  INGESTION_RUN_ID, SOURCE_ID, INGESTION_STARTED_AT, EXECUTION_ROLE,
  STATUS, FILES_SEEN, FILES_LOADED, RECORDS_LOADED, RECORDS_REJECTED, TRACE_ID
)
SELECT $INGESTION_RUN_ID, COLUMN1, $INGESTION_STARTED_AT, CURRENT_ROLE(),
       'STARTED', 0, 0, 0, 0, $TRACE_ID
FROM VALUES
  ('SRC_CUSTOMER'), ('SRC_ACCOUNT'), ('SRC_PAYMENT'),
  ('SRC_PAYMENT_EXCEPTION'), ('SRC_SLA_EVENT'), ('SRC_OPERATIONS_TEAM'),
  ('SRC_OPERATIONS_USER'), ('SRC_REFERENCE_EXCEPTION_REASON'),
  ('SRC_REFERENCE_PAYMENT_THRESHOLD'), ('SRC_GOVERNANCE_REFERENCE');

COPY INTO BRONZE.CUSTOMER_RAW (
  CUSTOMER_ID, CUSTOMER_TYPE, CUSTOMER_NAME, DATE_OF_BIRTH, EMAIL, PHONE,
  ADDRESS_LINE, CITY, STATE, COUNTRY, POSTAL_CODE, CUSTOMER_SEGMENT, RISK_TIER,
  CUSTOMER_STATUS, CREATED_DATE, _SOURCE_ID, _SOURCE_FILE_NAME,
  _SOURCE_FILE_ROW_NUMBER, _SOURCE_FILE_CONTENT_KEY, _SOURCE_FILE_LAST_MODIFIED,
  _STAGE_SCAN_TIME, _INGESTION_RUN_ID, _INGESTED_AT, _SYNTHETIC_FLAG
)
FROM (
  SELECT t.$1, t.$2, t.$3, t.$4, t.$5, t.$6, t.$7, t.$8, t.$9, t.$10,
         t.$11, t.$12, t.$13, t.$14, t.$15, 'SRC_CUSTOMER',
         METADATA$FILENAME, METADATA$FILE_ROW_NUMBER, METADATA$FILE_CONTENT_KEY,
         METADATA$FILE_LAST_MODIFIED::TIMESTAMP_TZ, METADATA$START_SCAN_TIME,
         $INGESTION_RUN_ID, METADATA$START_SCAN_TIME, TRUE
  FROM @PLATFORM.SOURCE_STAGE/customer/
    (FILE_FORMAT => PLATFORM.SYNTHETIC_SOURCE_CSV_FORMAT) t
)
ON_ERROR = ABORT_STATEMENT FORCE = FALSE;

COPY INTO BRONZE.ACCOUNT_RAW (
  ACCOUNT_ID, CUSTOMER_ID, ACCOUNT_TYPE, ACCOUNT_STATUS, CURRENCY_CODE,
  BRANCH_CODE, OPEN_DATE, AVAILABLE_BALANCE, ACCOUNT_COUNTRY, RELATIONSHIP_TIER,
  _SOURCE_ID, _SOURCE_FILE_NAME, _SOURCE_FILE_ROW_NUMBER,
  _SOURCE_FILE_CONTENT_KEY, _SOURCE_FILE_LAST_MODIFIED, _STAGE_SCAN_TIME,
  _INGESTION_RUN_ID, _INGESTED_AT, _SYNTHETIC_FLAG
)
FROM (
  SELECT t.$1, t.$2, t.$3, t.$4, t.$5, t.$6, t.$7, t.$8, t.$9, t.$10,
         'SRC_ACCOUNT', METADATA$FILENAME, METADATA$FILE_ROW_NUMBER,
         METADATA$FILE_CONTENT_KEY, METADATA$FILE_LAST_MODIFIED::TIMESTAMP_TZ,
         METADATA$START_SCAN_TIME, $INGESTION_RUN_ID, METADATA$START_SCAN_TIME, TRUE
  FROM @PLATFORM.SOURCE_STAGE/account/
    (FILE_FORMAT => PLATFORM.SYNTHETIC_SOURCE_CSV_FORMAT) t
)
ON_ERROR = ABORT_STATEMENT FORCE = FALSE;

COPY INTO BRONZE.PAYMENT_RAW (
  PAYMENT_ID, ACCOUNT_ID, CUSTOMER_ID, PAYMENT_TIMESTAMP, PAYMENT_DATE,
  PAYMENT_TYPE, PAYMENT_CHANNEL, CURRENCY_CODE, PAYMENT_AMOUNT,
  BENEFICIARY_COUNTRY, BENEFICIARY_TYPE, PAYMENT_STATUS, PROCESSING_SYSTEM,
  REQUESTED_EXECUTION_DATE, ACTUAL_EXECUTION_DATE, SOURCE_REFERENCE,
  _SOURCE_ID, _SOURCE_FILE_NAME, _SOURCE_FILE_ROW_NUMBER,
  _SOURCE_FILE_CONTENT_KEY, _SOURCE_FILE_LAST_MODIFIED, _STAGE_SCAN_TIME,
  _INGESTION_RUN_ID, _INGESTED_AT, _SYNTHETIC_FLAG
)
FROM (
  SELECT t.$1, t.$2, t.$3, t.$4, t.$5, t.$6, t.$7, t.$8, t.$9, t.$10,
         t.$11, t.$12, t.$13, t.$14, t.$15, t.$16, 'SRC_PAYMENT',
         METADATA$FILENAME, METADATA$FILE_ROW_NUMBER, METADATA$FILE_CONTENT_KEY,
         METADATA$FILE_LAST_MODIFIED::TIMESTAMP_TZ, METADATA$START_SCAN_TIME,
         $INGESTION_RUN_ID, METADATA$START_SCAN_TIME, TRUE
  FROM @PLATFORM.SOURCE_STAGE/payment/
    (FILE_FORMAT => PLATFORM.SYNTHETIC_SOURCE_CSV_FORMAT) t
)
ON_ERROR = ABORT_STATEMENT FORCE = FALSE;

COPY INTO BRONZE.PAYMENT_EXCEPTION_RAW (
  EXCEPTION_ID, PAYMENT_ID, CUSTOMER_ID, ACCOUNT_ID, EXCEPTION_TIMESTAMP,
  EXCEPTION_DATE, EXCEPTION_TYPE, EXCEPTION_REASON_CODE,
  EXCEPTION_REASON_DESCRIPTION, SEVERITY, EXCEPTION_STATUS, ASSIGNED_TEAM,
  ASSIGNED_ANALYST_ID, RESOLUTION_STATUS, RESOLUTION_CODE, RESOLVED_TIMESTAMP,
  SLA_DUE_TIMESTAMP, HIGH_VALUE_FLAG, REQUIRES_MANUAL_REVIEW,
  _SOURCE_ID, _SOURCE_FILE_NAME, _SOURCE_FILE_ROW_NUMBER,
  _SOURCE_FILE_CONTENT_KEY, _SOURCE_FILE_LAST_MODIFIED, _STAGE_SCAN_TIME,
  _INGESTION_RUN_ID, _INGESTED_AT, _SYNTHETIC_FLAG
)
FROM (
  SELECT t.$1, t.$2, t.$3, t.$4, t.$5, t.$6, t.$7, t.$8, t.$9, t.$10,
         t.$11, t.$12, t.$13, t.$14, t.$15, t.$16, t.$17, t.$18, t.$19,
         'SRC_PAYMENT_EXCEPTION', METADATA$FILENAME, METADATA$FILE_ROW_NUMBER,
         METADATA$FILE_CONTENT_KEY, METADATA$FILE_LAST_MODIFIED::TIMESTAMP_TZ,
         METADATA$START_SCAN_TIME, $INGESTION_RUN_ID, METADATA$START_SCAN_TIME, TRUE
  FROM @PLATFORM.SOURCE_STAGE/payment_exception/
    (FILE_FORMAT => PLATFORM.SYNTHETIC_SOURCE_CSV_FORMAT) t
)
ON_ERROR = ABORT_STATEMENT FORCE = FALSE;

COPY INTO BRONZE.SLA_EVENT_RAW (
  SLA_EVENT_ID, EXCEPTION_ID, SLA_TYPE, SLA_START_TIMESTAMP, SLA_DUE_TIMESTAMP,
  SLA_BREACHED_FLAG, BREACH_MINUTES, ESCALATION_REQUIRED, SLA_STATUS,
  _SOURCE_ID, _SOURCE_FILE_NAME, _SOURCE_FILE_ROW_NUMBER,
  _SOURCE_FILE_CONTENT_KEY, _SOURCE_FILE_LAST_MODIFIED, _STAGE_SCAN_TIME,
  _INGESTION_RUN_ID, _INGESTED_AT, _SYNTHETIC_FLAG
)
FROM (
  SELECT t.$1, t.$2, t.$3, t.$4, t.$5, t.$6, t.$7, t.$8, t.$9,
         'SRC_SLA_EVENT', METADATA$FILENAME, METADATA$FILE_ROW_NUMBER,
         METADATA$FILE_CONTENT_KEY, METADATA$FILE_LAST_MODIFIED::TIMESTAMP_TZ,
         METADATA$START_SCAN_TIME, $INGESTION_RUN_ID, METADATA$START_SCAN_TIME, TRUE
  FROM @PLATFORM.SOURCE_STAGE/sla_event/
    (FILE_FORMAT => PLATFORM.SYNTHETIC_SOURCE_CSV_FORMAT) t
)
ON_ERROR = ABORT_STATEMENT FORCE = FALSE;

COPY INTO BRONZE.OPERATIONS_TEAM_RAW (
  TEAM_ID, TEAM_NAME, REGION, MANAGER_ID, TEAM_STATUS,
  _SOURCE_ID, _SOURCE_FILE_NAME, _SOURCE_FILE_ROW_NUMBER,
  _SOURCE_FILE_CONTENT_KEY, _SOURCE_FILE_LAST_MODIFIED, _STAGE_SCAN_TIME,
  _INGESTION_RUN_ID, _INGESTED_AT, _SYNTHETIC_FLAG
)
FROM (
  SELECT t.$1, t.$2, t.$3, t.$4, t.$5, 'SRC_OPERATIONS_TEAM',
         METADATA$FILENAME, METADATA$FILE_ROW_NUMBER, METADATA$FILE_CONTENT_KEY,
         METADATA$FILE_LAST_MODIFIED::TIMESTAMP_TZ, METADATA$START_SCAN_TIME,
         $INGESTION_RUN_ID, METADATA$START_SCAN_TIME, TRUE
  FROM @PLATFORM.SOURCE_STAGE/operations_team/
    (FILE_FORMAT => PLATFORM.SYNTHETIC_SOURCE_CSV_FORMAT) t
)
ON_ERROR = ABORT_STATEMENT FORCE = FALSE;

COPY INTO BRONZE.OPERATIONS_USER_RAW (
  OPERATIONS_USER_ID, TEAM_ID, DISPLAY_NAME, BUSINESS_PERSONA, REGION,
  EMPLOYMENT_STATUS, _SOURCE_ID, _SOURCE_FILE_NAME, _SOURCE_FILE_ROW_NUMBER,
  _SOURCE_FILE_CONTENT_KEY, _SOURCE_FILE_LAST_MODIFIED, _STAGE_SCAN_TIME,
  _INGESTION_RUN_ID, _INGESTED_AT, _SYNTHETIC_FLAG
)
FROM (
  SELECT t.$1, t.$2, t.$3, t.$4, t.$5, t.$6, 'SRC_OPERATIONS_USER',
         METADATA$FILENAME, METADATA$FILE_ROW_NUMBER, METADATA$FILE_CONTENT_KEY,
         METADATA$FILE_LAST_MODIFIED::TIMESTAMP_TZ, METADATA$START_SCAN_TIME,
         $INGESTION_RUN_ID, METADATA$START_SCAN_TIME, TRUE
  FROM @PLATFORM.SOURCE_STAGE/operations_user/
    (FILE_FORMAT => PLATFORM.SYNTHETIC_SOURCE_CSV_FORMAT) t
)
ON_ERROR = ABORT_STATEMENT FORCE = FALSE;

COPY INTO BRONZE.REFERENCE_EXCEPTION_REASON_RAW (
  EXCEPTION_REASON_CODE, EXCEPTION_CATEGORY, BUSINESS_DEFINITION,
  DEFAULT_SEVERITY, MANUAL_REVIEW_DEFAULT, ACTIVE_FLAG, EFFECTIVE_DATE,
  EXPIRY_DATE, _SOURCE_ID, _SOURCE_FILE_NAME, _SOURCE_FILE_ROW_NUMBER,
  _SOURCE_FILE_CONTENT_KEY, _SOURCE_FILE_LAST_MODIFIED, _STAGE_SCAN_TIME,
  _INGESTION_RUN_ID, _INGESTED_AT, _SYNTHETIC_FLAG
)
FROM (
  SELECT t.$1, t.$2, t.$3, t.$4, t.$5, t.$6, t.$7, t.$8,
         'SRC_REFERENCE_EXCEPTION_REASON', METADATA$FILENAME,
         METADATA$FILE_ROW_NUMBER, METADATA$FILE_CONTENT_KEY,
         METADATA$FILE_LAST_MODIFIED::TIMESTAMP_TZ, METADATA$START_SCAN_TIME,
         $INGESTION_RUN_ID, METADATA$START_SCAN_TIME, TRUE
  FROM @PLATFORM.SOURCE_STAGE/reference_exception_reason/
    (FILE_FORMAT => PLATFORM.SYNTHETIC_SOURCE_CSV_FORMAT) t
)
ON_ERROR = ABORT_STATEMENT FORCE = FALSE;

COPY INTO BRONZE.REFERENCE_PAYMENT_THRESHOLD_RAW (
  THRESHOLD_ID, CURRENCY_CODE, HIGH_VALUE_THRESHOLD, EFFECTIVE_DATE,
  EXPIRY_DATE, APPROVAL_STATUS, _SOURCE_ID, _SOURCE_FILE_NAME,
  _SOURCE_FILE_ROW_NUMBER, _SOURCE_FILE_CONTENT_KEY,
  _SOURCE_FILE_LAST_MODIFIED, _STAGE_SCAN_TIME, _INGESTION_RUN_ID,
  _INGESTED_AT, _SYNTHETIC_FLAG
)
FROM (
  SELECT t.$1, t.$2, t.$3, t.$4, t.$5, t.$6,
         'SRC_REFERENCE_PAYMENT_THRESHOLD', METADATA$FILENAME,
         METADATA$FILE_ROW_NUMBER, METADATA$FILE_CONTENT_KEY,
         METADATA$FILE_LAST_MODIFIED::TIMESTAMP_TZ, METADATA$START_SCAN_TIME,
         $INGESTION_RUN_ID, METADATA$START_SCAN_TIME, TRUE
  FROM @PLATFORM.SOURCE_STAGE/reference_payment_threshold/
    (FILE_FORMAT => PLATFORM.SYNTHETIC_SOURCE_CSV_FORMAT) t
)
ON_ERROR = ABORT_STATEMENT FORCE = FALSE;

COPY INTO BRONZE.GOVERNANCE_REFERENCE_RAW (
  GOVERNANCE_REFERENCE_ID, ASSET_TYPE, ASSET_IDENTIFIER, CLASSIFICATION,
  SENSITIVITY_LEVEL, PERMITTED_PURPOSE, OWNER, EFFECTIVE_DATE, EXPIRY_DATE,
  GOVERNANCE_STATUS, _SOURCE_ID, _SOURCE_FILE_NAME, _SOURCE_FILE_ROW_NUMBER,
  _SOURCE_FILE_CONTENT_KEY, _SOURCE_FILE_LAST_MODIFIED, _STAGE_SCAN_TIME,
  _INGESTION_RUN_ID, _INGESTED_AT, _SYNTHETIC_FLAG
)
FROM (
  SELECT t.$1, t.$2, t.$3, t.$4, t.$5, t.$6, t.$7, t.$8, t.$9, t.$10,
         'SRC_GOVERNANCE_REFERENCE', METADATA$FILENAME,
         METADATA$FILE_ROW_NUMBER, METADATA$FILE_CONTENT_KEY,
         METADATA$FILE_LAST_MODIFIED::TIMESTAMP_TZ, METADATA$START_SCAN_TIME,
         $INGESTION_RUN_ID, METADATA$START_SCAN_TIME, TRUE
  FROM @PLATFORM.SOURCE_STAGE/governance_reference/
    (FILE_FORMAT => PLATFORM.SYNTHETIC_SOURCE_CSV_FORMAT) t
)
ON_ERROR = ABORT_STATEMENT FORCE = FALSE;

SELECT $INGESTION_RUN_ID AS INGESTION_RUN_ID, $TRACE_ID AS TRACE_ID,
       'COPY statements completed; run 014_bronze_ingestion_evidence.sql in this session' AS NEXT_STEP;
