-- G2.3 — finalize Bronze ingestion run and file evidence
-- Prerequisite: execute immediately after 013 in the same session so the
-- INGESTION_RUN_ID and TRACE_ID session variables remain available.

USE ROLE TRUSTED_AI_DATA_ENGINEER;
USE DATABASE TRUSTED_AI_GOVERNANCE;

MERGE INTO AUDIT.INGESTION_FILE_EVIDENCE AS TARGET
USING (
  SELECT _INGESTION_RUN_ID AS INGESTION_RUN_ID, _SOURCE_ID AS SOURCE_ID,
         _SOURCE_FILE_NAME AS SOURCE_FILE_NAME,
         _SOURCE_FILE_CONTENT_KEY AS SOURCE_FILE_CONTENT_KEY,
         MAX(_SOURCE_FILE_LAST_MODIFIED) AS SOURCE_FILE_LAST_MODIFIED,
         MIN(_STAGE_SCAN_TIME) AS STAGE_SCAN_TIME,
         COUNT(*) AS RECORDS_LOADED, 'LOADED' AS LOAD_STATUS
  FROM (
    SELECT _INGESTION_RUN_ID, _SOURCE_ID, _SOURCE_FILE_NAME, _SOURCE_FILE_CONTENT_KEY, _SOURCE_FILE_LAST_MODIFIED, _STAGE_SCAN_TIME FROM BRONZE.CUSTOMER_RAW UNION ALL
    SELECT _INGESTION_RUN_ID, _SOURCE_ID, _SOURCE_FILE_NAME, _SOURCE_FILE_CONTENT_KEY, _SOURCE_FILE_LAST_MODIFIED, _STAGE_SCAN_TIME FROM BRONZE.ACCOUNT_RAW UNION ALL
    SELECT _INGESTION_RUN_ID, _SOURCE_ID, _SOURCE_FILE_NAME, _SOURCE_FILE_CONTENT_KEY, _SOURCE_FILE_LAST_MODIFIED, _STAGE_SCAN_TIME FROM BRONZE.PAYMENT_RAW UNION ALL
    SELECT _INGESTION_RUN_ID, _SOURCE_ID, _SOURCE_FILE_NAME, _SOURCE_FILE_CONTENT_KEY, _SOURCE_FILE_LAST_MODIFIED, _STAGE_SCAN_TIME FROM BRONZE.PAYMENT_EXCEPTION_RAW UNION ALL
    SELECT _INGESTION_RUN_ID, _SOURCE_ID, _SOURCE_FILE_NAME, _SOURCE_FILE_CONTENT_KEY, _SOURCE_FILE_LAST_MODIFIED, _STAGE_SCAN_TIME FROM BRONZE.SLA_EVENT_RAW UNION ALL
    SELECT _INGESTION_RUN_ID, _SOURCE_ID, _SOURCE_FILE_NAME, _SOURCE_FILE_CONTENT_KEY, _SOURCE_FILE_LAST_MODIFIED, _STAGE_SCAN_TIME FROM BRONZE.OPERATIONS_TEAM_RAW UNION ALL
    SELECT _INGESTION_RUN_ID, _SOURCE_ID, _SOURCE_FILE_NAME, _SOURCE_FILE_CONTENT_KEY, _SOURCE_FILE_LAST_MODIFIED, _STAGE_SCAN_TIME FROM BRONZE.OPERATIONS_USER_RAW UNION ALL
    SELECT _INGESTION_RUN_ID, _SOURCE_ID, _SOURCE_FILE_NAME, _SOURCE_FILE_CONTENT_KEY, _SOURCE_FILE_LAST_MODIFIED, _STAGE_SCAN_TIME FROM BRONZE.REFERENCE_EXCEPTION_REASON_RAW UNION ALL
    SELECT _INGESTION_RUN_ID, _SOURCE_ID, _SOURCE_FILE_NAME, _SOURCE_FILE_CONTENT_KEY, _SOURCE_FILE_LAST_MODIFIED, _STAGE_SCAN_TIME FROM BRONZE.REFERENCE_PAYMENT_THRESHOLD_RAW UNION ALL
    SELECT _INGESTION_RUN_ID, _SOURCE_ID, _SOURCE_FILE_NAME, _SOURCE_FILE_CONTENT_KEY, _SOURCE_FILE_LAST_MODIFIED, _STAGE_SCAN_TIME FROM BRONZE.GOVERNANCE_REFERENCE_RAW
  )
  WHERE _INGESTION_RUN_ID = $INGESTION_RUN_ID
  GROUP BY _INGESTION_RUN_ID, _SOURCE_ID, _SOURCE_FILE_NAME,
           _SOURCE_FILE_CONTENT_KEY
) AS SOURCE
ON TARGET.INGESTION_RUN_ID = SOURCE.INGESTION_RUN_ID
AND TARGET.SOURCE_ID = SOURCE.SOURCE_ID
AND TARGET.SOURCE_FILE_NAME = SOURCE.SOURCE_FILE_NAME
AND TARGET.SOURCE_FILE_CONTENT_KEY = SOURCE.SOURCE_FILE_CONTENT_KEY
WHEN MATCHED THEN UPDATE SET
  SOURCE_FILE_LAST_MODIFIED = SOURCE.SOURCE_FILE_LAST_MODIFIED,
  STAGE_SCAN_TIME = SOURCE.STAGE_SCAN_TIME,
  RECORDS_LOADED = SOURCE.RECORDS_LOADED,
  LOAD_STATUS = SOURCE.LOAD_STATUS
WHEN NOT MATCHED THEN INSERT (
  INGESTION_RUN_ID, SOURCE_ID, SOURCE_FILE_NAME, SOURCE_FILE_CONTENT_KEY,
  SOURCE_FILE_LAST_MODIFIED, STAGE_SCAN_TIME, RECORDS_LOADED, LOAD_STATUS
) VALUES (
  SOURCE.INGESTION_RUN_ID, SOURCE.SOURCE_ID, SOURCE.SOURCE_FILE_NAME,
  SOURCE.SOURCE_FILE_CONTENT_KEY, SOURCE.SOURCE_FILE_LAST_MODIFIED,
  SOURCE.STAGE_SCAN_TIME, SOURCE.RECORDS_LOADED, SOURCE.LOAD_STATUS
);

UPDATE AUDIT.INGESTION_RUN AS RUN
SET INGESTION_COMPLETED_AT = CURRENT_TIMESTAMP(),
    STATUS = 'COMPLETED',
    FILES_SEEN = SUMMARY.FILE_COUNT,
    FILES_LOADED = SUMMARY.FILE_COUNT,
    RECORDS_LOADED = SUMMARY.RECORD_COUNT,
    RECORDS_REJECTED = 0,
    ERROR_MESSAGE = NULL
FROM (
  SELECT _INGESTION_RUN_ID AS INGESTION_RUN_ID, _SOURCE_ID AS SOURCE_ID,
         COUNT(DISTINCT _SOURCE_FILE_CONTENT_KEY) AS FILE_COUNT,
         COUNT(*) AS RECORD_COUNT
  FROM (
    SELECT _INGESTION_RUN_ID, _SOURCE_ID, _SOURCE_FILE_CONTENT_KEY FROM BRONZE.CUSTOMER_RAW UNION ALL
    SELECT _INGESTION_RUN_ID, _SOURCE_ID, _SOURCE_FILE_CONTENT_KEY FROM BRONZE.ACCOUNT_RAW UNION ALL
    SELECT _INGESTION_RUN_ID, _SOURCE_ID, _SOURCE_FILE_CONTENT_KEY FROM BRONZE.PAYMENT_RAW UNION ALL
    SELECT _INGESTION_RUN_ID, _SOURCE_ID, _SOURCE_FILE_CONTENT_KEY FROM BRONZE.PAYMENT_EXCEPTION_RAW UNION ALL
    SELECT _INGESTION_RUN_ID, _SOURCE_ID, _SOURCE_FILE_CONTENT_KEY FROM BRONZE.SLA_EVENT_RAW UNION ALL
    SELECT _INGESTION_RUN_ID, _SOURCE_ID, _SOURCE_FILE_CONTENT_KEY FROM BRONZE.OPERATIONS_TEAM_RAW UNION ALL
    SELECT _INGESTION_RUN_ID, _SOURCE_ID, _SOURCE_FILE_CONTENT_KEY FROM BRONZE.OPERATIONS_USER_RAW UNION ALL
    SELECT _INGESTION_RUN_ID, _SOURCE_ID, _SOURCE_FILE_CONTENT_KEY FROM BRONZE.REFERENCE_EXCEPTION_REASON_RAW UNION ALL
    SELECT _INGESTION_RUN_ID, _SOURCE_ID, _SOURCE_FILE_CONTENT_KEY FROM BRONZE.REFERENCE_PAYMENT_THRESHOLD_RAW UNION ALL
    SELECT _INGESTION_RUN_ID, _SOURCE_ID, _SOURCE_FILE_CONTENT_KEY FROM BRONZE.GOVERNANCE_REFERENCE_RAW
  )
  WHERE _INGESTION_RUN_ID = $INGESTION_RUN_ID
  GROUP BY _INGESTION_RUN_ID, _SOURCE_ID
) AS SUMMARY
WHERE RUN.INGESTION_RUN_ID = SUMMARY.INGESTION_RUN_ID
  AND RUN.SOURCE_ID = SUMMARY.SOURCE_ID;

SELECT * FROM AUDIT.INGESTION_RUN
WHERE INGESTION_RUN_ID = $INGESTION_RUN_ID
ORDER BY SOURCE_ID;

SELECT * FROM AUDIT.INGESTION_FILE_EVIDENCE
WHERE INGESTION_RUN_ID = $INGESTION_RUN_ID
ORDER BY SOURCE_ID, SOURCE_FILE_NAME;

-- COPY uses ABORT_STATEMENT, so a structural failure stops 013 and preserves
-- STARTED evidence. The operator must diagnose the COPY error and explicitly
-- mark affected rows FAILED with a minimized ERROR_MESSAGE before replay.
-- No automated catch block is fabricated in this transparent SQL-only baseline.

-- Snowflake-native delayed evidence is inspected separately by DATA_STEWARD or
-- AUDITOR (Enterprise Edition; typically up to three hours). This query is
-- deliberately not executed as DATA_ENGINEER:
-- SELECT DISTINCT AH.QUERY_ID, AH.QUERY_START_TIME, AH.USER_NAME, AH.ROLE_NAME,
--        AH.DIRECT_OBJECTS_ACCESSED
-- FROM SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY AS AH,
-- LATERAL FLATTEN(INPUT => AH.BASE_OBJECTS_ACCESSED) AS OBJECTS
-- WHERE AH.QUERY_START_TIME >= $INGESTION_STARTED_AT
--   AND OBJECTS.VALUE:objectName::VARCHAR ILIKE 'TRUSTED_AI_GOVERNANCE.%'
-- ORDER BY AH.QUERY_START_TIME;
