-- G2.3 — Bronze execution validation
-- A PASS result is meaningful only after Snowflake execution and evidence capture.

USE DATABASE TRUSTED_AI_GOVERNANCE;

-- 1. Exactly the ten expected Bronze business tables exist.
SELECT 'BRONZE_TABLE_COUNT' AS CHECK_NAME, COUNT(*) AS OBSERVED, 10 AS EXPECTED,
       IFF(COUNT(*) = 10, 'PASS', 'FAIL') AS RESULT
FROM TRUSTED_AI_GOVERNANCE.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'BRONZE'
  AND TABLE_NAME IN ('CUSTOMER_RAW', 'ACCOUNT_RAW', 'PAYMENT_RAW',
    'PAYMENT_EXCEPTION_RAW', 'SLA_EVENT_RAW', 'OPERATIONS_TEAM_RAW',
    'OPERATIONS_USER_RAW', 'REFERENCE_EXCEPTION_REASON_RAW',
    'REFERENCE_PAYMENT_THRESHOLD_RAW', 'GOVERNANCE_REFERENCE_RAW');

-- 2. Approved G2.2 source counts.
SELECT 'CUSTOMER_RAW' AS TABLE_NAME, COUNT(*) AS OBSERVED, 1000 AS EXPECTED, IFF(COUNT(*)=1000,'PASS','FAIL') AS RESULT FROM BRONZE.CUSTOMER_RAW
UNION ALL SELECT 'ACCOUNT_RAW', COUNT(*), 1500, IFF(COUNT(*)=1500,'PASS','FAIL') FROM BRONZE.ACCOUNT_RAW
UNION ALL SELECT 'PAYMENT_RAW', COUNT(*), 25000, IFF(COUNT(*)=25000,'PASS','FAIL') FROM BRONZE.PAYMENT_RAW
UNION ALL SELECT 'PAYMENT_EXCEPTION_RAW', COUNT(*), 2500, IFF(COUNT(*)=2500,'PASS','FAIL') FROM BRONZE.PAYMENT_EXCEPTION_RAW
UNION ALL SELECT 'SLA_EVENT_RAW', COUNT(*), 2500, IFF(COUNT(*)=2500,'PASS','FAIL') FROM BRONZE.SLA_EVENT_RAW
UNION ALL SELECT 'OPERATIONS_TEAM_RAW', COUNT(*), 5, IFF(COUNT(*)=5,'PASS','FAIL') FROM BRONZE.OPERATIONS_TEAM_RAW
UNION ALL SELECT 'OPERATIONS_USER_RAW', COUNT(*), 25, IFF(COUNT(*)=25,'PASS','FAIL') FROM BRONZE.OPERATIONS_USER_RAW
UNION ALL SELECT 'REFERENCE_EXCEPTION_REASON_RAW', COUNT(*), 12, IFF(COUNT(*)=12,'PASS','FAIL') FROM BRONZE.REFERENCE_EXCEPTION_REASON_RAW
UNION ALL SELECT 'REFERENCE_PAYMENT_THRESHOLD_RAW', COUNT(*), 4, IFF(COUNT(*)=4,'PASS','FAIL') FROM BRONZE.REFERENCE_PAYMENT_THRESHOLD_RAW
UNION ALL SELECT 'GOVERNANCE_REFERENCE_RAW', COUNT(*), 24, IFF(COUNT(*)=24,'PASS','FAIL') FROM BRONZE.GOVERNANCE_REFERENCE_RAW;

-- 3. Mandatory metadata is populated and every row is explicitly synthetic.
SELECT TABLE_NAME, MISSING_CONTEXT_ROWS, IFF(MISSING_CONTEXT_ROWS=0,'PASS','FAIL') AS RESULT
FROM (
  SELECT 'CUSTOMER_RAW' TABLE_NAME, COUNT_IF(_SOURCE_ID IS NULL OR _SOURCE_FILE_NAME IS NULL OR _SOURCE_FILE_ROW_NUMBER IS NULL OR _SOURCE_FILE_CONTENT_KEY IS NULL OR _STAGE_SCAN_TIME IS NULL OR _INGESTION_RUN_ID IS NULL OR _INGESTED_AT IS NULL OR _SYNTHETIC_FLAG IS DISTINCT FROM TRUE) MISSING_CONTEXT_ROWS FROM BRONZE.CUSTOMER_RAW
  UNION ALL SELECT 'ACCOUNT_RAW', COUNT_IF(_SOURCE_ID IS NULL OR _SOURCE_FILE_NAME IS NULL OR _SOURCE_FILE_ROW_NUMBER IS NULL OR _SOURCE_FILE_CONTENT_KEY IS NULL OR _STAGE_SCAN_TIME IS NULL OR _INGESTION_RUN_ID IS NULL OR _INGESTED_AT IS NULL OR _SYNTHETIC_FLAG IS DISTINCT FROM TRUE) FROM BRONZE.ACCOUNT_RAW
  UNION ALL SELECT 'PAYMENT_RAW', COUNT_IF(_SOURCE_ID IS NULL OR _SOURCE_FILE_NAME IS NULL OR _SOURCE_FILE_ROW_NUMBER IS NULL OR _SOURCE_FILE_CONTENT_KEY IS NULL OR _STAGE_SCAN_TIME IS NULL OR _INGESTION_RUN_ID IS NULL OR _INGESTED_AT IS NULL OR _SYNTHETIC_FLAG IS DISTINCT FROM TRUE) FROM BRONZE.PAYMENT_RAW
  UNION ALL SELECT 'PAYMENT_EXCEPTION_RAW', COUNT_IF(_SOURCE_ID IS NULL OR _SOURCE_FILE_NAME IS NULL OR _SOURCE_FILE_ROW_NUMBER IS NULL OR _SOURCE_FILE_CONTENT_KEY IS NULL OR _STAGE_SCAN_TIME IS NULL OR _INGESTION_RUN_ID IS NULL OR _INGESTED_AT IS NULL OR _SYNTHETIC_FLAG IS DISTINCT FROM TRUE) FROM BRONZE.PAYMENT_EXCEPTION_RAW
  UNION ALL SELECT 'SLA_EVENT_RAW', COUNT_IF(_SOURCE_ID IS NULL OR _SOURCE_FILE_NAME IS NULL OR _SOURCE_FILE_ROW_NUMBER IS NULL OR _SOURCE_FILE_CONTENT_KEY IS NULL OR _STAGE_SCAN_TIME IS NULL OR _INGESTION_RUN_ID IS NULL OR _INGESTED_AT IS NULL OR _SYNTHETIC_FLAG IS DISTINCT FROM TRUE) FROM BRONZE.SLA_EVENT_RAW
  UNION ALL SELECT 'OPERATIONS_TEAM_RAW', COUNT_IF(_SOURCE_ID IS NULL OR _SOURCE_FILE_NAME IS NULL OR _SOURCE_FILE_ROW_NUMBER IS NULL OR _SOURCE_FILE_CONTENT_KEY IS NULL OR _STAGE_SCAN_TIME IS NULL OR _INGESTION_RUN_ID IS NULL OR _INGESTED_AT IS NULL OR _SYNTHETIC_FLAG IS DISTINCT FROM TRUE) FROM BRONZE.OPERATIONS_TEAM_RAW
  UNION ALL SELECT 'OPERATIONS_USER_RAW', COUNT_IF(_SOURCE_ID IS NULL OR _SOURCE_FILE_NAME IS NULL OR _SOURCE_FILE_ROW_NUMBER IS NULL OR _SOURCE_FILE_CONTENT_KEY IS NULL OR _STAGE_SCAN_TIME IS NULL OR _INGESTION_RUN_ID IS NULL OR _INGESTED_AT IS NULL OR _SYNTHETIC_FLAG IS DISTINCT FROM TRUE) FROM BRONZE.OPERATIONS_USER_RAW
  UNION ALL SELECT 'REFERENCE_EXCEPTION_REASON_RAW', COUNT_IF(_SOURCE_ID IS NULL OR _SOURCE_FILE_NAME IS NULL OR _SOURCE_FILE_ROW_NUMBER IS NULL OR _SOURCE_FILE_CONTENT_KEY IS NULL OR _STAGE_SCAN_TIME IS NULL OR _INGESTION_RUN_ID IS NULL OR _INGESTED_AT IS NULL OR _SYNTHETIC_FLAG IS DISTINCT FROM TRUE) FROM BRONZE.REFERENCE_EXCEPTION_REASON_RAW
  UNION ALL SELECT 'REFERENCE_PAYMENT_THRESHOLD_RAW', COUNT_IF(_SOURCE_ID IS NULL OR _SOURCE_FILE_NAME IS NULL OR _SOURCE_FILE_ROW_NUMBER IS NULL OR _SOURCE_FILE_CONTENT_KEY IS NULL OR _STAGE_SCAN_TIME IS NULL OR _INGESTION_RUN_ID IS NULL OR _INGESTED_AT IS NULL OR _SYNTHETIC_FLAG IS DISTINCT FROM TRUE) FROM BRONZE.REFERENCE_PAYMENT_THRESHOLD_RAW
  UNION ALL SELECT 'GOVERNANCE_REFERENCE_RAW', COUNT_IF(_SOURCE_ID IS NULL OR _SOURCE_FILE_NAME IS NULL OR _SOURCE_FILE_ROW_NUMBER IS NULL OR _SOURCE_FILE_CONTENT_KEY IS NULL OR _STAGE_SCAN_TIME IS NULL OR _INGESTION_RUN_ID IS NULL OR _INGESTED_AT IS NULL OR _SYNTHETIC_FLAG IS DISTINCT FROM TRUE) FROM BRONZE.GOVERNANCE_REFERENCE_RAW
);

-- 4. Stable business, DQ, and positive SLA anchors.
SELECT 'CUST_DEMO_001' ANCHOR, COUNT(*) OBSERVED, IFF(COUNT(*)=1,'PASS','FAIL') RESULT FROM BRONZE.CUSTOMER_RAW WHERE CUSTOMER_ID='CUST_DEMO_001'
UNION ALL SELECT 'ACCT_DEMO_001', COUNT(*), IFF(COUNT(*)=1,'PASS','FAIL') FROM BRONZE.ACCOUNT_RAW WHERE ACCOUNT_ID='ACCT_DEMO_001'
UNION ALL SELECT 'PAY_DEMO_001', COUNT(*), IFF(COUNT(*)=1,'PASS','FAIL') FROM BRONZE.PAYMENT_RAW WHERE PAYMENT_ID='PAY_DEMO_001'
UNION ALL SELECT 'EXC_DEMO_001', COUNT(*), IFF(COUNT(*)=1,'PASS','FAIL') FROM BRONZE.PAYMENT_EXCEPTION_RAW WHERE EXCEPTION_ID='EXC_DEMO_001'
UNION ALL SELECT 'PAY_DQ_NEGATIVE_001', COUNT(*), IFF(COUNT(*)=1,'PASS','FAIL') FROM BRONZE.PAYMENT_RAW WHERE PAYMENT_ID='PAY_DQ_NEGATIVE_001'
UNION ALL SELECT 'PAY_DQ_DUP_001', COUNT(*), IFF(COUNT(*)=1,'PASS','FAIL') FROM BRONZE.PAYMENT_RAW WHERE PAYMENT_ID='PAY_DQ_DUP_001'
UNION ALL SELECT 'EXC_DQ_TIMESTAMP_001', COUNT(*), IFF(COUNT(*)=1,'PASS','FAIL') FROM BRONZE.PAYMENT_EXCEPTION_RAW WHERE EXCEPTION_ID='EXC_DQ_TIMESTAMP_001'
UNION ALL SELECT 'SLA_DEMO_BREACH_001', COUNT(*), IFF(COUNT(*)=1,'PASS','FAIL') FROM BRONZE.SLA_EVENT_RAW WHERE SLA_EVENT_ID='SLA_DEMO_BREACH_001'
UNION ALL SELECT 'SLA_DQ_DUE_001', COUNT(*), IFF(COUNT(*)=1,'PASS','FAIL') FROM BRONZE.SLA_EVENT_RAW WHERE SLA_EVENT_ID='SLA_DQ_DUE_001';

-- 5. Selected deliberate source defects remain unchanged; no quarantine occurs here.
SELECT 'NEGATIVE_AMOUNT_PRESERVED' CHECK_NAME, COUNT(*) OBSERVED, IFF(COUNT(*)=1,'PASS','FAIL') RESULT FROM BRONZE.PAYMENT_RAW WHERE PAYMENT_ID='PAY_DQ_NEGATIVE_001' AND PAYMENT_AMOUNT='-1250.00'
UNION ALL SELECT 'INVALID_CURRENCY_PRESERVED', COUNT(*), IFF(COUNT(*)=1,'PASS','FAIL') FROM BRONZE.PAYMENT_RAW WHERE PAYMENT_ID='PAY_DQ_CURRENCY_001' AND CURRENCY_CODE='ZZZ'
UNION ALL SELECT 'MISSING_REASON_PRESERVED', COUNT(*), IFF(COUNT(*)=1,'PASS','FAIL') FROM BRONZE.PAYMENT_EXCEPTION_RAW WHERE EXCEPTION_ID='EXC_DQ_REASON_001' AND EXCEPTION_REASON_CODE IS NULL
UNION ALL SELECT 'INVALID_SLA_TIME_PRESERVED', COUNT(*), IFF(COUNT(*)=1,'PASS','FAIL') FROM BRONZE.SLA_EVENT_RAW WHERE SLA_EVENT_ID='SLA_DQ_DUE_001' AND TRY_TO_TIMESTAMP_NTZ(SLA_DUE_TIMESTAMP) < TRY_TO_TIMESTAMP_NTZ(SLA_START_TIMESTAMP)
UNION ALL SELECT 'EXPIRED_REASON_PRESERVED', COUNT(*), IFF(COUNT(*)=1,'PASS','FAIL') FROM BRONZE.PAYMENT_EXCEPTION_RAW WHERE EXCEPTION_ID='EXC_DQ_EXPIRED_REF_001' AND EXCEPTION_REASON_CODE='R_EXP';

-- 6. Run/file correlation and source registry evidence.
SELECT 'ACTIVE_SYNTHETIC_SOURCE_REGISTRY' CHECK_NAME, COUNT(*) OBSERVED, 10 EXPECTED,
       IFF(COUNT(*)=10,'PASS','FAIL') RESULT
FROM GOVERNANCE.INGESTION_SOURCE_REGISTRY
WHERE ACTIVE_FLAG=TRUE AND SYNTHETIC_FLAG=TRUE;

SELECT INGESTION_RUN_ID, COUNT(DISTINCT SOURCE_ID) SOURCES,
       SUM(RECORDS_LOADED) RECORDS_LOADED, MIN(STATUS) MIN_STATUS,
       MAX(STATUS) MAX_STATUS
FROM AUDIT.INGESTION_RUN
GROUP BY INGESTION_RUN_ID
ORDER BY MAX(INGESTION_STARTED_AT) DESC;

SELECT INGESTION_RUN_ID, COUNT(*) FILE_EVIDENCE_ROWS,
       COUNT(DISTINCT SOURCE_ID) SOURCES, SUM(RECORDS_LOADED) RECORDS_LOADED
FROM AUDIT.INGESTION_FILE_EVIDENCE
GROUP BY INGESTION_RUN_ID;

-- 7. Confirm this action did not create later-layer schemas.
SELECT SCHEMA_NAME
FROM TRUSTED_AI_GOVERNANCE.INFORMATION_SCHEMA.SCHEMATA
WHERE SCHEMA_NAME IN ('SILVER','GOLD','SEMANTIC','KNOWLEDGE','AI','AGENT','OUTPUT');
-- Expected: zero rows.
